package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvOrderSlipDetailId generated by hbm2java
 */
@Embeddable
public class NvOrderSlipDetailId implements java.io.Serializable {

	private int idOrderSlip;
	private int idOrderDetail;

	public NvOrderSlipDetailId() {
	}

	public NvOrderSlipDetailId(int idOrderSlip, int idOrderDetail) {
		this.idOrderSlip = idOrderSlip;
		this.idOrderDetail = idOrderDetail;
	}

	@Column(name = "id_order_slip", nullable = false)
	public int getIdOrderSlip() {
		return this.idOrderSlip;
	}

	public void setIdOrderSlip(int idOrderSlip) {
		this.idOrderSlip = idOrderSlip;
	}

	@Column(name = "id_order_detail", nullable = false)
	public int getIdOrderDetail() {
		return this.idOrderDetail;
	}

	public void setIdOrderDetail(int idOrderDetail) {
		this.idOrderDetail = idOrderDetail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvOrderSlipDetailId))
			return false;
		NvOrderSlipDetailId castOther = (NvOrderSlipDetailId) other;

		return (this.getIdOrderSlip() == castOther.getIdOrderSlip()) && (this.getIdOrderDetail() == castOther.getIdOrderDetail());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrderSlip();
		result = 37 * result + this.getIdOrderDetail();
		return result;
	}

}
