package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvOrderSlip generated by hbm2java
 */
@Entity
@Table(name = "nv_order_slip", catalog = "NVPrestashop")
public class NvOrderSlip implements java.io.Serializable {

	private Integer idOrderSlip;
	private BigDecimal conversionRate;
	private int idCustomer;
	private int idOrder;
	private BigDecimal totalProductsTaxExcl;
	private BigDecimal totalProductsTaxIncl;
	private BigDecimal totalShippingTaxExcl;
	private BigDecimal totalShippingTaxIncl;
	private byte shippingCost;
	private BigDecimal amount;
	private BigDecimal shippingCostAmount;
	private boolean partial;
	private boolean orderSlipType;
	private Date dateAdd;
	private Date dateUpd;

	public NvOrderSlip() {
	}

	public NvOrderSlip(BigDecimal conversionRate, int idCustomer, int idOrder, byte shippingCost, BigDecimal amount, BigDecimal shippingCostAmount,
					boolean partial, boolean orderSlipType, Date dateAdd, Date dateUpd) {
		this.conversionRate = conversionRate;
		this.idCustomer = idCustomer;
		this.idOrder = idOrder;
		this.shippingCost = shippingCost;
		this.amount = amount;
		this.shippingCostAmount = shippingCostAmount;
		this.partial = partial;
		this.orderSlipType = orderSlipType;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvOrderSlip(BigDecimal conversionRate, int idCustomer, int idOrder, BigDecimal totalProductsTaxExcl, BigDecimal totalProductsTaxIncl,
					BigDecimal totalShippingTaxExcl, BigDecimal totalShippingTaxIncl, byte shippingCost, BigDecimal amount, BigDecimal shippingCostAmount,
					boolean partial, boolean orderSlipType, Date dateAdd, Date dateUpd) {
		this.conversionRate = conversionRate;
		this.idCustomer = idCustomer;
		this.idOrder = idOrder;
		this.totalProductsTaxExcl = totalProductsTaxExcl;
		this.totalProductsTaxIncl = totalProductsTaxIncl;
		this.totalShippingTaxExcl = totalShippingTaxExcl;
		this.totalShippingTaxIncl = totalShippingTaxIncl;
		this.shippingCost = shippingCost;
		this.amount = amount;
		this.shippingCostAmount = shippingCostAmount;
		this.partial = partial;
		this.orderSlipType = orderSlipType;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_order_slip", unique = true, nullable = false)
	public Integer getIdOrderSlip() {
		return this.idOrderSlip;
	}

	public void setIdOrderSlip(Integer idOrderSlip) {
		this.idOrderSlip = idOrderSlip;
	}

	@Column(name = "conversion_rate", nullable = false, precision = 13, scale = 6)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "total_products_tax_excl", precision = 20, scale = 6)
	public BigDecimal getTotalProductsTaxExcl() {
		return this.totalProductsTaxExcl;
	}

	public void setTotalProductsTaxExcl(BigDecimal totalProductsTaxExcl) {
		this.totalProductsTaxExcl = totalProductsTaxExcl;
	}

	@Column(name = "total_products_tax_incl", precision = 20, scale = 6)
	public BigDecimal getTotalProductsTaxIncl() {
		return this.totalProductsTaxIncl;
	}

	public void setTotalProductsTaxIncl(BigDecimal totalProductsTaxIncl) {
		this.totalProductsTaxIncl = totalProductsTaxIncl;
	}

	@Column(name = "total_shipping_tax_excl", precision = 20, scale = 6)
	public BigDecimal getTotalShippingTaxExcl() {
		return this.totalShippingTaxExcl;
	}

	public void setTotalShippingTaxExcl(BigDecimal totalShippingTaxExcl) {
		this.totalShippingTaxExcl = totalShippingTaxExcl;
	}

	@Column(name = "total_shipping_tax_incl", precision = 20, scale = 6)
	public BigDecimal getTotalShippingTaxIncl() {
		return this.totalShippingTaxIncl;
	}

	public void setTotalShippingTaxIncl(BigDecimal totalShippingTaxIncl) {
		this.totalShippingTaxIncl = totalShippingTaxIncl;
	}

	@Column(name = "shipping_cost", nullable = false)
	public byte getShippingCost() {
		return this.shippingCost;
	}

	public void setShippingCost(byte shippingCost) {
		this.shippingCost = shippingCost;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "shipping_cost_amount", nullable = false, precision = 10)
	public BigDecimal getShippingCostAmount() {
		return this.shippingCostAmount;
	}

	public void setShippingCostAmount(BigDecimal shippingCostAmount) {
		this.shippingCostAmount = shippingCostAmount;
	}

	@Column(name = "partial", nullable = false)
	public boolean isPartial() {
		return this.partial;
	}

	public void setPartial(boolean partial) {
		this.partial = partial;
	}

	@Column(name = "order_slip_type", nullable = false)
	public boolean isOrderSlipType() {
		return this.orderSlipType;
	}

	public void setOrderSlipType(boolean orderSlipType) {
		this.orderSlipType = orderSlipType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
