package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvOrderReturnDetailId generated by hbm2java
 */
@Embeddable
public class NvOrderReturnDetailId implements java.io.Serializable {

	private int idOrderReturn;
	private int idOrderDetail;
	private int idCustomization;

	public NvOrderReturnDetailId() {
	}

	public NvOrderReturnDetailId(int idOrderReturn, int idOrderDetail, int idCustomization) {
		this.idOrderReturn = idOrderReturn;
		this.idOrderDetail = idOrderDetail;
		this.idCustomization = idCustomization;
	}

	@Column(name = "id_order_return", nullable = false)
	public int getIdOrderReturn() {
		return this.idOrderReturn;
	}

	public void setIdOrderReturn(int idOrderReturn) {
		this.idOrderReturn = idOrderReturn;
	}

	@Column(name = "id_order_detail", nullable = false)
	public int getIdOrderDetail() {
		return this.idOrderDetail;
	}

	public void setIdOrderDetail(int idOrderDetail) {
		this.idOrderDetail = idOrderDetail;
	}

	@Column(name = "id_customization", nullable = false)
	public int getIdCustomization() {
		return this.idCustomization;
	}

	public void setIdCustomization(int idCustomization) {
		this.idCustomization = idCustomization;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvOrderReturnDetailId))
			return false;
		NvOrderReturnDetailId castOther = (NvOrderReturnDetailId) other;

		return (this.getIdOrderReturn() == castOther.getIdOrderReturn()) && (this.getIdOrderDetail() == castOther.getIdOrderDetail())
						&& (this.getIdCustomization() == castOther.getIdCustomization());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrderReturn();
		result = 37 * result + this.getIdOrderDetail();
		result = 37 * result + this.getIdCustomization();
		return result;
	}

}
