package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvOrderInvoice generated by hbm2java
 */
@Entity
@Table(name = "nv_order_invoice", catalog = "NVPrestashop")
public class NvOrderInvoice implements java.io.Serializable {

	private Integer idOrderInvoice;
	private int idOrder;
	private int number;
	private int deliveryNumber;
	private Date deliveryDate;
	private BigDecimal totalDiscountTaxExcl;
	private BigDecimal totalDiscountTaxIncl;
	private BigDecimal totalPaidTaxExcl;
	private BigDecimal totalPaidTaxIncl;
	private BigDecimal totalProducts;
	private BigDecimal totalProductsWt;
	private BigDecimal totalShippingTaxExcl;
	private BigDecimal totalShippingTaxIncl;
	private int shippingTaxComputationMethod;
	private BigDecimal totalWrappingTaxExcl;
	private BigDecimal totalWrappingTaxIncl;
	private String shopAddress;
	private String invoiceAddress;
	private String deliveryAddress;
	private String note;
	private Date dateAdd;
	private String slotName;
	private int idDeliveryBoy;
	private String orderComment;

	public NvOrderInvoice() {
	}

	public NvOrderInvoice(int idOrder, int number, int deliveryNumber, BigDecimal totalDiscountTaxExcl, BigDecimal totalDiscountTaxIncl,
					BigDecimal totalPaidTaxExcl, BigDecimal totalPaidTaxIncl, BigDecimal totalProducts, BigDecimal totalProductsWt,
					BigDecimal totalShippingTaxExcl, BigDecimal totalShippingTaxIncl, int shippingTaxComputationMethod, BigDecimal totalWrappingTaxExcl,
					BigDecimal totalWrappingTaxIncl, Date dateAdd, String slotName, int idDeliveryBoy, String orderComment) {
		this.idOrder = idOrder;
		this.number = number;
		this.deliveryNumber = deliveryNumber;
		this.totalDiscountTaxExcl = totalDiscountTaxExcl;
		this.totalDiscountTaxIncl = totalDiscountTaxIncl;
		this.totalPaidTaxExcl = totalPaidTaxExcl;
		this.totalPaidTaxIncl = totalPaidTaxIncl;
		this.totalProducts = totalProducts;
		this.totalProductsWt = totalProductsWt;
		this.totalShippingTaxExcl = totalShippingTaxExcl;
		this.totalShippingTaxIncl = totalShippingTaxIncl;
		this.shippingTaxComputationMethod = shippingTaxComputationMethod;
		this.totalWrappingTaxExcl = totalWrappingTaxExcl;
		this.totalWrappingTaxIncl = totalWrappingTaxIncl;
		this.dateAdd = dateAdd;
		this.slotName = slotName;
		this.idDeliveryBoy = idDeliveryBoy;
		this.orderComment = orderComment;
	}

	public NvOrderInvoice(int idOrder, int number, int deliveryNumber, Date deliveryDate, BigDecimal totalDiscountTaxExcl, BigDecimal totalDiscountTaxIncl,
					BigDecimal totalPaidTaxExcl, BigDecimal totalPaidTaxIncl, BigDecimal totalProducts, BigDecimal totalProductsWt,
					BigDecimal totalShippingTaxExcl, BigDecimal totalShippingTaxIncl, int shippingTaxComputationMethod, BigDecimal totalWrappingTaxExcl,
					BigDecimal totalWrappingTaxIncl, String shopAddress, String invoiceAddress, String deliveryAddress, String note, Date dateAdd,
					String slotName, int idDeliveryBoy, String orderComment) {
		this.idOrder = idOrder;
		this.number = number;
		this.deliveryNumber = deliveryNumber;
		this.deliveryDate = deliveryDate;
		this.totalDiscountTaxExcl = totalDiscountTaxExcl;
		this.totalDiscountTaxIncl = totalDiscountTaxIncl;
		this.totalPaidTaxExcl = totalPaidTaxExcl;
		this.totalPaidTaxIncl = totalPaidTaxIncl;
		this.totalProducts = totalProducts;
		this.totalProductsWt = totalProductsWt;
		this.totalShippingTaxExcl = totalShippingTaxExcl;
		this.totalShippingTaxIncl = totalShippingTaxIncl;
		this.shippingTaxComputationMethod = shippingTaxComputationMethod;
		this.totalWrappingTaxExcl = totalWrappingTaxExcl;
		this.totalWrappingTaxIncl = totalWrappingTaxIncl;
		this.shopAddress = shopAddress;
		this.invoiceAddress = invoiceAddress;
		this.deliveryAddress = deliveryAddress;
		this.note = note;
		this.dateAdd = dateAdd;
		this.slotName = slotName;
		this.idDeliveryBoy = idDeliveryBoy;
		this.orderComment = orderComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_order_invoice", unique = true, nullable = false)
	public Integer getIdOrderInvoice() {
		return this.idOrderInvoice;
	}

	public void setIdOrderInvoice(Integer idOrderInvoice) {
		this.idOrderInvoice = idOrderInvoice;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "delivery_number", nullable = false)
	public int getDeliveryNumber() {
		return this.deliveryNumber;
	}

	public void setDeliveryNumber(int deliveryNumber) {
		this.deliveryNumber = deliveryNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_date", length = 0)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "total_discount_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalDiscountTaxExcl() {
		return this.totalDiscountTaxExcl;
	}

	public void setTotalDiscountTaxExcl(BigDecimal totalDiscountTaxExcl) {
		this.totalDiscountTaxExcl = totalDiscountTaxExcl;
	}

	@Column(name = "total_discount_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalDiscountTaxIncl() {
		return this.totalDiscountTaxIncl;
	}

	public void setTotalDiscountTaxIncl(BigDecimal totalDiscountTaxIncl) {
		this.totalDiscountTaxIncl = totalDiscountTaxIncl;
	}

	@Column(name = "total_paid_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalPaidTaxExcl() {
		return this.totalPaidTaxExcl;
	}

	public void setTotalPaidTaxExcl(BigDecimal totalPaidTaxExcl) {
		this.totalPaidTaxExcl = totalPaidTaxExcl;
	}

	@Column(name = "total_paid_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalPaidTaxIncl() {
		return this.totalPaidTaxIncl;
	}

	public void setTotalPaidTaxIncl(BigDecimal totalPaidTaxIncl) {
		this.totalPaidTaxIncl = totalPaidTaxIncl;
	}

	@Column(name = "total_products", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalProducts() {
		return this.totalProducts;
	}

	public void setTotalProducts(BigDecimal totalProducts) {
		this.totalProducts = totalProducts;
	}

	@Column(name = "total_products_wt", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalProductsWt() {
		return this.totalProductsWt;
	}

	public void setTotalProductsWt(BigDecimal totalProductsWt) {
		this.totalProductsWt = totalProductsWt;
	}

	@Column(name = "total_shipping_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalShippingTaxExcl() {
		return this.totalShippingTaxExcl;
	}

	public void setTotalShippingTaxExcl(BigDecimal totalShippingTaxExcl) {
		this.totalShippingTaxExcl = totalShippingTaxExcl;
	}

	@Column(name = "total_shipping_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalShippingTaxIncl() {
		return this.totalShippingTaxIncl;
	}

	public void setTotalShippingTaxIncl(BigDecimal totalShippingTaxIncl) {
		this.totalShippingTaxIncl = totalShippingTaxIncl;
	}

	@Column(name = "shipping_tax_computation_method", nullable = false)
	public int getShippingTaxComputationMethod() {
		return this.shippingTaxComputationMethod;
	}

	public void setShippingTaxComputationMethod(int shippingTaxComputationMethod) {
		this.shippingTaxComputationMethod = shippingTaxComputationMethod;
	}

	@Column(name = "total_wrapping_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalWrappingTaxExcl() {
		return this.totalWrappingTaxExcl;
	}

	public void setTotalWrappingTaxExcl(BigDecimal totalWrappingTaxExcl) {
		this.totalWrappingTaxExcl = totalWrappingTaxExcl;
	}

	@Column(name = "total_wrapping_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalWrappingTaxIncl() {
		return this.totalWrappingTaxIncl;
	}

	public void setTotalWrappingTaxIncl(BigDecimal totalWrappingTaxIncl) {
		this.totalWrappingTaxIncl = totalWrappingTaxIncl;
	}

	@Column(name = "shop_address", length = 65535)
	public String getShopAddress() {
		return this.shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	@Column(name = "invoice_address", length = 65535)
	public String getInvoiceAddress() {
		return this.invoiceAddress;
	}

	public void setInvoiceAddress(String invoiceAddress) {
		this.invoiceAddress = invoiceAddress;
	}

	@Column(name = "delivery_address", length = 65535)
	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Column(name = "slot_name", nullable = false, length = 20)
	public String getSlotName() {
		return this.slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}

	@Column(name = "id_delivery_boy", nullable = false)
	public int getIdDeliveryBoy() {
		return this.idDeliveryBoy;
	}

	public void setIdDeliveryBoy(int idDeliveryBoy) {
		this.idDeliveryBoy = idDeliveryBoy;
	}

	@Column(name = "order_comment", nullable = false)
	public String getOrderComment() {
		return this.orderComment;
	}

	public void setOrderComment(String orderComment) {
		this.orderComment = orderComment;
	}

}
