package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvOrderSlipDetailTaxId generated by hbm2java
 */
@Embeddable
public class NvOrderSlipDetailTaxId implements java.io.Serializable {

	private int idOrderSlipDetail;
	private int idTax;
	private BigDecimal unitAmount;
	private BigDecimal totalAmount;

	public NvOrderSlipDetailTaxId() {
	}

	public NvOrderSlipDetailTaxId(int idOrderSlipDetail, int idTax, BigDecimal unitAmount, BigDecimal totalAmount) {
		this.idOrderSlipDetail = idOrderSlipDetail;
		this.idTax = idTax;
		this.unitAmount = unitAmount;
		this.totalAmount = totalAmount;
	}

	@Column(name = "id_order_slip_detail", nullable = false)
	public int getIdOrderSlipDetail() {
		return this.idOrderSlipDetail;
	}

	public void setIdOrderSlipDetail(int idOrderSlipDetail) {
		this.idOrderSlipDetail = idOrderSlipDetail;
	}

	@Column(name = "id_tax", nullable = false)
	public int getIdTax() {
		return this.idTax;
	}

	public void setIdTax(int idTax) {
		this.idTax = idTax;
	}

	@Column(name = "unit_amount", nullable = false, precision = 16, scale = 6)
	public BigDecimal getUnitAmount() {
		return this.unitAmount;
	}

	public void setUnitAmount(BigDecimal unitAmount) {
		this.unitAmount = unitAmount;
	}

	@Column(name = "total_amount", nullable = false, precision = 16, scale = 6)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvOrderSlipDetailTaxId))
			return false;
		NvOrderSlipDetailTaxId castOther = (NvOrderSlipDetailTaxId) other;

		return (this.getIdOrderSlipDetail() == castOther.getIdOrderSlipDetail())
						&& (this.getIdTax() == castOther.getIdTax())
						&& ((this.getUnitAmount() == castOther.getUnitAmount()) || (this.getUnitAmount() != null && castOther.getUnitAmount() != null && this
										.getUnitAmount().equals(castOther.getUnitAmount())))
						&& ((this.getTotalAmount() == castOther.getTotalAmount()) || (this.getTotalAmount() != null && castOther.getTotalAmount() != null && this
										.getTotalAmount().equals(castOther.getTotalAmount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrderSlipDetail();
		result = 37 * result + this.getIdTax();
		result = 37 * result + (getUnitAmount() == null ? 0 : this.getUnitAmount().hashCode());
		result = 37 * result + (getTotalAmount() == null ? 0 : this.getTotalAmount().hashCode());
		return result;
	}

}
