package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderSlipDetail generated by hbm2java
 */
@Entity
@Table(name = "nv_order_slip_detail", catalog = "NVPrestashop")
public class NvOrderSlipDetail implements java.io.Serializable {

	private NvOrderSlipDetailId id;
	private int productQuantity;
	private BigDecimal unitPriceTaxExcl;
	private BigDecimal unitPriceTaxIncl;
	private BigDecimal totalPriceTaxExcl;
	private BigDecimal totalPriceTaxIncl;
	private BigDecimal amountTaxExcl;
	private BigDecimal amountTaxIncl;

	public NvOrderSlipDetail() {
	}

	public NvOrderSlipDetail(NvOrderSlipDetailId id, int productQuantity) {
		this.id = id;
		this.productQuantity = productQuantity;
	}

	public NvOrderSlipDetail(NvOrderSlipDetailId id, int productQuantity, BigDecimal unitPriceTaxExcl, BigDecimal unitPriceTaxIncl,
					BigDecimal totalPriceTaxExcl, BigDecimal totalPriceTaxIncl, BigDecimal amountTaxExcl, BigDecimal amountTaxIncl) {
		this.id = id;
		this.productQuantity = productQuantity;
		this.unitPriceTaxExcl = unitPriceTaxExcl;
		this.unitPriceTaxIncl = unitPriceTaxIncl;
		this.totalPriceTaxExcl = totalPriceTaxExcl;
		this.totalPriceTaxIncl = totalPriceTaxIncl;
		this.amountTaxExcl = amountTaxExcl;
		this.amountTaxIncl = amountTaxIncl;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderSlip", column = @Column(name = "id_order_slip", nullable = false)),
			@AttributeOverride(name = "idOrderDetail", column = @Column(name = "id_order_detail", nullable = false)) })
	public NvOrderSlipDetailId getId() {
		return this.id;
	}

	public void setId(NvOrderSlipDetailId id) {
		this.id = id;
	}

	@Column(name = "product_quantity", nullable = false)
	public int getProductQuantity() {
		return this.productQuantity;
	}

	public void setProductQuantity(int productQuantity) {
		this.productQuantity = productQuantity;
	}

	@Column(name = "unit_price_tax_excl", precision = 20, scale = 6)
	public BigDecimal getUnitPriceTaxExcl() {
		return this.unitPriceTaxExcl;
	}

	public void setUnitPriceTaxExcl(BigDecimal unitPriceTaxExcl) {
		this.unitPriceTaxExcl = unitPriceTaxExcl;
	}

	@Column(name = "unit_price_tax_incl", precision = 20, scale = 6)
	public BigDecimal getUnitPriceTaxIncl() {
		return this.unitPriceTaxIncl;
	}

	public void setUnitPriceTaxIncl(BigDecimal unitPriceTaxIncl) {
		this.unitPriceTaxIncl = unitPriceTaxIncl;
	}

	@Column(name = "total_price_tax_excl", precision = 20, scale = 6)
	public BigDecimal getTotalPriceTaxExcl() {
		return this.totalPriceTaxExcl;
	}

	public void setTotalPriceTaxExcl(BigDecimal totalPriceTaxExcl) {
		this.totalPriceTaxExcl = totalPriceTaxExcl;
	}

	@Column(name = "total_price_tax_incl", precision = 20, scale = 6)
	public BigDecimal getTotalPriceTaxIncl() {
		return this.totalPriceTaxIncl;
	}

	public void setTotalPriceTaxIncl(BigDecimal totalPriceTaxIncl) {
		this.totalPriceTaxIncl = totalPriceTaxIncl;
	}

	@Column(name = "amount_tax_excl", precision = 20, scale = 6)
	public BigDecimal getAmountTaxExcl() {
		return this.amountTaxExcl;
	}

	public void setAmountTaxExcl(BigDecimal amountTaxExcl) {
		this.amountTaxExcl = amountTaxExcl;
	}

	@Column(name = "amount_tax_incl", precision = 20, scale = 6)
	public BigDecimal getAmountTaxIncl() {
		return this.amountTaxIncl;
	}

	public void setAmountTaxIncl(BigDecimal amountTaxIncl) {
		this.amountTaxIncl = amountTaxIncl;
	}

}
