package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvOrderPayment generated by hbm2java
 */
@Entity
@Table(name = "nv_order_payment", catalog = "NVPrestashop")
public class NvOrderPayment implements java.io.Serializable {

	private Integer idOrderPayment;
	private String orderReference;
	private int idCurrency;
	private BigDecimal amount;
	private String paymentMethod;
	private BigDecimal conversionRate;
	private String transactionId;
	private String cardNumber;
	private String cardBrand;
	private String cardExpiration;
	private String cardHolder;
	private Date dateAdd;

	public NvOrderPayment() {
	}

	public NvOrderPayment(int idCurrency, BigDecimal amount, String paymentMethod, BigDecimal conversionRate, Date dateAdd) {
		this.idCurrency = idCurrency;
		this.amount = amount;
		this.paymentMethod = paymentMethod;
		this.conversionRate = conversionRate;
		this.dateAdd = dateAdd;
	}

	public NvOrderPayment(String orderReference, int idCurrency, BigDecimal amount, String paymentMethod, BigDecimal conversionRate, String transactionId,
					String cardNumber, String cardBrand, String cardExpiration, String cardHolder, Date dateAdd) {
		this.orderReference = orderReference;
		this.idCurrency = idCurrency;
		this.amount = amount;
		this.paymentMethod = paymentMethod;
		this.conversionRate = conversionRate;
		this.transactionId = transactionId;
		this.cardNumber = cardNumber;
		this.cardBrand = cardBrand;
		this.cardExpiration = cardExpiration;
		this.cardHolder = cardHolder;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_order_payment", unique = true, nullable = false)
	public Integer getIdOrderPayment() {
		return this.idOrderPayment;
	}

	public void setIdOrderPayment(Integer idOrderPayment) {
		this.idOrderPayment = idOrderPayment;
	}

	@Column(name = "order_reference", length = 9)
	public String getOrderReference() {
		return this.orderReference;
	}

	public void setOrderReference(String orderReference) {
		this.orderReference = orderReference;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "payment_method", nullable = false)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "conversion_rate", nullable = false, precision = 13, scale = 6)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Column(name = "transaction_id", length = 254)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "card_number", length = 254)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "card_brand", length = 254)
	public String getCardBrand() {
		return this.cardBrand;
	}

	public void setCardBrand(String cardBrand) {
		this.cardBrand = cardBrand;
	}

	@Column(name = "card_expiration", length = 7)
	public String getCardExpiration() {
		return this.cardExpiration;
	}

	public void setCardExpiration(String cardExpiration) {
		this.cardExpiration = cardExpiration;
	}

	@Column(name = "card_holder", length = 254)
	public String getCardHolder() {
		return this.cardHolder;
	}

	public void setCardHolder(String cardHolder) {
		this.cardHolder = cardHolder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
