package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderStateLang generated by hbm2java
 */
@Entity
@Table(name = "nv_order_state_lang", catalog = "NVPrestashop")
public class NvOrderStateLang implements java.io.Serializable {

	private static final long serialVersionUID = -7213954858872004594L;
	
	private NvOrderStateLangId id;
	private String name;
	private String template;

	public NvOrderStateLang() {
	}

	public NvOrderStateLang(NvOrderStateLangId id, String name, String template) {
		this.id = id;
		this.name = name;
		this.template = template;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderState", column = @Column(name = "id_order_state", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvOrderStateLangId getId() {
		return this.id;
	}

	public void setId(NvOrderStateLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "template", nullable = false, length = 64)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

}
