package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderInvoiceTax generated by hbm2java
 */
@Entity
@Table(name = "nv_order_invoice_tax", catalog = "NVPrestashop")
public class NvOrderInvoiceTax implements java.io.Serializable {

	private NvOrderInvoiceTaxId id;

	public NvOrderInvoiceTax() {
	}

	public NvOrderInvoiceTax(NvOrderInvoiceTaxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderInvoice", column = @Column(name = "id_order_invoice", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 15)),
			@AttributeOverride(name = "idTax", column = @Column(name = "id_tax", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 10, scale = 6)) })
	public NvOrderInvoiceTaxId getId() {
		return this.id;
	}

	public void setId(NvOrderInvoiceTaxId id) {
		this.id = id;
	}

}
