package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderReturnStateLang generated by hbm2java
 */
@Entity
@Table(name = "nv_order_return_state_lang", catalog = "NVPrestashop")
public class NvOrderReturnStateLang implements java.io.Serializable {

	private NvOrderReturnStateLangId id;
	private String name;

	public NvOrderReturnStateLang() {
	}

	public NvOrderReturnStateLang(NvOrderReturnStateLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderReturnState", column = @Column(name = "id_order_return_state", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvOrderReturnStateLangId getId() {
		return this.id;
	}

	public void setId(NvOrderReturnStateLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
