package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderDetailTax generated by hbm2java
 */
@Entity
@Table(name = "nv_order_detail_tax", catalog = "NVPrestashop")
public class NvOrderDetailTax implements java.io.Serializable {

	private NvOrderDetailTaxId id;

	public NvOrderDetailTax() {
	}

	public NvOrderDetailTax(NvOrderDetailTaxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderDetail", column = @Column(name = "id_order_detail", nullable = false)),
			@AttributeOverride(name = "idTax", column = @Column(name = "id_tax", nullable = false)),
			@AttributeOverride(name = "unitAmount", column = @Column(name = "unit_amount", nullable = false, precision = 16, scale = 6)),
			@AttributeOverride(name = "totalAmount", column = @Column(name = "total_amount", nullable = false, precision = 16, scale = 6)) })
	public NvOrderDetailTaxId getId() {
		return this.id;
	}

	public void setId(NvOrderDetailTaxId id) {
		this.id = id;
	}

}
