package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "nv_order_detail", catalog = "NVPrestashop")
public class NvOrderDetail implements java.io.Serializable {

	private Integer idOrderDetail;
	private int idOrder;
	private Integer idOrderInvoice;
	private Integer idWarehouse;
	private int idShop;
	private int productId;
	private Integer productAttributeId;
	private String productName;
	private int productQuantity;
	private int productQuantityInStock;
	private int productQuantityRefunded;
	private int productQuantityReturn;
	private int productQuantityReinjected;
	private BigDecimal productPrice;
	private BigDecimal reductionPercent;
	private BigDecimal reductionAmount;
	private BigDecimal reductionAmountTaxIncl;
	private BigDecimal reductionAmountTaxExcl;
	private BigDecimal groupReduction;
	private BigDecimal productQuantityDiscount;
	private String productEan13;
	private String productUpc;
	private String productReference;
	private String productSupplierReference;
	private BigDecimal productWeight;
	private Integer idTaxRulesGroup;
	private boolean taxComputationMethod;
	private String taxName;
	private BigDecimal taxRate;
	private BigDecimal ecotax;
	private BigDecimal ecotaxTaxRate;
	private boolean discountQuantityApplied;
	private String downloadHash;
	private Integer downloadNb;
	private Date downloadDeadline;
	private BigDecimal totalPriceTaxIncl;
	private BigDecimal totalPriceTaxExcl;
	private BigDecimal unitPriceTaxIncl;
	private BigDecimal unitPriceTaxExcl;
	private BigDecimal totalShippingPriceTaxIncl;
	private BigDecimal totalShippingPriceTaxExcl;
	private BigDecimal purchaseSupplierPrice;
	private BigDecimal originalProductPrice;
	private BigDecimal originalWholesalePrice;

	public NvOrderDetail() {
	}

	public NvOrderDetail(int idOrder, int idShop, int productId, String productName, int productQuantity, int productQuantityInStock,
					int productQuantityRefunded, int productQuantityReturn, int productQuantityReinjected, BigDecimal productPrice,
					BigDecimal reductionPercent, BigDecimal reductionAmount, BigDecimal reductionAmountTaxIncl, BigDecimal reductionAmountTaxExcl,
					BigDecimal groupReduction, BigDecimal productQuantityDiscount, BigDecimal productWeight, boolean taxComputationMethod, String taxName,
					BigDecimal taxRate, BigDecimal ecotax, BigDecimal ecotaxTaxRate, boolean discountQuantityApplied, BigDecimal totalPriceTaxIncl,
					BigDecimal totalPriceTaxExcl, BigDecimal unitPriceTaxIncl, BigDecimal unitPriceTaxExcl, BigDecimal totalShippingPriceTaxIncl,
					BigDecimal totalShippingPriceTaxExcl, BigDecimal purchaseSupplierPrice, BigDecimal originalProductPrice, BigDecimal originalWholesalePrice) {
		this.idOrder = idOrder;
		this.idShop = idShop;
		this.productId = productId;
		this.productName = productName;
		this.productQuantity = productQuantity;
		this.productQuantityInStock = productQuantityInStock;
		this.productQuantityRefunded = productQuantityRefunded;
		this.productQuantityReturn = productQuantityReturn;
		this.productQuantityReinjected = productQuantityReinjected;
		this.productPrice = productPrice;
		this.reductionPercent = reductionPercent;
		this.reductionAmount = reductionAmount;
		this.reductionAmountTaxIncl = reductionAmountTaxIncl;
		this.reductionAmountTaxExcl = reductionAmountTaxExcl;
		this.groupReduction = groupReduction;
		this.productQuantityDiscount = productQuantityDiscount;
		this.productWeight = productWeight;
		this.taxComputationMethod = taxComputationMethod;
		this.taxName = taxName;
		this.taxRate = taxRate;
		this.ecotax = ecotax;
		this.ecotaxTaxRate = ecotaxTaxRate;
		this.discountQuantityApplied = discountQuantityApplied;
		this.totalPriceTaxIncl = totalPriceTaxIncl;
		this.totalPriceTaxExcl = totalPriceTaxExcl;
		this.unitPriceTaxIncl = unitPriceTaxIncl;
		this.unitPriceTaxExcl = unitPriceTaxExcl;
		this.totalShippingPriceTaxIncl = totalShippingPriceTaxIncl;
		this.totalShippingPriceTaxExcl = totalShippingPriceTaxExcl;
		this.purchaseSupplierPrice = purchaseSupplierPrice;
		this.originalProductPrice = originalProductPrice;
		this.originalWholesalePrice = originalWholesalePrice;
	}

	public NvOrderDetail(int idOrder, Integer idOrderInvoice, Integer idWarehouse, int idShop, int productId, Integer productAttributeId, String productName,
					int productQuantity, int productQuantityInStock, int productQuantityRefunded, int productQuantityReturn, int productQuantityReinjected,
					BigDecimal productPrice, BigDecimal reductionPercent, BigDecimal reductionAmount, BigDecimal reductionAmountTaxIncl,
					BigDecimal reductionAmountTaxExcl, BigDecimal groupReduction, BigDecimal productQuantityDiscount, String productEan13, String productUpc,
					String productReference, String productSupplierReference, BigDecimal productWeight, Integer idTaxRulesGroup, boolean taxComputationMethod,
					String taxName, BigDecimal taxRate, BigDecimal ecotax, BigDecimal ecotaxTaxRate, boolean discountQuantityApplied, String downloadHash,
					Integer downloadNb, Date downloadDeadline, BigDecimal totalPriceTaxIncl, BigDecimal totalPriceTaxExcl, BigDecimal unitPriceTaxIncl,
					BigDecimal unitPriceTaxExcl, BigDecimal totalShippingPriceTaxIncl, BigDecimal totalShippingPriceTaxExcl, BigDecimal purchaseSupplierPrice,
					BigDecimal originalProductPrice, BigDecimal originalWholesalePrice) {
		this.idOrder = idOrder;
		this.idOrderInvoice = idOrderInvoice;
		this.idWarehouse = idWarehouse;
		this.idShop = idShop;
		this.productId = productId;
		this.productAttributeId = productAttributeId;
		this.productName = productName;
		this.productQuantity = productQuantity;
		this.productQuantityInStock = productQuantityInStock;
		this.productQuantityRefunded = productQuantityRefunded;
		this.productQuantityReturn = productQuantityReturn;
		this.productQuantityReinjected = productQuantityReinjected;
		this.productPrice = productPrice;
		this.reductionPercent = reductionPercent;
		this.reductionAmount = reductionAmount;
		this.reductionAmountTaxIncl = reductionAmountTaxIncl;
		this.reductionAmountTaxExcl = reductionAmountTaxExcl;
		this.groupReduction = groupReduction;
		this.productQuantityDiscount = productQuantityDiscount;
		this.productEan13 = productEan13;
		this.productUpc = productUpc;
		this.productReference = productReference;
		this.productSupplierReference = productSupplierReference;
		this.productWeight = productWeight;
		this.idTaxRulesGroup = idTaxRulesGroup;
		this.taxComputationMethod = taxComputationMethod;
		this.taxName = taxName;
		this.taxRate = taxRate;
		this.ecotax = ecotax;
		this.ecotaxTaxRate = ecotaxTaxRate;
		this.discountQuantityApplied = discountQuantityApplied;
		this.downloadHash = downloadHash;
		this.downloadNb = downloadNb;
		this.downloadDeadline = downloadDeadline;
		this.totalPriceTaxIncl = totalPriceTaxIncl;
		this.totalPriceTaxExcl = totalPriceTaxExcl;
		this.unitPriceTaxIncl = unitPriceTaxIncl;
		this.unitPriceTaxExcl = unitPriceTaxExcl;
		this.totalShippingPriceTaxIncl = totalShippingPriceTaxIncl;
		this.totalShippingPriceTaxExcl = totalShippingPriceTaxExcl;
		this.purchaseSupplierPrice = purchaseSupplierPrice;
		this.originalProductPrice = originalProductPrice;
		this.originalWholesalePrice = originalWholesalePrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_order_detail", unique = true, nullable = false)
	public Integer getIdOrderDetail() {
		return this.idOrderDetail;
	}

	public void setIdOrderDetail(Integer idOrderDetail) {
		this.idOrderDetail = idOrderDetail;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "id_order_invoice")
	public Integer getIdOrderInvoice() {
		return this.idOrderInvoice;
	}

	public void setIdOrderInvoice(Integer idOrderInvoice) {
		this.idOrderInvoice = idOrderInvoice;
	}

	@Column(name = "id_warehouse")
	public Integer getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(Integer idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "product_attribute_id")
	public Integer getProductAttributeId() {
		return this.productAttributeId;
	}

	public void setProductAttributeId(Integer productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	@Column(name = "product_name", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_quantity", nullable = false)
	public int getProductQuantity() {
		return this.productQuantity;
	}

	public void setProductQuantity(int productQuantity) {
		this.productQuantity = productQuantity;
	}

	@Column(name = "product_quantity_in_stock", nullable = false)
	public int getProductQuantityInStock() {
		return this.productQuantityInStock;
	}

	public void setProductQuantityInStock(int productQuantityInStock) {
		this.productQuantityInStock = productQuantityInStock;
	}

	@Column(name = "product_quantity_refunded", nullable = false)
	public int getProductQuantityRefunded() {
		return this.productQuantityRefunded;
	}

	public void setProductQuantityRefunded(int productQuantityRefunded) {
		this.productQuantityRefunded = productQuantityRefunded;
	}

	@Column(name = "product_quantity_return", nullable = false)
	public int getProductQuantityReturn() {
		return this.productQuantityReturn;
	}

	public void setProductQuantityReturn(int productQuantityReturn) {
		this.productQuantityReturn = productQuantityReturn;
	}

	@Column(name = "product_quantity_reinjected", nullable = false)
	public int getProductQuantityReinjected() {
		return this.productQuantityReinjected;
	}

	public void setProductQuantityReinjected(int productQuantityReinjected) {
		this.productQuantityReinjected = productQuantityReinjected;
	}

	@Column(name = "product_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "reduction_percent", nullable = false, precision = 10)
	public BigDecimal getReductionPercent() {
		return this.reductionPercent;
	}

	public void setReductionPercent(BigDecimal reductionPercent) {
		this.reductionPercent = reductionPercent;
	}

	@Column(name = "reduction_amount", nullable = false, precision = 20, scale = 6)
	public BigDecimal getReductionAmount() {
		return this.reductionAmount;
	}

	public void setReductionAmount(BigDecimal reductionAmount) {
		this.reductionAmount = reductionAmount;
	}

	@Column(name = "reduction_amount_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getReductionAmountTaxIncl() {
		return this.reductionAmountTaxIncl;
	}

	public void setReductionAmountTaxIncl(BigDecimal reductionAmountTaxIncl) {
		this.reductionAmountTaxIncl = reductionAmountTaxIncl;
	}

	@Column(name = "reduction_amount_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getReductionAmountTaxExcl() {
		return this.reductionAmountTaxExcl;
	}

	public void setReductionAmountTaxExcl(BigDecimal reductionAmountTaxExcl) {
		this.reductionAmountTaxExcl = reductionAmountTaxExcl;
	}

	@Column(name = "group_reduction", nullable = false, precision = 10)
	public BigDecimal getGroupReduction() {
		return this.groupReduction;
	}

	public void setGroupReduction(BigDecimal groupReduction) {
		this.groupReduction = groupReduction;
	}

	@Column(name = "product_quantity_discount", nullable = false, precision = 20, scale = 6)
	public BigDecimal getProductQuantityDiscount() {
		return this.productQuantityDiscount;
	}

	public void setProductQuantityDiscount(BigDecimal productQuantityDiscount) {
		this.productQuantityDiscount = productQuantityDiscount;
	}

	@Column(name = "product_ean13", length = 13)
	public String getProductEan13() {
		return this.productEan13;
	}

	public void setProductEan13(String productEan13) {
		this.productEan13 = productEan13;
	}

	@Column(name = "product_upc", length = 12)
	public String getProductUpc() {
		return this.productUpc;
	}

	public void setProductUpc(String productUpc) {
		this.productUpc = productUpc;
	}

	@Column(name = "product_reference", length = 32)
	public String getProductReference() {
		return this.productReference;
	}

	public void setProductReference(String productReference) {
		this.productReference = productReference;
	}

	@Column(name = "product_supplier_reference", length = 32)
	public String getProductSupplierReference() {
		return this.productSupplierReference;
	}

	public void setProductSupplierReference(String productSupplierReference) {
		this.productSupplierReference = productSupplierReference;
	}

	@Column(name = "product_weight", nullable = false, precision = 20, scale = 6)
	public BigDecimal getProductWeight() {
		return this.productWeight;
	}

	public void setProductWeight(BigDecimal productWeight) {
		this.productWeight = productWeight;
	}

	@Column(name = "id_tax_rules_group")
	public Integer getIdTaxRulesGroup() {
		return this.idTaxRulesGroup;
	}

	public void setIdTaxRulesGroup(Integer idTaxRulesGroup) {
		this.idTaxRulesGroup = idTaxRulesGroup;
	}

	@Column(name = "tax_computation_method", nullable = false)
	public boolean isTaxComputationMethod() {
		return this.taxComputationMethod;
	}

	public void setTaxComputationMethod(boolean taxComputationMethod) {
		this.taxComputationMethod = taxComputationMethod;
	}

	@Column(name = "tax_name", nullable = false, length = 16)
	public String getTaxName() {
		return this.taxName;
	}

	public void setTaxName(String taxName) {
		this.taxName = taxName;
	}

	@Column(name = "tax_rate", nullable = false, precision = 10, scale = 3)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "ecotax", nullable = false, precision = 21, scale = 6)
	public BigDecimal getEcotax() {
		return this.ecotax;
	}

	public void setEcotax(BigDecimal ecotax) {
		this.ecotax = ecotax;
	}

	@Column(name = "ecotax_tax_rate", nullable = false, precision = 5, scale = 3)
	public BigDecimal getEcotaxTaxRate() {
		return this.ecotaxTaxRate;
	}

	public void setEcotaxTaxRate(BigDecimal ecotaxTaxRate) {
		this.ecotaxTaxRate = ecotaxTaxRate;
	}

	@Column(name = "discount_quantity_applied", nullable = false)
	public boolean isDiscountQuantityApplied() {
		return this.discountQuantityApplied;
	}

	public void setDiscountQuantityApplied(boolean discountQuantityApplied) {
		this.discountQuantityApplied = discountQuantityApplied;
	}

	@Column(name = "download_hash")
	public String getDownloadHash() {
		return this.downloadHash;
	}

	public void setDownloadHash(String downloadHash) {
		this.downloadHash = downloadHash;
	}

	@Column(name = "download_nb")
	public Integer getDownloadNb() {
		return this.downloadNb;
	}

	public void setDownloadNb(Integer downloadNb) {
		this.downloadNb = downloadNb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "download_deadline", length = 0)
	public Date getDownloadDeadline() {
		return this.downloadDeadline;
	}

	public void setDownloadDeadline(Date downloadDeadline) {
		this.downloadDeadline = downloadDeadline;
	}

	@Column(name = "total_price_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalPriceTaxIncl() {
		return this.totalPriceTaxIncl;
	}

	public void setTotalPriceTaxIncl(BigDecimal totalPriceTaxIncl) {
		this.totalPriceTaxIncl = totalPriceTaxIncl;
	}

	@Column(name = "total_price_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalPriceTaxExcl() {
		return this.totalPriceTaxExcl;
	}

	public void setTotalPriceTaxExcl(BigDecimal totalPriceTaxExcl) {
		this.totalPriceTaxExcl = totalPriceTaxExcl;
	}

	@Column(name = "unit_price_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getUnitPriceTaxIncl() {
		return this.unitPriceTaxIncl;
	}

	public void setUnitPriceTaxIncl(BigDecimal unitPriceTaxIncl) {
		this.unitPriceTaxIncl = unitPriceTaxIncl;
	}

	@Column(name = "unit_price_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getUnitPriceTaxExcl() {
		return this.unitPriceTaxExcl;
	}

	public void setUnitPriceTaxExcl(BigDecimal unitPriceTaxExcl) {
		this.unitPriceTaxExcl = unitPriceTaxExcl;
	}

	@Column(name = "total_shipping_price_tax_incl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalShippingPriceTaxIncl() {
		return this.totalShippingPriceTaxIncl;
	}

	public void setTotalShippingPriceTaxIncl(BigDecimal totalShippingPriceTaxIncl) {
		this.totalShippingPriceTaxIncl = totalShippingPriceTaxIncl;
	}

	@Column(name = "total_shipping_price_tax_excl", nullable = false, precision = 20, scale = 6)
	public BigDecimal getTotalShippingPriceTaxExcl() {
		return this.totalShippingPriceTaxExcl;
	}

	public void setTotalShippingPriceTaxExcl(BigDecimal totalShippingPriceTaxExcl) {
		this.totalShippingPriceTaxExcl = totalShippingPriceTaxExcl;
	}

	@Column(name = "purchase_supplier_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getPurchaseSupplierPrice() {
		return this.purchaseSupplierPrice;
	}

	public void setPurchaseSupplierPrice(BigDecimal purchaseSupplierPrice) {
		this.purchaseSupplierPrice = purchaseSupplierPrice;
	}

	@Column(name = "original_product_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getOriginalProductPrice() {
		return this.originalProductPrice;
	}

	public void setOriginalProductPrice(BigDecimal originalProductPrice) {
		this.originalProductPrice = originalProductPrice;
	}

	@Column(name = "original_wholesale_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getOriginalWholesalePrice() {
		return this.originalWholesalePrice;
	}

	public void setOriginalWholesalePrice(BigDecimal originalWholesalePrice) {
		this.originalWholesalePrice = originalWholesalePrice;
	}

}
