package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvOrderInvoicePaymentId generated by hbm2java
 */
@Embeddable
public class NvOrderInvoicePaymentId implements java.io.Serializable {

	private int idOrderInvoice;
	private int idOrderPayment;

	public NvOrderInvoicePaymentId() {
	}

	public NvOrderInvoicePaymentId(int idOrderInvoice, int idOrderPayment) {
		this.idOrderInvoice = idOrderInvoice;
		this.idOrderPayment = idOrderPayment;
	}

	@Column(name = "id_order_invoice", nullable = false)
	public int getIdOrderInvoice() {
		return this.idOrderInvoice;
	}

	public void setIdOrderInvoice(int idOrderInvoice) {
		this.idOrderInvoice = idOrderInvoice;
	}

	@Column(name = "id_order_payment", nullable = false)
	public int getIdOrderPayment() {
		return this.idOrderPayment;
	}

	public void setIdOrderPayment(int idOrderPayment) {
		this.idOrderPayment = idOrderPayment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvOrderInvoicePaymentId))
			return false;
		NvOrderInvoicePaymentId castOther = (NvOrderInvoicePaymentId) other;

		return (this.getIdOrderInvoice() == castOther.getIdOrderInvoice()) && (this.getIdOrderPayment() == castOther.getIdOrderPayment());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrderInvoice();
		result = 37 * result + this.getIdOrderPayment();
		return result;
	}

}
