package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderMessageLang generated by hbm2java
 */
@Entity
@Table(name = "nv_order_message_lang", catalog = "NVPrestashop")
public class NvOrderMessageLang implements java.io.Serializable {

	private NvOrderMessageLangId id;
	private String name;
	private String message;

	public NvOrderMessageLang() {
	}

	public NvOrderMessageLang(NvOrderMessageLangId id, String name, String message) {
		this.id = id;
		this.name = name;
		this.message = message;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderMessage", column = @Column(name = "id_order_message", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvOrderMessageLangId getId() {
		return this.id;
	}

	public void setId(NvOrderMessageLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
