package com.nonveggies.entity.order;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvOrderInvoicePayment generated by hbm2java
 */
@Entity
@Table(name = "nv_order_invoice_payment", catalog = "NVPrestashop")
public class NvOrderInvoicePayment implements java.io.Serializable {

	private NvOrderInvoicePaymentId id;
	private int idOrder;

	public NvOrderInvoicePayment() {
	}

	public NvOrderInvoicePayment(NvOrderInvoicePaymentId id, int idOrder) {
		this.id = id;
		this.idOrder = idOrder;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idOrderInvoice", column = @Column(name = "id_order_invoice", nullable = false)),
			@AttributeOverride(name = "idOrderPayment", column = @Column(name = "id_order_payment", nullable = false)) })
	public NvOrderInvoicePaymentId getId() {
		return this.id;
	}

	public void setId(NvOrderInvoicePaymentId id) {
		this.id = id;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

}
