package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvAccessoryId generated by hbm2java
 */
@Embeddable
public class NvAccessoryId implements java.io.Serializable {

	private int idProduct1;
	private int idProduct2;

	public NvAccessoryId() {
	}

	public NvAccessoryId(int idProduct1, int idProduct2) {
		this.idProduct1 = idProduct1;
		this.idProduct2 = idProduct2;
	}

	@Column(name = "id_product_1", nullable = false)
	public int getIdProduct1() {
		return this.idProduct1;
	}

	public void setIdProduct1(int idProduct1) {
		this.idProduct1 = idProduct1;
	}

	@Column(name = "id_product_2", nullable = false)
	public int getIdProduct2() {
		return this.idProduct2;
	}

	public void setIdProduct2(int idProduct2) {
		this.idProduct2 = idProduct2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvAccessoryId))
			return false;
		NvAccessoryId castOther = (NvAccessoryId) other;

		return (this.getIdProduct1() == castOther.getIdProduct1()) && (this.getIdProduct2() == castOther.getIdProduct2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct1();
		result = 37 * result + this.getIdProduct2();
		return result;
	}

}
