package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvAccess generated by hbm2java
 */
@Entity
@Table(name = "nv_access", catalog = "NVPrestashop")
public class NvAccess implements java.io.Serializable {

	private NvAccessId id;
	private int view;
	private int add;
	private int edit;
	private int delete;

	public NvAccess() {
	}

	public NvAccess(NvAccessId id, int view, int add, int edit, int delete) {
		this.id = id;
		this.view = view;
		this.add = add;
		this.edit = edit;
		this.delete = delete;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProfile", column = @Column(name = "id_profile", nullable = false)),
			@AttributeOverride(name = "idTab", column = @Column(name = "id_tab", nullable = false)) })
	public NvAccessId getId() {
		return this.id;
	}

	public void setId(NvAccessId id) {
		this.id = id;
	}

	@Column(name = "view", nullable = false)
	public int getView() {
		return this.view;
	}

	public void setView(int view) {
		this.view = view;
	}

	@Column(name = "add", nullable = false)
	public int getAdd() {
		return this.add;
	}

	public void setAdd(int add) {
		this.add = add;
	}

	@Column(name = "edit", nullable = false)
	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	@Column(name = "delete", nullable = false)
	public int getDelete() {
		return this.delete;
	}

	public void setDelete(int delete) {
		this.delete = delete;
	}

}
