package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvAccessory generated by hbm2java
 */
@Entity
@Table(name = "nv_accessory", catalog = "NVPrestashop")
public class NvAccessory implements java.io.Serializable {

	private NvAccessoryId id;

	public NvAccessory() {
	}

	public NvAccessory(NvAccessoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct1", column = @Column(name = "id_product_1", nullable = false)),
			@AttributeOverride(name = "idProduct2", column = @Column(name = "id_product_2", nullable = false)) })
	public NvAccessoryId getId() {
		return this.id;
	}

	public void setId(NvAccessoryId id) {
		this.id = id;
	}

}
