package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvAdvice generated by hbm2java
 */
@Entity
@Table(name = "nv_advice", catalog = "NVPrestashop")
public class NvAdvice implements java.io.Serializable {

	private Integer idAdvice;
	private int idPsAdvice;
	private int idTab;
	private String idsTab;
	private boolean validated;
	private boolean hide;
	private String location;
	private String selector;
	private int startDay;
	private int stopDay;
	private Integer weight;

	public NvAdvice() {
	}

	public NvAdvice(int idPsAdvice, int idTab, boolean validated, boolean hide, String location, int startDay, int stopDay) {
		this.idPsAdvice = idPsAdvice;
		this.idTab = idTab;
		this.validated = validated;
		this.hide = hide;
		this.location = location;
		this.startDay = startDay;
		this.stopDay = stopDay;
	}

	public NvAdvice(int idPsAdvice, int idTab, String idsTab, boolean validated, boolean hide, String location, String selector, int startDay, int stopDay,
					Integer weight) {
		this.idPsAdvice = idPsAdvice;
		this.idTab = idTab;
		this.idsTab = idsTab;
		this.validated = validated;
		this.hide = hide;
		this.location = location;
		this.selector = selector;
		this.startDay = startDay;
		this.stopDay = stopDay;
		this.weight = weight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_advice", unique = true, nullable = false)
	public Integer getIdAdvice() {
		return this.idAdvice;
	}

	public void setIdAdvice(Integer idAdvice) {
		this.idAdvice = idAdvice;
	}

	@Column(name = "id_ps_advice", nullable = false)
	public int getIdPsAdvice() {
		return this.idPsAdvice;
	}

	public void setIdPsAdvice(int idPsAdvice) {
		this.idPsAdvice = idPsAdvice;
	}

	@Column(name = "id_tab", nullable = false)
	public int getIdTab() {
		return this.idTab;
	}

	public void setIdTab(int idTab) {
		this.idTab = idTab;
	}

	@Column(name = "ids_tab", length = 65535)
	public String getIdsTab() {
		return this.idsTab;
	}

	public void setIdsTab(String idsTab) {
		this.idsTab = idsTab;
	}

	@Column(name = "validated", nullable = false)
	public boolean isValidated() {
		return this.validated;
	}

	public void setValidated(boolean validated) {
		this.validated = validated;
	}

	@Column(name = "hide", nullable = false)
	public boolean isHide() {
		return this.hide;
	}

	public void setHide(boolean hide) {
		this.hide = hide;
	}

	@Column(name = "location", nullable = false, length = 6)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "selector")
	public String getSelector() {
		return this.selector;
	}

	public void setSelector(String selector) {
		this.selector = selector;
	}

	@Column(name = "start_day", nullable = false)
	public int getStartDay() {
		return this.startDay;
	}

	public void setStartDay(int startDay) {
		this.startDay = startDay;
	}

	@Column(name = "stop_day", nullable = false)
	public int getStopDay() {
		return this.stopDay;
	}

	public void setStopDay(int stopDay) {
		this.stopDay = stopDay;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

}
