package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvAddress generated by hbm2java
 */
@Entity
@Table(name = "nv_address", catalog = "NVPrestashop")
public class NvAddress implements java.io.Serializable {

	private Integer idAddress;
	private int idCountry;
	private Integer idState;
	private int idCustomer;
	private int idManufacturer;
	private int idSupplier;
	private int idWarehouse;
	private String alias;
	private String company;
	private String lastname;
	private String firstname;
	private String address1;
	private String address2;
	private String postcode;
	private String city;
	private String other;
	private String phone;
	private String phoneMobile;
	private String vatNumber;
	private String dni;
	private Date dateAdd;
	private Date dateUpd;
	private boolean active;
	private boolean deleted;

	public NvAddress() {
	}

	public NvAddress(int idCountry, int idCustomer, int idManufacturer, int idSupplier, int idWarehouse, String alias, String lastname, String firstname,
					String address1, String city, Date dateAdd, Date dateUpd, boolean active, boolean deleted) {
		this.idCountry = idCountry;
		this.idCustomer = idCustomer;
		this.idManufacturer = idManufacturer;
		this.idSupplier = idSupplier;
		this.idWarehouse = idWarehouse;
		this.alias = alias;
		this.lastname = lastname;
		this.firstname = firstname;
		this.address1 = address1;
		this.city = city;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.active = active;
		this.deleted = deleted;
	}

	public NvAddress(int idCountry, Integer idState, int idCustomer, int idManufacturer, int idSupplier, int idWarehouse, String alias, String company,
					String lastname, String firstname, String address1, String address2, String postcode, String city, String other, String phone,
					String phoneMobile, String vatNumber, String dni, Date dateAdd, Date dateUpd, boolean active, boolean deleted) {
		this.idCountry = idCountry;
		this.idState = idState;
		this.idCustomer = idCustomer;
		this.idManufacturer = idManufacturer;
		this.idSupplier = idSupplier;
		this.idWarehouse = idWarehouse;
		this.alias = alias;
		this.company = company;
		this.lastname = lastname;
		this.firstname = firstname;
		this.address1 = address1;
		this.address2 = address2;
		this.postcode = postcode;
		this.city = city;
		this.other = other;
		this.phone = phone;
		this.phoneMobile = phoneMobile;
		this.vatNumber = vatNumber;
		this.dni = dni;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.active = active;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_address", unique = true, nullable = false)
	public Integer getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(Integer idAddress) {
		this.idAddress = idAddress;
	}

	@Column(name = "id_country", nullable = false)
	public int getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(int idCountry) {
		this.idCountry = idCountry;
	}

	@Column(name = "id_state")
	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_manufacturer", nullable = false)
	public int getIdManufacturer() {
		return this.idManufacturer;
	}

	public void setIdManufacturer(int idManufacturer) {
		this.idManufacturer = idManufacturer;
	}

	@Column(name = "id_supplier", nullable = false)
	public int getIdSupplier() {
		return this.idSupplier;
	}

	public void setIdSupplier(int idSupplier) {
		this.idSupplier = idSupplier;
	}

	@Column(name = "id_warehouse", nullable = false)
	public int getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(int idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "alias", nullable = false, length = 32)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "company", length = 64)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "lastname", nullable = false, length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "firstname", nullable = false, length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "address1", nullable = false, length = 128)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 128)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "postcode", length = 12)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "city", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "other", length = 65535)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "phone", length = 32)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "phone_mobile", length = 32)
	public String getPhoneMobile() {
		return this.phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	@Column(name = "vat_number", length = 32)
	public String getVatNumber() {
		return this.vatNumber;
	}

	public void setVatNumber(String vatNumber) {
		this.vatNumber = vatNumber;
	}

	@Column(name = "dni", length = 16)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
