package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvAlias generated by hbm2java
 */
@Entity
@Table(name = "nv_alias", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "alias"))
public class NvAlias implements java.io.Serializable {

	private Integer idAlias;
	private String alias;
	private String search;
	private boolean active;

	public NvAlias() {
	}

	public NvAlias(String alias, String search, boolean active) {
		this.alias = alias;
		this.search = search;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alias", unique = true, nullable = false)
	public Integer getIdAlias() {
		return this.idAlias;
	}

	public void setIdAlias(Integer idAlias) {
		this.idAlias = idAlias;
	}

	@Column(name = "alias", unique = true, nullable = false)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "search", nullable = false)
	public String getSearch() {
		return this.search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
