package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvAreaSlot generated by hbm2java
 */
@Entity
@Table(name = "nv_area_slot", catalog = "NVPrestashop")
public class NvAreaSlot implements java.io.Serializable {

	private NvAreaSlotId id;
	private Boolean active;
	private Date dateAdd;
	private Date dateUpd;

	public NvAreaSlot() {
	}

	public NvAreaSlot(NvAreaSlotId id) {
		this.id = id;
	}

	public NvAreaSlot(NvAreaSlotId id, Boolean active, Date dateAdd, Date dateUpd) {
		this.id = id;
		this.active = active;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idArea", column = @Column(name = "id_area", nullable = false)),
			@AttributeOverride(name = "idSlot", column = @Column(name = "id_slot", nullable = false)) })
	public NvAreaSlotId getId() {
		return this.id;
	}

	public void setId(NvAreaSlotId id) {
		this.id = id;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
