package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvAttributeLang generated by hbm2java
 */
@Entity
@Table(name = "nv_attribute_lang", catalog = "NVPrestashop")
public class NvAttributeLang implements java.io.Serializable {

	private NvAttributeLangId id;
	private String name;

	public NvAttributeLang() {
	}

	public NvAttributeLang(NvAttributeLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttribute", column = @Column(name = "id_attribute", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvAttributeLangId getId() {
		return this.id;
	}

	public void setId(NvAttributeLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
