package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvAttributeGroupShopId generated by hbm2java
 */
@Embeddable
public class NvAttributeGroupShopId implements java.io.Serializable {

	private int idAttributeGroup;
	private int idShop;

	public NvAttributeGroupShopId() {
	}

	public NvAttributeGroupShopId(int idAttributeGroup, int idShop) {
		this.idAttributeGroup = idAttributeGroup;
		this.idShop = idShop;
	}

	@Column(name = "id_attribute_group", nullable = false)
	public int getIdAttributeGroup() {
		return this.idAttributeGroup;
	}

	public void setIdAttributeGroup(int idAttributeGroup) {
		this.idAttributeGroup = idAttributeGroup;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvAttributeGroupShopId))
			return false;
		NvAttributeGroupShopId castOther = (NvAttributeGroupShopId) other;

		return (this.getIdAttributeGroup() == castOther.getIdAttributeGroup()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttributeGroup();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
