package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvAttachmentLangId generated by hbm2java
 */
@Embeddable
public class NvAttachmentLangId implements java.io.Serializable {

	private int idAttachment;
	private int idLang;

	public NvAttachmentLangId() {
	}

	public NvAttachmentLangId(int idAttachment, int idLang) {
		this.idAttachment = idAttachment;
		this.idLang = idLang;
	}

	@Column(name = "id_attachment", nullable = false)
	public int getIdAttachment() {
		return this.idAttachment;
	}

	public void setIdAttachment(int idAttachment) {
		this.idAttachment = idAttachment;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvAttachmentLangId))
			return false;
		NvAttachmentLangId castOther = (NvAttachmentLangId) other;

		return (this.getIdAttachment() == castOther.getIdAttachment()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttachment();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
