package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvAttributeShopId generated by hbm2java
 */
@Embeddable
public class NvAttributeShopId implements java.io.Serializable {

	private int idAttribute;
	private int idShop;

	public NvAttributeShopId() {
	}

	public NvAttributeShopId(int idAttribute, int idShop) {
		this.idAttribute = idAttribute;
		this.idShop = idShop;
	}

	@Column(name = "id_attribute", nullable = false)
	public int getIdAttribute() {
		return this.idAttribute;
	}

	public void setIdAttribute(int idAttribute) {
		this.idAttribute = idAttribute;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvAttributeShopId))
			return false;
		NvAttributeShopId castOther = (NvAttributeShopId) other;

		return (this.getIdAttribute() == castOther.getIdAttribute()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttribute();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
