package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvAttribute generated by hbm2java
 */
@Entity
@Table(name = "nv_attribute", catalog = "NVPrestashop")
public class NvAttribute implements java.io.Serializable {

	private Integer idAttribute;
	private int idAttributeGroup;
	private String color;
	private int position;

	public NvAttribute() {
	}

	public NvAttribute(int idAttributeGroup, int position) {
		this.idAttributeGroup = idAttributeGroup;
		this.position = position;
	}

	public NvAttribute(int idAttributeGroup, String color, int position) {
		this.idAttributeGroup = idAttributeGroup;
		this.color = color;
		this.position = position;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_attribute", unique = true, nullable = false)
	public Integer getIdAttribute() {
		return this.idAttribute;
	}

	public void setIdAttribute(Integer idAttribute) {
		this.idAttribute = idAttribute;
	}

	@Column(name = "id_attribute_group", nullable = false)
	public int getIdAttributeGroup() {
		return this.idAttributeGroup;
	}

	public void setIdAttributeGroup(int idAttributeGroup) {
		this.idAttributeGroup = idAttributeGroup;
	}

	@Column(name = "color", length = 32)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

}
