package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvAttributeShop generated by hbm2java
 */
@Entity
@Table(name = "nv_attribute_shop", catalog = "NVPrestashop")
public class NvAttributeShop implements java.io.Serializable {

	private NvAttributeShopId id;

	public NvAttributeShop() {
	}

	public NvAttributeShop(NvAttributeShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttribute", column = @Column(name = "id_attribute", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvAttributeShopId getId() {
		return this.id;
	}

	public void setId(NvAttributeShopId id) {
		this.id = id;
	}

}
