package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvAttachment generated by hbm2java
 */
@Entity
@Table(name = "nv_attachment", catalog = "NVPrestashop")
public class NvAttachment implements java.io.Serializable {

	private Integer idAttachment;
	private String file;
	private String fileName;
	private long fileSize;
	private String mime;

	public NvAttachment() {
	}

	public NvAttachment(String file, String fileName, long fileSize, String mime) {
		this.file = file;
		this.fileName = fileName;
		this.fileSize = fileSize;
		this.mime = mime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_attachment", unique = true, nullable = false)
	public Integer getIdAttachment() {
		return this.idAttachment;
	}

	public void setIdAttachment(Integer idAttachment) {
		this.idAttachment = idAttachment;
	}

	@Column(name = "file", nullable = false, length = 40)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "file_name", nullable = false, length = 128)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_size", nullable = false)
	public long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(long fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "mime", nullable = false, length = 128)
	public String getMime() {
		return this.mime;
	}

	public void setMime(String mime) {
		this.mime = mime;
	}

}
