package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvAttachmentLang generated by hbm2java
 */
@Entity
@Table(name = "nv_attachment_lang", catalog = "NVPrestashop")
public class NvAttachmentLang implements java.io.Serializable {

	private NvAttachmentLangId id;
	private String name;
	private String description;

	public NvAttachmentLang() {
	}

	public NvAttachmentLang(NvAttachmentLangId id) {
		this.id = id;
	}

	public NvAttachmentLang(NvAttachmentLangId id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttachment", column = @Column(name = "id_attachment", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvAttachmentLangId getId() {
		return this.id;
	}

	public void setId(NvAttachmentLangId id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
