package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvBadge generated by hbm2java
 */
@Entity
@Table(name = "nv_badge", catalog = "NVPrestashop")
public class NvBadge implements java.io.Serializable {

	private Integer idBadge;
	private int idPsBadge;
	private String type;
	private int idGroup;
	private int groupPosition;
	private int scoring;
	private Integer awb;
	private boolean validated;

	public NvBadge() {
	}

	public NvBadge(int idPsBadge, String type, int idGroup, int groupPosition, int scoring, boolean validated) {
		this.idPsBadge = idPsBadge;
		this.type = type;
		this.idGroup = idGroup;
		this.groupPosition = groupPosition;
		this.scoring = scoring;
		this.validated = validated;
	}

	public NvBadge(int idPsBadge, String type, int idGroup, int groupPosition, int scoring, Integer awb, boolean validated) {
		this.idPsBadge = idPsBadge;
		this.type = type;
		this.idGroup = idGroup;
		this.groupPosition = groupPosition;
		this.scoring = scoring;
		this.awb = awb;
		this.validated = validated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_badge", unique = true, nullable = false)
	public Integer getIdBadge() {
		return this.idBadge;
	}

	public void setIdBadge(Integer idBadge) {
		this.idBadge = idBadge;
	}

	@Column(name = "id_ps_badge", nullable = false)
	public int getIdPsBadge() {
		return this.idPsBadge;
	}

	public void setIdPsBadge(int idPsBadge) {
		this.idPsBadge = idPsBadge;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "id_group", nullable = false)
	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	@Column(name = "group_position", nullable = false)
	public int getGroupPosition() {
		return this.groupPosition;
	}

	public void setGroupPosition(int groupPosition) {
		this.groupPosition = groupPosition;
	}

	@Column(name = "scoring", nullable = false)
	public int getScoring() {
		return this.scoring;
	}

	public void setScoring(int scoring) {
		this.scoring = scoring;
	}

	@Column(name = "awb")
	public Integer getAwb() {
		return this.awb;
	}

	public void setAwb(Integer awb) {
		this.awb = awb;
	}

	@Column(name = "validated", nullable = false)
	public boolean isValidated() {
		return this.validated;
	}

	public void setValidated(boolean validated) {
		this.validated = validated;
	}

}
