package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCartRuleLang generated by hbm2java
 */
@Entity
@Table(name = "nv_cart_rule_lang", catalog = "NVPrestashop")
public class NvCartRuleLang implements java.io.Serializable {

	private NvCartRuleLangId id;
	private String name;

	public NvCartRuleLang() {
	}

	public NvCartRuleLang(NvCartRuleLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCartRule", column = @Column(name = "id_cart_rule", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvCartRuleLangId getId() {
		return this.id;
	}

	public void setId(NvCartRuleLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
