package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCartRuleGroupId generated by hbm2java
 */
@Embeddable
public class NvCartRuleGroupId implements java.io.Serializable {

	private int idCartRule;
	private int idGroup;

	public NvCartRuleGroupId() {
	}

	public NvCartRuleGroupId(int idCartRule, int idGroup) {
		this.idCartRule = idCartRule;
		this.idGroup = idGroup;
	}

	@Column(name = "id_cart_rule", nullable = false)
	public int getIdCartRule() {
		return this.idCartRule;
	}

	public void setIdCartRule(int idCartRule) {
		this.idCartRule = idCartRule;
	}

	@Column(name = "id_group", nullable = false)
	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCartRuleGroupId))
			return false;
		NvCartRuleGroupId castOther = (NvCartRuleGroupId) other;

		return (this.getIdCartRule() == castOther.getIdCartRule()) && (this.getIdGroup() == castOther.getIdGroup());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCartRule();
		result = 37 * result + this.getIdGroup();
		return result;
	}

}
