package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCartRuleCombination generated by hbm2java
 */
@Entity
@Table(name = "nv_cart_rule_combination", catalog = "NVPrestashop")
public class NvCartRuleCombination implements java.io.Serializable {

	private NvCartRuleCombinationId id;

	public NvCartRuleCombination() {
	}

	public NvCartRuleCombination(NvCartRuleCombinationId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCartRule1", column = @Column(name = "id_cart_rule_1", nullable = false)),
			@AttributeOverride(name = "idCartRule2", column = @Column(name = "id_cart_rule_2", nullable = false)) })
	public NvCartRuleCombinationId getId() {
		return this.id;
	}

	public void setId(NvCartRuleCombinationId id) {
		this.id = id;
	}

}
