package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCartRuleShop generated by hbm2java
 */
@Entity
@Table(name = "nv_cart_rule_shop", catalog = "NVPrestashop")
public class NvCartRuleShop implements java.io.Serializable {

	private NvCartRuleShopId id;

	public NvCartRuleShop() {
	}

	public NvCartRuleShop(NvCartRuleShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCartRule", column = @Column(name = "id_cart_rule", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCartRuleShopId getId() {
		return this.id;
	}

	public void setId(NvCartRuleShopId id) {
		this.id = id;
	}

}
