package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCartRuleShopId generated by hbm2java
 */
@Embeddable
public class NvCartRuleShopId implements java.io.Serializable {

	private int idCartRule;
	private int idShop;

	public NvCartRuleShopId() {
	}

	public NvCartRuleShopId(int idCartRule, int idShop) {
		this.idCartRule = idCartRule;
		this.idShop = idShop;
	}

	@Column(name = "id_cart_rule", nullable = false)
	public int getIdCartRule() {
		return this.idCartRule;
	}

	public void setIdCartRule(int idCartRule) {
		this.idCartRule = idCartRule;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCartRuleShopId))
			return false;
		NvCartRuleShopId castOther = (NvCartRuleShopId) other;

		return (this.getIdCartRule() == castOther.getIdCartRule()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCartRule();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
