package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCartRuleProductRuleValueId generated by hbm2java
 */
@Embeddable
public class NvCartRuleProductRuleValueId implements java.io.Serializable {

	private int idProductRule;
	private int idItem;

	public NvCartRuleProductRuleValueId() {
	}

	public NvCartRuleProductRuleValueId(int idProductRule, int idItem) {
		this.idProductRule = idProductRule;
		this.idItem = idItem;
	}

	@Column(name = "id_product_rule", nullable = false)
	public int getIdProductRule() {
		return this.idProductRule;
	}

	public void setIdProductRule(int idProductRule) {
		this.idProductRule = idProductRule;
	}

	@Column(name = "id_item", nullable = false)
	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCartRuleProductRuleValueId))
			return false;
		NvCartRuleProductRuleValueId castOther = (NvCartRuleProductRuleValueId) other;

		return (this.getIdProductRule() == castOther.getIdProductRule()) && (this.getIdItem() == castOther.getIdItem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductRule();
		result = 37 * result + this.getIdItem();
		return result;
	}

}
