package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvCartRuleProductRuleGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_cart_rule_product_rule_group", catalog = "NVPrestashop")
public class NvCartRuleProductRuleGroup implements java.io.Serializable {

	private Integer idProductRuleGroup;
	private int idCartRule;
	private int quantity;

	public NvCartRuleProductRuleGroup() {
	}

	public NvCartRuleProductRuleGroup(int idCartRule, int quantity) {
		this.idCartRule = idCartRule;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_product_rule_group", unique = true, nullable = false)
	public Integer getIdProductRuleGroup() {
		return this.idProductRuleGroup;
	}

	public void setIdProductRuleGroup(Integer idProductRuleGroup) {
		this.idProductRuleGroup = idProductRuleGroup;
	}

	@Column(name = "id_cart_rule", nullable = false)
	public int getIdCartRule() {
		return this.idCartRule;
	}

	public void setIdCartRule(int idCartRule) {
		this.idCartRule = idCartRule;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
