package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCategoryShopId generated by hbm2java
 */
@Embeddable
public class NvCategoryShopId implements java.io.Serializable {

	private int idCategory;
	private int idShop;

	public NvCategoryShopId() {
	}

	public NvCategoryShopId(int idCategory, int idShop) {
		this.idCategory = idCategory;
		this.idShop = idShop;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCategoryShopId))
			return false;
		NvCategoryShopId castOther = (NvCategoryShopId) other;

		return (this.getIdCategory() == castOther.getIdCategory()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCategory();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
