package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCarrierZoneId generated by hbm2java
 */
@Embeddable
public class NvCarrierZoneId implements java.io.Serializable {

	private int idCarrier;
	private int idZone;

	public NvCarrierZoneId() {
	}

	public NvCarrierZoneId(int idCarrier, int idZone) {
		this.idCarrier = idCarrier;
		this.idZone = idZone;
	}

	@Column(name = "id_carrier", nullable = false)
	public int getIdCarrier() {
		return this.idCarrier;
	}

	public void setIdCarrier(int idCarrier) {
		this.idCarrier = idCarrier;
	}

	@Column(name = "id_zone", nullable = false)
	public int getIdZone() {
		return this.idZone;
	}

	public void setIdZone(int idZone) {
		this.idZone = idZone;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCarrierZoneId))
			return false;
		NvCarrierZoneId castOther = (NvCarrierZoneId) other;

		return (this.getIdCarrier() == castOther.getIdCarrier()) && (this.getIdZone() == castOther.getIdZone());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCarrier();
		result = 37 * result + this.getIdZone();
		return result;
	}

}
