package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCarrierShop generated by hbm2java
 */
@Entity
@Table(name = "nv_carrier_shop", catalog = "NVPrestashop")
public class NvCarrierShop implements java.io.Serializable {

	private NvCarrierShopId id;

	public NvCarrierShop() {
	}

	public NvCarrierShop(NvCarrierShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCarrier", column = @Column(name = "id_carrier", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCarrierShopId getId() {
		return this.id;
	}

	public void setId(NvCarrierShopId id) {
		this.id = id;
	}

}
