package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCategoryLangId generated by hbm2java
 */
@Embeddable
public class NvCategoryLangId implements java.io.Serializable {

	private int idCategory;
	private int idShop;
	private int idLang;

	public NvCategoryLangId() {
	}

	public NvCategoryLangId(int idCategory, int idShop, int idLang) {
		this.idCategory = idCategory;
		this.idShop = idShop;
		this.idLang = idLang;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCategoryLangId))
			return false;
		NvCategoryLangId castOther = (NvCategoryLangId) other;

		return (this.getIdCategory() == castOther.getIdCategory()) && (this.getIdShop() == castOther.getIdShop())
						&& (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCategory();
		result = 37 * result + this.getIdShop();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
