package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCarrierZone generated by hbm2java
 */
@Entity
@Table(name = "nv_carrier_zone", catalog = "NVPrestashop")
public class NvCarrierZone implements java.io.Serializable {

	private NvCarrierZoneId id;

	public NvCarrierZone() {
	}

	public NvCarrierZone(NvCarrierZoneId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCarrier", column = @Column(name = "id_carrier", nullable = false)),
			@AttributeOverride(name = "idZone", column = @Column(name = "id_zone", nullable = false)) })
	public NvCarrierZoneId getId() {
		return this.id;
	}

	public void setId(NvCarrierZoneId id) {
		this.id = id;
	}

}
