package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCategoryShop generated by hbm2java
 */
@Entity
@Table(name = "nv_category_shop", catalog = "NVPrestashop")
public class NvCategoryShop implements java.io.Serializable {

	private NvCategoryShopId id;
	private int position;

	public NvCategoryShop() {
	}

	public NvCategoryShop(NvCategoryShopId id, int position) {
		this.id = id;
		this.position = position;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCategory", column = @Column(name = "id_category", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCategoryShopId getId() {
		return this.id;
	}

	public void setId(NvCategoryShopId id) {
		this.id = id;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

}
