package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCarrierShopId generated by hbm2java
 */
@Embeddable
public class NvCarrierShopId implements java.io.Serializable {

	private int idCarrier;
	private int idShop;

	public NvCarrierShopId() {
	}

	public NvCarrierShopId(int idCarrier, int idShop) {
		this.idCarrier = idCarrier;
		this.idShop = idShop;
	}

	@Column(name = "id_carrier", nullable = false)
	public int getIdCarrier() {
		return this.idCarrier;
	}

	public void setIdCarrier(int idCarrier) {
		this.idCarrier = idCarrier;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCarrierShopId))
			return false;
		NvCarrierShopId castOther = (NvCarrierShopId) other;

		return (this.getIdCarrier() == castOther.getIdCarrier()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCarrier();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
