package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCategoryGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_category_group", catalog = "NVPrestashop")
public class NvCategoryGroup implements java.io.Serializable {

	private NvCategoryGroupId id;

	public NvCategoryGroup() {
	}

	public NvCategoryGroup(NvCategoryGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCategory", column = @Column(name = "id_category", nullable = false)),
			@AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)) })
	public NvCategoryGroupId getId() {
		return this.id;
	}

	public void setId(NvCategoryGroupId id) {
		this.id = id;
	}

}
