package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCartCartRule generated by hbm2java
 */
@Entity
@Table(name = "nv_cart_cart_rule", catalog = "NVPrestashop")
public class NvCartCartRule implements java.io.Serializable {

	private NvCartCartRuleId id;

	public NvCartCartRule() {
	}

	public NvCartCartRule(NvCartCartRuleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCart", column = @Column(name = "id_cart", nullable = false)),
			@AttributeOverride(name = "idCartRule", column = @Column(name = "id_cart_rule", nullable = false)) })
	public NvCartCartRuleId getId() {
		return this.id;
	}

	public void setId(NvCartCartRuleId id) {
		this.id = id;
	}

}
