package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCmsBlockLangId generated by hbm2java
 */
@Embeddable
public class NvCmsBlockLangId implements java.io.Serializable {

	private int idCmsBlock;
	private int idLang;

	public NvCmsBlockLangId() {
	}

	public NvCmsBlockLangId(int idCmsBlock, int idLang) {
		this.idCmsBlock = idCmsBlock;
		this.idLang = idLang;
	}

	@Column(name = "id_cms_block", nullable = false)
	public int getIdCmsBlock() {
		return this.idCmsBlock;
	}

	public void setIdCmsBlock(int idCmsBlock) {
		this.idCmsBlock = idCmsBlock;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCmsBlockLangId))
			return false;
		NvCmsBlockLangId castOther = (NvCmsBlockLangId) other;

		return (this.getIdCmsBlock() == castOther.getIdCmsBlock()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCmsBlock();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
