package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsBlockShop generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_block_shop", catalog = "NVPrestashop")
public class NvCmsBlockShop implements java.io.Serializable {

	private NvCmsBlockShopId id;

	public NvCmsBlockShop() {
	}

	public NvCmsBlockShop(NvCmsBlockShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsBlock", column = @Column(name = "id_cms_block", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCmsBlockShopId getId() {
		return this.id;
	}

	public void setId(NvCmsBlockShopId id) {
		this.id = id;
	}

}
