package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsRoleLang generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_role_lang", catalog = "NVPrestashop")
public class NvCmsRoleLang implements java.io.Serializable {

	private NvCmsRoleLangId id;
	private String name;

	public NvCmsRoleLang() {
	}

	public NvCmsRoleLang(NvCmsRoleLangId id) {
		this.id = id;
	}

	public NvCmsRoleLang(NvCmsRoleLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsRole", column = @Column(name = "id_cms_role", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCmsRoleLangId getId() {
		return this.id;
	}

	public void setId(NvCmsRoleLangId id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
