package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCmsBlockShopId generated by hbm2java
 */
@Embeddable
public class NvCmsBlockShopId implements java.io.Serializable {

	private int idCmsBlock;
	private int idShop;

	public NvCmsBlockShopId() {
	}

	public NvCmsBlockShopId(int idCmsBlock, int idShop) {
		this.idCmsBlock = idCmsBlock;
		this.idShop = idShop;
	}

	@Column(name = "id_cms_block", nullable = false)
	public int getIdCmsBlock() {
		return this.idCmsBlock;
	}

	public void setIdCmsBlock(int idCmsBlock) {
		this.idCmsBlock = idCmsBlock;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCmsBlockShopId))
			return false;
		NvCmsBlockShopId castOther = (NvCmsBlockShopId) other;

		return (this.getIdCmsBlock() == castOther.getIdCmsBlock()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCmsBlock();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
