package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsCategoryShop generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_category_shop", catalog = "NVPrestashop")
public class NvCmsCategoryShop implements java.io.Serializable {

	private NvCmsCategoryShopId id;

	public NvCmsCategoryShop() {
	}

	public NvCmsCategoryShop(NvCmsCategoryShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsCategory", column = @Column(name = "id_cms_category", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCmsCategoryShopId getId() {
		return this.id;
	}

	public void setId(NvCmsCategoryShopId id) {
		this.id = id;
	}

}
