package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsShop generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_shop", catalog = "NVPrestashop")
public class NvCmsShop implements java.io.Serializable {

	private NvCmsShopId id;

	public NvCmsShop() {
	}

	public NvCmsShop(NvCmsShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCms", column = @Column(name = "id_cms", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCmsShopId getId() {
		return this.id;
	}

	public void setId(NvCmsShopId id) {
		this.id = id;
	}

}
