package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsBlockLang generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_block_lang", catalog = "NVPrestashop")
public class NvCmsBlockLang implements java.io.Serializable {

	private NvCmsBlockLangId id;
	private String name;

	public NvCmsBlockLang() {
	}

	public NvCmsBlockLang(NvCmsBlockLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsBlock", column = @Column(name = "id_cms_block", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvCmsBlockLangId getId() {
		return this.id;
	}

	public void setId(NvCmsBlockLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
