package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCmsCategoryLang generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_category_lang", catalog = "NVPrestashop")
public class NvCmsCategoryLang implements java.io.Serializable {

	private NvCmsCategoryLangId id;
	private String name;
	private String description;
	private String linkRewrite;
	private String metaTitle;
	private String metaKeywords;
	private String metaDescription;

	public NvCmsCategoryLang() {
	}

	public NvCmsCategoryLang(NvCmsCategoryLangId id, String name, String linkRewrite) {
		this.id = id;
		this.name = name;
		this.linkRewrite = linkRewrite;
	}

	public NvCmsCategoryLang(NvCmsCategoryLangId id, String name, String description, String linkRewrite, String metaTitle, String metaKeywords,
					String metaDescription) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.linkRewrite = linkRewrite;
		this.metaTitle = metaTitle;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsCategory", column = @Column(name = "id_cms_category", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvCmsCategoryLangId getId() {
		return this.id;
	}

	public void setId(NvCmsCategoryLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "link_rewrite", nullable = false, length = 128)
	public String getLinkRewrite() {
		return this.linkRewrite;
	}

	public void setLinkRewrite(String linkRewrite) {
		this.linkRewrite = linkRewrite;
	}

	@Column(name = "meta_title", length = 128)
	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	@Column(name = "meta_keywords")
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "meta_description")
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

}
