package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCmsCategoryShopId generated by hbm2java
 */
@Embeddable
public class NvCmsCategoryShopId implements java.io.Serializable {

	private int idCmsCategory;
	private int idShop;

	public NvCmsCategoryShopId() {
	}

	public NvCmsCategoryShopId(int idCmsCategory, int idShop) {
		this.idCmsCategory = idCmsCategory;
		this.idShop = idShop;
	}

	@Column(name = "id_cms_category", nullable = false)
	public int getIdCmsCategory() {
		return this.idCmsCategory;
	}

	public void setIdCmsCategory(int idCmsCategory) {
		this.idCmsCategory = idCmsCategory;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCmsCategoryShopId))
			return false;
		NvCmsCategoryShopId castOther = (NvCmsCategoryShopId) other;

		return (this.getIdCmsCategory() == castOther.getIdCmsCategory()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCmsCategory();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
