package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvCmsRole generated by hbm2java
 */
@Entity
@Table(name = "nv_cms_role", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class NvCmsRole implements java.io.Serializable {

	private NvCmsRoleId id;
	private String name;

	public NvCmsRole() {
	}

	public NvCmsRole(NvCmsRoleId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCmsRole", column = @Column(name = "id_cms_role", nullable = false)),
			@AttributeOverride(name = "idCms", column = @Column(name = "id_cms", nullable = false)) })
	public NvCmsRoleId getId() {
		return this.id;
	}

	public void setId(NvCmsRoleId id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
