package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCmsRoleId generated by hbm2java
 */
@Embeddable
public class NvCmsRoleId implements java.io.Serializable {

	private int idCmsRole;
	private int idCms;

	public NvCmsRoleId() {
	}

	public NvCmsRoleId(int idCmsRole, int idCms) {
		this.idCmsRole = idCmsRole;
		this.idCms = idCms;
	}

	@Column(name = "id_cms_role", nullable = false)
	public int getIdCmsRole() {
		return this.idCmsRole;
	}

	public void setIdCmsRole(int idCmsRole) {
		this.idCmsRole = idCmsRole;
	}

	@Column(name = "id_cms", nullable = false)
	public int getIdCms() {
		return this.idCms;
	}

	public void setIdCms(int idCms) {
		this.idCms = idCms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCmsRoleId))
			return false;
		NvCmsRoleId castOther = (NvCmsRoleId) other;

		return (this.getIdCmsRole() == castOther.getIdCmsRole()) && (this.getIdCms() == castOther.getIdCms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCmsRole();
		result = 37 * result + this.getIdCms();
		return result;
	}

}
