package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvCompare generated by hbm2java
 */
@Entity
@Table(name = "nv_compare", catalog = "NVPrestashop")
public class NvCompare implements java.io.Serializable {

	private Integer idCompare;
	private int idCustomer;

	public NvCompare() {
	}

	public NvCompare(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_compare", unique = true, nullable = false)
	public Integer getIdCompare() {
		return this.idCompare;
	}

	public void setIdCompare(Integer idCompare) {
		this.idCompare = idCompare;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

}
