package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvContactShop generated by hbm2java
 */
@Entity
@Table(name = "nv_contact_shop", catalog = "NVPrestashop")
public class NvContactShop implements java.io.Serializable {

	private NvContactShopId id;

	public NvContactShop() {
	}

	public NvContactShop(NvContactShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idContact", column = @Column(name = "id_contact", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvContactShopId getId() {
		return this.id;
	}

	public void setId(NvContactShopId id) {
		this.id = id;
	}

}
