package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvCompareProduct generated by hbm2java
 */
@Entity
@Table(name = "nv_compare_product", catalog = "NVPrestashop")
public class NvCompareProduct implements java.io.Serializable {

	private NvCompareProductId id;
	private Date dateAdd;
	private Date dateUpd;

	public NvCompareProduct() {
	}

	public NvCompareProduct(NvCompareProductId id, Date dateAdd, Date dateUpd) {
		this.id = id;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCompare", column = @Column(name = "id_compare", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)) })
	public NvCompareProductId getId() {
		return this.id;
	}

	public void setId(NvCompareProductId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
