package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvConnectionsPage generated by hbm2java
 */
@Entity
@Table(name = "nv_connections_page", catalog = "NVPrestashop")
public class NvConnectionsPage implements java.io.Serializable {

	private NvConnectionsPageId id;
	private Date timeEnd;

	public NvConnectionsPage() {
	}

	public NvConnectionsPage(NvConnectionsPageId id) {
		this.id = id;
	}

	public NvConnectionsPage(NvConnectionsPageId id, Date timeEnd) {
		this.id = id;
		this.timeEnd = timeEnd;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idConnections", column = @Column(name = "id_connections", nullable = false)),
			@AttributeOverride(name = "idPage", column = @Column(name = "id_page", nullable = false)),
			@AttributeOverride(name = "timeStart", column = @Column(name = "time_start", nullable = false, length = 0)) })
	public NvConnectionsPageId getId() {
		return this.id;
	}

	public void setId(NvConnectionsPageId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_end", length = 0)
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

}
