package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvConditionBadge generated by hbm2java
 */
@Entity
@Table(name = "nv_condition_badge", catalog = "NVPrestashop")
public class NvConditionBadge implements java.io.Serializable {

	private NvConditionBadgeId id;

	public NvConditionBadge() {
	}

	public NvConditionBadge(NvConditionBadgeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCondition", column = @Column(name = "id_condition", nullable = false)),
			@AttributeOverride(name = "idBadge", column = @Column(name = "id_badge", nullable = false)) })
	public NvConditionBadgeId getId() {
		return this.id;
	}

	public void setId(NvConditionBadgeId id) {
		this.id = id;
	}

}
