package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvConditionBadgeId generated by hbm2java
 */
@Embeddable
public class NvConditionBadgeId implements java.io.Serializable {

	private int idCondition;
	private int idBadge;

	public NvConditionBadgeId() {
	}

	public NvConditionBadgeId(int idCondition, int idBadge) {
		this.idCondition = idCondition;
		this.idBadge = idBadge;
	}

	@Column(name = "id_condition", nullable = false)
	public int getIdCondition() {
		return this.idCondition;
	}

	public void setIdCondition(int idCondition) {
		this.idCondition = idCondition;
	}

	@Column(name = "id_badge", nullable = false)
	public int getIdBadge() {
		return this.idBadge;
	}

	public void setIdBadge(int idBadge) {
		this.idBadge = idBadge;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvConditionBadgeId))
			return false;
		NvConditionBadgeId castOther = (NvConditionBadgeId) other;

		return (this.getIdCondition() == castOther.getIdCondition()) && (this.getIdBadge() == castOther.getIdBadge());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCondition();
		result = 37 * result + this.getIdBadge();
		return result;
	}

}
