package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvConnectionsSource generated by hbm2java
 */
@Entity
@Table(name = "nv_connections_source", catalog = "NVPrestashop")
public class NvConnectionsSource implements java.io.Serializable {

	private Integer idConnectionsSource;
	private int idConnections;
	private String httpReferer;
	private String requestUri;
	private String keywords;
	private Date dateAdd;

	public NvConnectionsSource() {
	}

	public NvConnectionsSource(int idConnections, Date dateAdd) {
		this.idConnections = idConnections;
		this.dateAdd = dateAdd;
	}

	public NvConnectionsSource(int idConnections, String httpReferer, String requestUri, String keywords, Date dateAdd) {
		this.idConnections = idConnections;
		this.httpReferer = httpReferer;
		this.requestUri = requestUri;
		this.keywords = keywords;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_connections_source", unique = true, nullable = false)
	public Integer getIdConnectionsSource() {
		return this.idConnectionsSource;
	}

	public void setIdConnectionsSource(Integer idConnectionsSource) {
		this.idConnectionsSource = idConnectionsSource;
	}

	@Column(name = "id_connections", nullable = false)
	public int getIdConnections() {
		return this.idConnections;
	}

	public void setIdConnections(int idConnections) {
		this.idConnections = idConnections;
	}

	@Column(name = "http_referer")
	public String getHttpReferer() {
		return this.httpReferer;
	}

	public void setHttpReferer(String httpReferer) {
		this.httpReferer = httpReferer;
	}

	@Column(name = "request_uri")
	public String getRequestUri() {
		return this.requestUri;
	}

	public void setRequestUri(String requestUri) {
		this.requestUri = requestUri;
	}

	@Column(name = "keywords")
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
