package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvConfigurationKpiLang generated by hbm2java
 */
@Entity
@Table(name = "nv_configuration_kpi_lang", catalog = "NVPrestashop")
public class NvConfigurationKpiLang implements java.io.Serializable {

	private NvConfigurationKpiLangId id;
	private String value;
	private Date dateUpd;

	public NvConfigurationKpiLang() {
	}

	public NvConfigurationKpiLang(NvConfigurationKpiLangId id) {
		this.id = id;
	}

	public NvConfigurationKpiLang(NvConfigurationKpiLangId id, String value, Date dateUpd) {
		this.id = id;
		this.value = value;
		this.dateUpd = dateUpd;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idConfigurationKpi", column = @Column(name = "id_configuration_kpi", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvConfigurationKpiLangId getId() {
		return this.id;
	}

	public void setId(NvConfigurationKpiLangId id) {
		this.id = id;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
