package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCountryShop generated by hbm2java
 */
@Entity
@Table(name = "nv_country_shop", catalog = "NVPrestashop")
public class NvCountryShop implements java.io.Serializable {

	private NvCountryShopId id;

	public NvCountryShop() {
	}

	public NvCountryShop(NvCountryShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCountry", column = @Column(name = "id_country", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCountryShopId getId() {
		return this.id;
	}

	public void setId(NvCountryShopId id) {
		this.id = id;
	}

}
