package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvContactLang generated by hbm2java
 */
@Entity
@Table(name = "nv_contact_lang", catalog = "NVPrestashop")
public class NvContactLang implements java.io.Serializable {

	private NvContactLangId id;
	private String name;
	private String description;

	public NvContactLang() {
	}

	public NvContactLang(NvContactLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	public NvContactLang(NvContactLangId id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idContact", column = @Column(name = "id_contact", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvContactLangId getId() {
		return this.id;
	}

	public void setId(NvContactLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
