package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCurrencyShopId generated by hbm2java
 */
@Embeddable
public class NvCurrencyShopId implements java.io.Serializable {

	private int idCurrency;
	private int idShop;

	public NvCurrencyShopId() {
	}

	public NvCurrencyShopId(int idCurrency, int idShop) {
		this.idCurrency = idCurrency;
		this.idShop = idShop;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCurrencyShopId))
			return false;
		NvCurrencyShopId castOther = (NvCurrencyShopId) other;

		return (this.getIdCurrency() == castOther.getIdCurrency()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCurrency();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
