package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvCustomerMessage generated by hbm2java
 */
@Entity
@Table(name = "nv_customer_message", catalog = "NVPrestashop")
public class NvCustomerMessage implements java.io.Serializable {

	private Integer idCustomerMessage;
	private Integer idCustomerThread;
	private Integer idEmployee;
	private String message;
	private String fileName;
	private String ipAddress;
	private String userAgent;
	private Date dateAdd;
	private Date dateUpd;
	private byte private_;
	private boolean read;

	public NvCustomerMessage() {
	}

	public NvCustomerMessage(String message, Date dateAdd, Date dateUpd, byte private_, boolean read) {
		this.message = message;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.private_ = private_;
		this.read = read;
	}

	public NvCustomerMessage(Integer idCustomerThread, Integer idEmployee, String message, String fileName, String ipAddress, String userAgent, Date dateAdd,
					Date dateUpd, byte private_, boolean read) {
		this.idCustomerThread = idCustomerThread;
		this.idEmployee = idEmployee;
		this.message = message;
		this.fileName = fileName;
		this.ipAddress = ipAddress;
		this.userAgent = userAgent;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.private_ = private_;
		this.read = read;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_customer_message", unique = true, nullable = false)
	public Integer getIdCustomerMessage() {
		return this.idCustomerMessage;
	}

	public void setIdCustomerMessage(Integer idCustomerMessage) {
		this.idCustomerMessage = idCustomerMessage;
	}

	@Column(name = "id_customer_thread")
	public Integer getIdCustomerThread() {
		return this.idCustomerThread;
	}

	public void setIdCustomerThread(Integer idCustomerThread) {
		this.idCustomerThread = idCustomerThread;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "message", nullable = false, length = 16777215)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "file_name", length = 18)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "ip_address", length = 16)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "user_agent", length = 128)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Column(name = "private", nullable = false)
	public byte getPrivate_() {
		return this.private_;
	}

	public void setPrivate_(byte private_) {
		this.private_ = private_;
	}

	@Column(name = "read", nullable = false)
	public boolean isRead() {
		return this.read;
	}

	public void setRead(boolean read) {
		this.read = read;
	}

}
