package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvCustomer generated by hbm2java
 */
@Entity
@Table(name = "nv_customer", catalog = "NVPrestashop")
public class NvCustomer implements java.io.Serializable {

	private Integer idCustomer;
	private int idShopGroup;
	private int idShop;
	private int idGender;
	private int idDefaultGroup;
	private Integer idLang;
	private int idRisk;
	private String company;
	private String siret;
	private String ape;
	private String firstname;
	private String lastname;
	private String email;
	private String passwd;
	private Date lastPasswdGen;
	private Date birthday;
	private boolean newsletter;
	private String ipRegistrationNewsletter;
	private Date newsletterDateAdd;
	private boolean optin;
	private String website;
	private BigDecimal outstandingAllowAmount;
	private boolean showPublicPrices;
	private int maxPaymentDays;
	private String secureKey;
	private String note;
	private boolean active;
	private boolean isGuest;
	private boolean deleted;
	private Date dateAdd;
	private Date dateUpd;

	public NvCustomer() {
	}

	public NvCustomer(int idShopGroup, int idShop, int idGender, int idDefaultGroup, int idRisk, String firstname, String lastname, String email,
					String passwd, Date lastPasswdGen, boolean newsletter, boolean optin, BigDecimal outstandingAllowAmount, boolean showPublicPrices,
					int maxPaymentDays, String secureKey, boolean active, boolean isGuest, boolean deleted, Date dateAdd, Date dateUpd) {
		this.idShopGroup = idShopGroup;
		this.idShop = idShop;
		this.idGender = idGender;
		this.idDefaultGroup = idDefaultGroup;
		this.idRisk = idRisk;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.passwd = passwd;
		this.lastPasswdGen = lastPasswdGen;
		this.newsletter = newsletter;
		this.optin = optin;
		this.outstandingAllowAmount = outstandingAllowAmount;
		this.showPublicPrices = showPublicPrices;
		this.maxPaymentDays = maxPaymentDays;
		this.secureKey = secureKey;
		this.active = active;
		this.isGuest = isGuest;
		this.deleted = deleted;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvCustomer(int idShopGroup, int idShop, int idGender, int idDefaultGroup, Integer idLang, int idRisk, String company, String siret, String ape,
					String firstname, String lastname, String email, String passwd, Date lastPasswdGen, Date birthday, boolean newsletter,
					String ipRegistrationNewsletter, Date newsletterDateAdd, boolean optin, String website, BigDecimal outstandingAllowAmount,
					boolean showPublicPrices, int maxPaymentDays, String secureKey, String note, boolean active, boolean isGuest, boolean deleted,
					Date dateAdd, Date dateUpd) {
		this.idShopGroup = idShopGroup;
		this.idShop = idShop;
		this.idGender = idGender;
		this.idDefaultGroup = idDefaultGroup;
		this.idLang = idLang;
		this.idRisk = idRisk;
		this.company = company;
		this.siret = siret;
		this.ape = ape;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.passwd = passwd;
		this.lastPasswdGen = lastPasswdGen;
		this.birthday = birthday;
		this.newsletter = newsletter;
		this.ipRegistrationNewsletter = ipRegistrationNewsletter;
		this.newsletterDateAdd = newsletterDateAdd;
		this.optin = optin;
		this.website = website;
		this.outstandingAllowAmount = outstandingAllowAmount;
		this.showPublicPrices = showPublicPrices;
		this.maxPaymentDays = maxPaymentDays;
		this.secureKey = secureKey;
		this.note = note;
		this.active = active;
		this.isGuest = isGuest;
		this.deleted = deleted;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_customer", unique = true, nullable = false)
	public Integer getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Integer idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_shop_group", nullable = false)
	public int getIdShopGroup() {
		return this.idShopGroup;
	}

	public void setIdShopGroup(int idShopGroup) {
		this.idShopGroup = idShopGroup;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_gender", nullable = false)
	public int getIdGender() {
		return this.idGender;
	}

	public void setIdGender(int idGender) {
		this.idGender = idGender;
	}

	@Column(name = "id_default_group", nullable = false)
	public int getIdDefaultGroup() {
		return this.idDefaultGroup;
	}

	public void setIdDefaultGroup(int idDefaultGroup) {
		this.idDefaultGroup = idDefaultGroup;
	}

	@Column(name = "id_lang")
	public Integer getIdLang() {
		return this.idLang;
	}

	public void setIdLang(Integer idLang) {
		this.idLang = idLang;
	}

	@Column(name = "id_risk", nullable = false)
	public int getIdRisk() {
		return this.idRisk;
	}

	public void setIdRisk(int idRisk) {
		this.idRisk = idRisk;
	}

	@Column(name = "company", length = 64)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "siret", length = 14)
	public String getSiret() {
		return this.siret;
	}

	public void setSiret(String siret) {
		this.siret = siret;
	}

	@Column(name = "ape", length = 5)
	public String getApe() {
		return this.ape;
	}

	public void setApe(String ape) {
		this.ape = ape;
	}

	@Column(name = "firstname", nullable = false, length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "passwd", nullable = false, length = 32)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_passwd_gen", nullable = false, length = 0)
	public Date getLastPasswdGen() {
		return this.lastPasswdGen;
	}

	public void setLastPasswdGen(Date lastPasswdGen) {
		this.lastPasswdGen = lastPasswdGen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 0)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "newsletter", nullable = false)
	public boolean isNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		this.newsletter = newsletter;
	}

	@Column(name = "ip_registration_newsletter", length = 15)
	public String getIpRegistrationNewsletter() {
		return this.ipRegistrationNewsletter;
	}

	public void setIpRegistrationNewsletter(String ipRegistrationNewsletter) {
		this.ipRegistrationNewsletter = ipRegistrationNewsletter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "newsletter_date_add", length = 0)
	public Date getNewsletterDateAdd() {
		return this.newsletterDateAdd;
	}

	public void setNewsletterDateAdd(Date newsletterDateAdd) {
		this.newsletterDateAdd = newsletterDateAdd;
	}

	@Column(name = "optin", nullable = false)
	public boolean isOptin() {
		return this.optin;
	}

	public void setOptin(boolean optin) {
		this.optin = optin;
	}

	@Column(name = "website", length = 128)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "outstanding_allow_amount", nullable = false, precision = 20, scale = 6)
	public BigDecimal getOutstandingAllowAmount() {
		return this.outstandingAllowAmount;
	}

	public void setOutstandingAllowAmount(BigDecimal outstandingAllowAmount) {
		this.outstandingAllowAmount = outstandingAllowAmount;
	}

	@Column(name = "show_public_prices", nullable = false)
	public boolean isShowPublicPrices() {
		return this.showPublicPrices;
	}

	public void setShowPublicPrices(boolean showPublicPrices) {
		this.showPublicPrices = showPublicPrices;
	}

	@Column(name = "max_payment_days", nullable = false)
	public int getMaxPaymentDays() {
		return this.maxPaymentDays;
	}

	public void setMaxPaymentDays(int maxPaymentDays) {
		this.maxPaymentDays = maxPaymentDays;
	}

	@Column(name = "secure_key", nullable = false, length = 32)
	public String getSecureKey() {
		return this.secureKey;
	}

	public void setSecureKey(String secureKey) {
		this.secureKey = secureKey;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "is_guest", nullable = false)
	public boolean isIsGuest() {
		return this.isGuest;
	}

	public void setIsGuest(boolean isGuest) {
		this.isGuest = isGuest;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
