package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCurrencyShop generated by hbm2java
 */
@Entity
@Table(name = "nv_currency_shop", catalog = "NVPrestashop")
public class NvCurrencyShop implements java.io.Serializable {

	private NvCurrencyShopId id;
	private BigDecimal conversionRate;

	public NvCurrencyShop() {
	}

	public NvCurrencyShop(NvCurrencyShopId id, BigDecimal conversionRate) {
		this.id = id;
		this.conversionRate = conversionRate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCurrency", column = @Column(name = "id_currency", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvCurrencyShopId getId() {
		return this.id;
	}

	public void setId(NvCurrencyShopId id) {
		this.id = id;
	}

	@Column(name = "conversion_rate", nullable = false, precision = 13, scale = 6)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

}
