package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_customer_group", catalog = "NVPrestashop")
public class NvCustomerGroup implements java.io.Serializable {

	private NvCustomerGroupId id;

	public NvCustomerGroup() {
	}

	public NvCustomerGroup(NvCustomerGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)),
			@AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)) })
	public NvCustomerGroupId getId() {
		return this.id;
	}

	public void setId(NvCustomerGroupId id) {
		this.id = id;
	}

}
