package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCustomizedData generated by hbm2java
 */
@Entity
@Table(name = "nv_customized_data", catalog = "NVPrestashop")
public class NvCustomizedData implements java.io.Serializable {

	private NvCustomizedDataId id;
	private String value;

	public NvCustomizedData() {
	}

	public NvCustomizedData(NvCustomizedDataId id, String value) {
		this.id = id;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCustomization", column = @Column(name = "id_customization", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false)),
			@AttributeOverride(name = "index", column = @Column(name = "index", nullable = false)) })
	public NvCustomizedDataId getId() {
		return this.id;
	}

	public void setId(NvCustomizedDataId id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
