package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvCustomizationId generated by hbm2java
 */
@Embeddable
public class NvCustomizationId implements java.io.Serializable {

	private int idCustomization;
	private int idCart;
	private int idProduct;
	private int idAddressDelivery;

	public NvCustomizationId() {
	}

	public NvCustomizationId(int idCustomization, int idCart, int idProduct, int idAddressDelivery) {
		this.idCustomization = idCustomization;
		this.idCart = idCart;
		this.idProduct = idProduct;
		this.idAddressDelivery = idAddressDelivery;
	}

	@Column(name = "id_customization", nullable = false)
	public int getIdCustomization() {
		return this.idCustomization;
	}

	public void setIdCustomization(int idCustomization) {
		this.idCustomization = idCustomization;
	}

	@Column(name = "id_cart", nullable = false)
	public int getIdCart() {
		return this.idCart;
	}

	public void setIdCart(int idCart) {
		this.idCart = idCart;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_address_delivery", nullable = false)
	public int getIdAddressDelivery() {
		return this.idAddressDelivery;
	}

	public void setIdAddressDelivery(int idAddressDelivery) {
		this.idAddressDelivery = idAddressDelivery;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvCustomizationId))
			return false;
		NvCustomizationId castOther = (NvCustomizationId) other;

		return (this.getIdCustomization() == castOther.getIdCustomization()) && (this.getIdCart() == castOther.getIdCart())
						&& (this.getIdProduct() == castOther.getIdProduct()) && (this.getIdAddressDelivery() == castOther.getIdAddressDelivery());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCustomization();
		result = 37 * result + this.getIdCart();
		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdAddressDelivery();
		return result;
	}

}
