package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvCurrency generated by hbm2java
 */
@Entity
@Table(name = "nv_currency", catalog = "NVPrestashop")
public class NvCurrency implements java.io.Serializable {

	private Integer idCurrency;
	private String name;
	private String isoCode;
	private String isoCodeNum;
	private String sign;
	private boolean blank;
	private boolean format;
	private boolean decimals;
	private BigDecimal conversionRate;
	private boolean deleted;
	private boolean active;

	public NvCurrency() {
	}

	public NvCurrency(String name, String isoCode, String isoCodeNum, String sign, boolean blank, boolean format, boolean decimals, BigDecimal conversionRate,
					boolean deleted, boolean active) {
		this.name = name;
		this.isoCode = isoCode;
		this.isoCodeNum = isoCodeNum;
		this.sign = sign;
		this.blank = blank;
		this.format = format;
		this.decimals = decimals;
		this.conversionRate = conversionRate;
		this.deleted = deleted;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_currency", unique = true, nullable = false)
	public Integer getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(Integer idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iso_code", nullable = false, length = 3)
	public String getIsoCode() {
		return this.isoCode;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	@Column(name = "iso_code_num", nullable = false, length = 3)
	public String getIsoCodeNum() {
		return this.isoCodeNum;
	}

	public void setIsoCodeNum(String isoCodeNum) {
		this.isoCodeNum = isoCodeNum;
	}

	@Column(name = "sign", nullable = false, length = 8)
	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	@Column(name = "blank", nullable = false)
	public boolean isBlank() {
		return this.blank;
	}

	public void setBlank(boolean blank) {
		this.blank = blank;
	}

	@Column(name = "format", nullable = false)
	public boolean isFormat() {
		return this.format;
	}

	public void setFormat(boolean format) {
		this.format = format;
	}

	@Column(name = "decimals", nullable = false)
	public boolean isDecimals() {
		return this.decimals;
	}

	public void setDecimals(boolean decimals) {
		this.decimals = decimals;
	}

	@Column(name = "conversion_rate", nullable = false, precision = 13, scale = 6)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
