package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvCustomization generated by hbm2java
 */
@Entity
@Table(name = "nv_customization", catalog = "NVPrestashop")
public class NvCustomization implements java.io.Serializable {

	private NvCustomizationId id;
	private int idProductAttribute;
	private int quantity;
	private int quantityRefunded;
	private int quantityReturned;
	private boolean inCart;

	public NvCustomization() {
	}

	public NvCustomization(NvCustomizationId id, int idProductAttribute, int quantity, int quantityRefunded, int quantityReturned, boolean inCart) {
		this.id = id;
		this.idProductAttribute = idProductAttribute;
		this.quantity = quantity;
		this.quantityRefunded = quantityRefunded;
		this.quantityReturned = quantityReturned;
		this.inCart = inCart;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCustomization", column = @Column(name = "id_customization", nullable = false)),
			@AttributeOverride(name = "idCart", column = @Column(name = "id_cart", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idAddressDelivery", column = @Column(name = "id_address_delivery", nullable = false)) })
	public NvCustomizationId getId() {
		return this.id;
	}

	public void setId(NvCustomizationId id) {
		this.id = id;
	}

	@Column(name = "id_product_attribute", nullable = false)
	public int getIdProductAttribute() {
		return this.idProductAttribute;
	}

	public void setIdProductAttribute(int idProductAttribute) {
		this.idProductAttribute = idProductAttribute;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "quantity_refunded", nullable = false)
	public int getQuantityRefunded() {
		return this.quantityRefunded;
	}

	public void setQuantityRefunded(int quantityRefunded) {
		this.quantityRefunded = quantityRefunded;
	}

	@Column(name = "quantity_returned", nullable = false)
	public int getQuantityReturned() {
		return this.quantityReturned;
	}

	public void setQuantityReturned(int quantityReturned) {
		this.quantityReturned = quantityReturned;
	}

	@Column(name = "in_cart", nullable = false)
	public boolean isInCart() {
		return this.inCart;
	}

	public void setInCart(boolean inCart) {
		this.inCart = inCart;
	}

}
