package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvDeliveryBoy generated by hbm2java
 */
@Entity
@Table(name = "nv_delivery_boy", catalog = "NVPrestashop")
public class NvDeliveryBoy implements java.io.Serializable {

	private Integer idDeliveryBoy;
	private int idGender;
	private String firstname;
	private String lastname;
	private Date birthday;
	private String email;
	private String address1;
	private String address2;
	private String postcode;
	private String city;
	private Integer idState;
	private Integer idCountry;
	private String phone;
	private String panCard;
	private String aadharCrd;
	private String voterId;
	private Boolean active;
	private Date dateAdd;
	private Date dateUpd;

	public NvDeliveryBoy() {
	}

	public NvDeliveryBoy(int idGender, String firstname, String lastname, String email, String address1, String city, String phone, String panCard,
					String aadharCrd, String voterId) {
		this.idGender = idGender;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.address1 = address1;
		this.city = city;
		this.phone = phone;
		this.panCard = panCard;
		this.aadharCrd = aadharCrd;
		this.voterId = voterId;
	}

	public NvDeliveryBoy(int idGender, String firstname, String lastname, Date birthday, String email, String address1, String address2, String postcode,
					String city, Integer idState, Integer idCountry, String phone, String panCard, String aadharCrd, String voterId, Boolean active,
					Date dateAdd, Date dateUpd) {
		this.idGender = idGender;
		this.firstname = firstname;
		this.lastname = lastname;
		this.birthday = birthday;
		this.email = email;
		this.address1 = address1;
		this.address2 = address2;
		this.postcode = postcode;
		this.city = city;
		this.idState = idState;
		this.idCountry = idCountry;
		this.phone = phone;
		this.panCard = panCard;
		this.aadharCrd = aadharCrd;
		this.voterId = voterId;
		this.active = active;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_delivery_boy", unique = true, nullable = false)
	public Integer getIdDeliveryBoy() {
		return this.idDeliveryBoy;
	}

	public void setIdDeliveryBoy(Integer idDeliveryBoy) {
		this.idDeliveryBoy = idDeliveryBoy;
	}

	@Column(name = "id_gender", nullable = false)
	public int getIdGender() {
		return this.idGender;
	}

	public void setIdGender(int idGender) {
		this.idGender = idGender;
	}

	@Column(name = "firstname", nullable = false, length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 0)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "email", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address1", nullable = false, length = 128)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 128)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "postcode", length = 12)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "city", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "id_state")
	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	@Column(name = "id_country")
	public Integer getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

	@Column(name = "phone", nullable = false, length = 32)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "pan_card", nullable = false, length = 32)
	public String getPanCard() {
		return this.panCard;
	}

	public void setPanCard(String panCard) {
		this.panCard = panCard;
	}

	@Column(name = "aadhar_crd", nullable = false, length = 32)
	public String getAadharCrd() {
		return this.aadharCrd;
	}

	public void setAadharCrd(String aadharCrd) {
		this.aadharCrd = aadharCrd;
	}

	@Column(name = "voter_id", nullable = false, length = 32)
	public String getVoterId() {
		return this.voterId;
	}

	public void setVoterId(String voterId) {
		this.voterId = voterId;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
