package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvEmployeeShop generated by hbm2java
 */
@Entity
@Table(name = "nv_employee_shop", catalog = "NVPrestashop")
public class NvEmployeeShop implements java.io.Serializable {

	private NvEmployeeShopId id;

	public NvEmployeeShop() {
	}

	public NvEmployeeShop(NvEmployeeShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idEmployee", column = @Column(name = "id_employee", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvEmployeeShopId getId() {
		return this.id;
	}

	public void setId(NvEmployeeShopId id) {
		this.id = id;
	}

}
