package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvFeatureShopId generated by hbm2java
 */
@Embeddable
public class NvFeatureShopId implements java.io.Serializable {

	private int idFeature;
	private int idShop;

	public NvFeatureShopId() {
	}

	public NvFeatureShopId(int idFeature, int idShop) {
		this.idFeature = idFeature;
		this.idShop = idShop;
	}

	@Column(name = "id_feature", nullable = false)
	public int getIdFeature() {
		return this.idFeature;
	}

	public void setIdFeature(int idFeature) {
		this.idFeature = idFeature;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvFeatureShopId))
			return false;
		NvFeatureShopId castOther = (NvFeatureShopId) other;

		return (this.getIdFeature() == castOther.getIdFeature()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFeature();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
