package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvFeatureShop generated by hbm2java
 */
@Entity
@Table(name = "nv_feature_shop", catalog = "NVPrestashop")
public class NvFeatureShop implements java.io.Serializable {

	private NvFeatureShopId id;

	public NvFeatureShop() {
	}

	public NvFeatureShop(NvFeatureShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idFeature", column = @Column(name = "id_feature", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvFeatureShopId getId() {
		return this.id;
	}

	public void setId(NvFeatureShopId id) {
		this.id = id;
	}

}
