package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvFeatureProductId generated by hbm2java
 */
@Embeddable
public class NvFeatureProductId implements java.io.Serializable {

	private int idFeature;
	private int idProduct;

	public NvFeatureProductId() {
	}

	public NvFeatureProductId(int idFeature, int idProduct) {
		this.idFeature = idFeature;
		this.idProduct = idProduct;
	}

	@Column(name = "id_feature", nullable = false)
	public int getIdFeature() {
		return this.idFeature;
	}

	public void setIdFeature(int idFeature) {
		this.idFeature = idFeature;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvFeatureProductId))
			return false;
		NvFeatureProductId castOther = (NvFeatureProductId) other;

		return (this.getIdFeature() == castOther.getIdFeature()) && (this.getIdProduct() == castOther.getIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFeature();
		result = 37 * result + this.getIdProduct();
		return result;
	}

}
