package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvFeatureProduct generated by hbm2java
 */
@Entity
@Table(name = "nv_feature_product", catalog = "NVPrestashop")
public class NvFeatureProduct implements java.io.Serializable {

	private NvFeatureProductId id;
	private int idFeatureValue;

	public NvFeatureProduct() {
	}

	public NvFeatureProduct(NvFeatureProductId id, int idFeatureValue) {
		this.id = id;
		this.idFeatureValue = idFeatureValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idFeature", column = @Column(name = "id_feature", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)) })
	public NvFeatureProductId getId() {
		return this.id;
	}

	public void setId(NvFeatureProductId id) {
		this.id = id;
	}

	@Column(name = "id_feature_value", nullable = false)
	public int getIdFeatureValue() {
		return this.idFeatureValue;
	}

	public void setIdFeatureValue(int idFeatureValue) {
		this.idFeatureValue = idFeatureValue;
	}

}
