package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvFeatureLang generated by hbm2java
 */
@Entity
@Table(name = "nv_feature_lang", catalog = "NVPrestashop")
public class NvFeatureLang implements java.io.Serializable {

	private NvFeatureLangId id;
	private String name;

	public NvFeatureLang() {
	}

	public NvFeatureLang(NvFeatureLangId id) {
		this.id = id;
	}

	public NvFeatureLang(NvFeatureLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idFeature", column = @Column(name = "id_feature", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvFeatureLangId getId() {
		return this.id;
	}

	public void setId(NvFeatureLangId id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
