package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvGenderLang generated by hbm2java
 */
@Entity
@Table(name = "nv_gender_lang", catalog = "NVPrestashop")
public class NvGenderLang implements java.io.Serializable {

	private NvGenderLangId id;
	private String name;

	public NvGenderLang() {
	}

	public NvGenderLang(NvGenderLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGender", column = @Column(name = "id_gender", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvGenderLangId getId() {
		return this.id;
	}

	public void setId(NvGenderLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
