package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvGender generated by hbm2java
 */
@Entity
@Table(name = "nv_gender", catalog = "NVPrestashop")
public class NvGender implements java.io.Serializable {

	private Integer idGender;
	private boolean type;

	public NvGender() {
	}

	public NvGender(boolean type) {
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_gender", unique = true, nullable = false)
	public Integer getIdGender() {
		return this.idGender;
	}

	public void setIdGender(Integer idGender) {
		this.idGender = idGender;
	}

	@Column(name = "type", nullable = false)
	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

}
