package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvGroupLang generated by hbm2java
 */
@Entity
@Table(name = "nv_group_lang", catalog = "NVPrestashop")
public class NvGroupLang implements java.io.Serializable {

	private NvGroupLangId id;
	private String name;

	public NvGroupLang() {
	}

	public NvGroupLang(NvGroupLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvGroupLangId getId() {
		return this.id;
	}

	public void setId(NvGroupLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
