package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvGroupLangId generated by hbm2java
 */
@Embeddable
public class NvGroupLangId implements java.io.Serializable {

	private int idGroup;
	private int idLang;

	public NvGroupLangId() {
	}

	public NvGroupLangId(int idGroup, int idLang) {
		this.idGroup = idGroup;
		this.idLang = idLang;
	}

	@Column(name = "id_group", nullable = false)
	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvGroupLangId))
			return false;
		NvGroupLangId castOther = (NvGroupLangId) other;

		return (this.getIdGroup() == castOther.getIdGroup()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGroup();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
