package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_group", catalog = "NVPrestashop")
public class NvGroup implements java.io.Serializable {

	private Integer idGroup;
	private BigDecimal reduction;
	private byte priceDisplayMethod;
	private boolean showPrices;
	private Date dateAdd;
	private Date dateUpd;

	public NvGroup() {
	}

	public NvGroup(BigDecimal reduction, byte priceDisplayMethod, boolean showPrices, Date dateAdd, Date dateUpd) {
		this.reduction = reduction;
		this.priceDisplayMethod = priceDisplayMethod;
		this.showPrices = showPrices;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_group", unique = true, nullable = false)
	public Integer getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	@Column(name = "reduction", nullable = false, precision = 17)
	public BigDecimal getReduction() {
		return this.reduction;
	}

	public void setReduction(BigDecimal reduction) {
		this.reduction = reduction;
	}

	@Column(name = "price_display_method", nullable = false)
	public byte getPriceDisplayMethod() {
		return this.priceDisplayMethod;
	}

	public void setPriceDisplayMethod(byte priceDisplayMethod) {
		this.priceDisplayMethod = priceDisplayMethod;
	}

	@Column(name = "show_prices", nullable = false)
	public boolean isShowPrices() {
		return this.showPrices;
	}

	public void setShowPrices(boolean showPrices) {
		this.showPrices = showPrices;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
