package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvHookModule generated by hbm2java
 */
@Entity
@Table(name = "nv_hook_module", catalog = "NVPrestashop")
public class NvHookModule implements java.io.Serializable {

	private NvHookModuleId id;
	private byte position;

	public NvHookModule() {
	}

	public NvHookModule(NvHookModuleId id, byte position) {
		this.id = id;
		this.position = position;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)),
			@AttributeOverride(name = "idHook", column = @Column(name = "id_hook", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvHookModuleId getId() {
		return this.id;
	}

	public void setId(NvHookModuleId id) {
		this.id = id;
	}

	@Column(name = "position", nullable = false)
	public byte getPosition() {
		return this.position;
	}

	public void setPosition(byte position) {
		this.position = position;
	}

}
