package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvHookAlias generated by hbm2java
 */
@Entity
@Table(name = "nv_hook_alias", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "alias"))
public class NvHookAlias implements java.io.Serializable {

	private Integer idHookAlias;
	private String alias;
	private String name;

	public NvHookAlias() {
	}

	public NvHookAlias(String alias, String name) {
		this.alias = alias;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_hook_alias", unique = true, nullable = false)
	public Integer getIdHookAlias() {
		return this.idHookAlias;
	}

	public void setIdHookAlias(Integer idHookAlias) {
		this.idHookAlias = idHookAlias;
	}

	@Column(name = "alias", unique = true, nullable = false, length = 64)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
