package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvHookModuleExceptions generated by hbm2java
 */
@Entity
@Table(name = "nv_hook_module_exceptions", catalog = "NVPrestashop")
public class NvHookModuleExceptions implements java.io.Serializable {

	private Integer idHookModuleExceptions;
	private int idShop;
	private int idModule;
	private int idHook;
	private String fileName;

	public NvHookModuleExceptions() {
	}

	public NvHookModuleExceptions(int idShop, int idModule, int idHook) {
		this.idShop = idShop;
		this.idModule = idModule;
		this.idHook = idHook;
	}

	public NvHookModuleExceptions(int idShop, int idModule, int idHook, String fileName) {
		this.idShop = idShop;
		this.idModule = idModule;
		this.idHook = idHook;
		this.fileName = fileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_hook_module_exceptions", unique = true, nullable = false)
	public Integer getIdHookModuleExceptions() {
		return this.idHookModuleExceptions;
	}

	public void setIdHookModuleExceptions(Integer idHookModuleExceptions) {
		this.idHookModuleExceptions = idHookModuleExceptions;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_module", nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	@Column(name = "id_hook", nullable = false)
	public int getIdHook() {
		return this.idHook;
	}

	public void setIdHook(int idHook) {
		this.idHook = idHook;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

}
