package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvHomesliderSlidesLang generated by hbm2java
 */
@Entity
@Table(name = "nv_homeslider_slides_lang", catalog = "NVPrestashop")
public class NvHomesliderSlidesLang implements java.io.Serializable {

	private NvHomesliderSlidesLangId id;
	private String title;
	private String description;
	private String legend;
	private String url;
	private String image;

	public NvHomesliderSlidesLang() {
	}

	public NvHomesliderSlidesLang(NvHomesliderSlidesLangId id, String title, String description, String legend, String url, String image) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.legend = legend;
		this.url = url;
		this.image = image;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idHomesliderSlides", column = @Column(name = "id_homeslider_slides", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvHomesliderSlidesLangId getId() {
		return this.id;
	}

	public void setId(NvHomesliderSlidesLangId id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "legend", nullable = false)
	public String getLegend() {
		return this.legend;
	}

	public void setLegend(String legend) {
		this.legend = legend;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
