package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvHomesliderSlides generated by hbm2java
 */
@Entity
@Table(name = "nv_homeslider_slides", catalog = "NVPrestashop")
public class NvHomesliderSlides implements java.io.Serializable {

	private Integer idHomesliderSlides;
	private int position;
	private boolean active;

	public NvHomesliderSlides() {
	}

	public NvHomesliderSlides(int position, boolean active) {
		this.position = position;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_homeslider_slides", unique = true, nullable = false)
	public Integer getIdHomesliderSlides() {
		return this.idHomesliderSlides;
	}

	public void setIdHomesliderSlides(Integer idHomesliderSlides) {
		this.idHomesliderSlides = idHomesliderSlides;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
