package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvHomesliderSlidesLangId generated by hbm2java
 */
@Embeddable
public class NvHomesliderSlidesLangId implements java.io.Serializable {

	private int idHomesliderSlides;
	private int idLang;

	public NvHomesliderSlidesLangId() {
	}

	public NvHomesliderSlidesLangId(int idHomesliderSlides, int idLang) {
		this.idHomesliderSlides = idHomesliderSlides;
		this.idLang = idLang;
	}

	@Column(name = "id_homeslider_slides", nullable = false)
	public int getIdHomesliderSlides() {
		return this.idHomesliderSlides;
	}

	public void setIdHomesliderSlides(int idHomesliderSlides) {
		this.idHomesliderSlides = idHomesliderSlides;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvHomesliderSlidesLangId))
			return false;
		NvHomesliderSlidesLangId castOther = (NvHomesliderSlidesLangId) other;

		return (this.getIdHomesliderSlides() == castOther.getIdHomesliderSlides()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHomesliderSlides();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
