package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvHomesliderId generated by hbm2java
 */
@Embeddable
public class NvHomesliderId implements java.io.Serializable {

	private int idHomesliderSlides;
	private int idShop;

	public NvHomesliderId() {
	}

	public NvHomesliderId(int idHomesliderSlides, int idShop) {
		this.idHomesliderSlides = idHomesliderSlides;
		this.idShop = idShop;
	}

	@Column(name = "id_homeslider_slides", nullable = false)
	public int getIdHomesliderSlides() {
		return this.idHomesliderSlides;
	}

	public void setIdHomesliderSlides(int idHomesliderSlides) {
		this.idHomesliderSlides = idHomesliderSlides;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvHomesliderId))
			return false;
		NvHomesliderId castOther = (NvHomesliderId) other;

		return (this.getIdHomesliderSlides() == castOther.getIdHomesliderSlides()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHomesliderSlides();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
