package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvHookModuleId generated by hbm2java
 */
@Embeddable
public class NvHookModuleId implements java.io.Serializable {

	private int idModule;
	private int idHook;
	private int idShop;

	public NvHookModuleId() {
	}

	public NvHookModuleId(int idModule, int idHook, int idShop) {
		this.idModule = idModule;
		this.idHook = idHook;
		this.idShop = idShop;
	}

	@Column(name = "id_module", nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	@Column(name = "id_hook", nullable = false)
	public int getIdHook() {
		return this.idHook;
	}

	public void setIdHook(int idHook) {
		this.idHook = idHook;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvHookModuleId))
			return false;
		NvHookModuleId castOther = (NvHookModuleId) other;

		return (this.getIdModule() == castOther.getIdModule()) && (this.getIdHook() == castOther.getIdHook()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdModule();
		result = 37 * result + this.getIdHook();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
