package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvImageLang generated by hbm2java
 */
@Entity
@Table(name = "nv_image_lang", catalog = "NVPrestashop")
public class NvImageLang implements java.io.Serializable {

	private NvImageLangId id;
	private String legend;

	public NvImageLang() {
	}

	public NvImageLang(NvImageLangId id) {
		this.id = id;
	}

	public NvImageLang(NvImageLangId id, String legend) {
		this.id = id;
		this.legend = legend;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idImage", column = @Column(name = "id_image", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvImageLangId getId() {
		return this.id;
	}

	public void setId(NvImageLangId id) {
		this.id = id;
	}

	@Column(name = "legend", length = 128)
	public String getLegend() {
		return this.legend;
	}

	public void setLegend(String legend) {
		this.legend = legend;
	}

}
