package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvImageShopId generated by hbm2java
 */
@Embeddable
public class NvImageShopId implements java.io.Serializable {

	private int idImage;
	private int idShop;

	public NvImageShopId() {
	}

	public NvImageShopId(int idImage, int idShop) {
		this.idImage = idImage;
		this.idShop = idShop;
	}

	@Column(name = "id_image", nullable = false)
	public int getIdImage() {
		return this.idImage;
	}

	public void setIdImage(int idImage) {
		this.idImage = idImage;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvImageShopId))
			return false;
		NvImageShopId castOther = (NvImageShopId) other;

		return (this.getIdImage() == castOther.getIdImage()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdImage();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
