package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvImageShop generated by hbm2java
 */
@Entity
@Table(name = "nv_image_shop", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = { "id_product", "id_shop", "cover" }))
public class NvImageShop implements java.io.Serializable {

	private NvImageShopId id;
	private int idProduct;
	private Boolean cover;

	public NvImageShop() {
	}

	public NvImageShop(NvImageShopId id, int idProduct) {
		this.id = id;
		this.idProduct = idProduct;
	}

	public NvImageShop(NvImageShopId id, int idProduct, Boolean cover) {
		this.id = id;
		this.idProduct = idProduct;
		this.cover = cover;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idImage", column = @Column(name = "id_image", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvImageShopId getId() {
		return this.id;
	}

	public void setId(NvImageShopId id) {
		this.id = id;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "cover")
	public Boolean getCover() {
		return this.cover;
	}

	public void setCover(Boolean cover) {
		this.cover = cover;
	}

}
