package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvInfo generated by hbm2java
 */
@Entity
@Table(name = "nv_info", catalog = "NVPrestashop")
public class NvInfo implements java.io.Serializable {

	private Integer idInfo;
	private Integer idShop;

	public NvInfo() {
	}

	public NvInfo(Integer idShop) {
		this.idShop = idShop;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_info", unique = true, nullable = false)
	public Integer getIdInfo() {
		return this.idInfo;
	}

	public void setIdInfo(Integer idInfo) {
		this.idInfo = idInfo;
	}

	@Column(name = "id_shop")
	public Integer getIdShop() {
		return this.idShop;
	}

	public void setIdShop(Integer idShop) {
		this.idShop = idShop;
	}

}
