package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvLayeredCategory generated by hbm2java
 */
@Entity
@Table(name = "nv_layered_category", catalog = "NVPrestashop")
public class NvLayeredCategory implements java.io.Serializable {

	private Integer idLayeredCategory;
	private int idShop;
	private int idCategory;
	private Integer idValue;
	private String type;
	private int position;
	private int filterType;
	private int filterShowLimit;

	public NvLayeredCategory() {
	}

	public NvLayeredCategory(int idShop, int idCategory, String type, int position, int filterType, int filterShowLimit) {
		this.idShop = idShop;
		this.idCategory = idCategory;
		this.type = type;
		this.position = position;
		this.filterType = filterType;
		this.filterShowLimit = filterShowLimit;
	}

	public NvLayeredCategory(int idShop, int idCategory, Integer idValue, String type, int position, int filterType, int filterShowLimit) {
		this.idShop = idShop;
		this.idCategory = idCategory;
		this.idValue = idValue;
		this.type = type;
		this.position = position;
		this.filterType = filterType;
		this.filterShowLimit = filterShowLimit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_layered_category", unique = true, nullable = false)
	public Integer getIdLayeredCategory() {
		return this.idLayeredCategory;
	}

	public void setIdLayeredCategory(Integer idLayeredCategory) {
		this.idLayeredCategory = idLayeredCategory;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "id_value")
	public Integer getIdValue() {
		return this.idValue;
	}

	public void setIdValue(Integer idValue) {
		this.idValue = idValue;
	}

	@Column(name = "type", nullable = false, length = 18)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "filter_type", nullable = false)
	public int getFilterType() {
		return this.filterType;
	}

	public void setFilterType(int filterType) {
		this.filterType = filterType;
	}

	@Column(name = "filter_show_limit", nullable = false)
	public int getFilterShowLimit() {
		return this.filterShowLimit;
	}

	public void setFilterShowLimit(int filterShowLimit) {
		this.filterShowLimit = filterShowLimit;
	}

}
