package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvLayeredPriceIndex generated by hbm2java
 */
@Entity
@Table(name = "nv_layered_price_index", catalog = "NVPrestashop")
public class NvLayeredPriceIndex implements java.io.Serializable {

	private NvLayeredPriceIndexId id;
	private int priceMin;
	private int priceMax;

	public NvLayeredPriceIndex() {
	}

	public NvLayeredPriceIndex(NvLayeredPriceIndexId id, int priceMin, int priceMax) {
		this.id = id;
		this.priceMin = priceMin;
		this.priceMax = priceMax;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idCurrency", column = @Column(name = "id_currency", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvLayeredPriceIndexId getId() {
		return this.id;
	}

	public void setId(NvLayeredPriceIndexId id) {
		this.id = id;
	}

	@Column(name = "price_min", nullable = false)
	public int getPriceMin() {
		return this.priceMin;
	}

	public void setPriceMin(int priceMin) {
		this.priceMin = priceMin;
	}

	@Column(name = "price_max", nullable = false)
	public int getPriceMax() {
		return this.priceMax;
	}

	public void setPriceMax(int priceMax) {
		this.priceMax = priceMax;
	}

}
