package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvLayeredProductAttributeId generated by hbm2java
 */
@Embeddable
public class NvLayeredProductAttributeId implements java.io.Serializable {

	private int idAttribute;
	private int idProduct;
	private int idShop;

	public NvLayeredProductAttributeId() {
	}

	public NvLayeredProductAttributeId(int idAttribute, int idProduct, int idShop) {
		this.idAttribute = idAttribute;
		this.idProduct = idProduct;
		this.idShop = idShop;
	}

	@Column(name = "id_attribute", nullable = false)
	public int getIdAttribute() {
		return this.idAttribute;
	}

	public void setIdAttribute(int idAttribute) {
		this.idAttribute = idAttribute;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvLayeredProductAttributeId))
			return false;
		NvLayeredProductAttributeId castOther = (NvLayeredProductAttributeId) other;

		return (this.getIdAttribute() == castOther.getIdAttribute()) && (this.getIdProduct() == castOther.getIdProduct())
						&& (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttribute();
		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
