package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvLayeredFilter generated by hbm2java
 */
@Entity
@Table(name = "nv_layered_filter", catalog = "NVPrestashop")
public class NvLayeredFilter implements java.io.Serializable {

	private Integer idLayeredFilter;
	private String name;
	private String filters;
	private int NCategories;
	private Date dateAdd;

	public NvLayeredFilter() {
	}

	public NvLayeredFilter(String name, int NCategories, Date dateAdd) {
		this.name = name;
		this.NCategories = NCategories;
		this.dateAdd = dateAdd;
	}

	public NvLayeredFilter(String name, String filters, int NCategories, Date dateAdd) {
		this.name = name;
		this.filters = filters;
		this.NCategories = NCategories;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_layered_filter", unique = true, nullable = false)
	public Integer getIdLayeredFilter() {
		return this.idLayeredFilter;
	}

	public void setIdLayeredFilter(Integer idLayeredFilter) {
		this.idLayeredFilter = idLayeredFilter;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "filters", length = 65535)
	public String getFilters() {
		return this.filters;
	}

	public void setFilters(String filters) {
		this.filters = filters;
	}

	@Column(name = "n_categories", nullable = false)
	public int getNCategories() {
		return this.NCategories;
	}

	public void setNCategories(int NCategories) {
		this.NCategories = NCategories;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
