package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvLayeredFilterShop generated by hbm2java
 */
@Entity
@Table(name = "nv_layered_filter_shop", catalog = "NVPrestashop")
public class NvLayeredFilterShop implements java.io.Serializable {

	private NvLayeredFilterShopId id;

	public NvLayeredFilterShop() {
	}

	public NvLayeredFilterShop(NvLayeredFilterShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idLayeredFilter", column = @Column(name = "id_layered_filter", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvLayeredFilterShopId getId() {
		return this.id;
	}

	public void setId(NvLayeredFilterShopId id) {
		this.id = id;
	}

}
