package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvLayeredFilterShopId generated by hbm2java
 */
@Embeddable
public class NvLayeredFilterShopId implements java.io.Serializable {

	private int idLayeredFilter;
	private int idShop;

	public NvLayeredFilterShopId() {
	}

	public NvLayeredFilterShopId(int idLayeredFilter, int idShop) {
		this.idLayeredFilter = idLayeredFilter;
		this.idShop = idShop;
	}

	@Column(name = "id_layered_filter", nullable = false)
	public int getIdLayeredFilter() {
		return this.idLayeredFilter;
	}

	public void setIdLayeredFilter(int idLayeredFilter) {
		this.idLayeredFilter = idLayeredFilter;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvLayeredFilterShopId))
			return false;
		NvLayeredFilterShopId castOther = (NvLayeredFilterShopId) other;

		return (this.getIdLayeredFilter() == castOther.getIdLayeredFilter()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdLayeredFilter();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
