package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvLang generated by hbm2java
 */
@Entity
@Table(name = "nv_lang", catalog = "NVPrestashop")
public class NvLang implements java.io.Serializable {

	private Integer idLang;
	private String name;
	private byte active;
	private String isoCode;
	private String languageCode;
	private String dateFormatLite;
	private String dateFormatFull;
	private boolean isRtl;

	public NvLang() {
	}

	public NvLang(String name, byte active, String isoCode, String languageCode, String dateFormatLite, String dateFormatFull, boolean isRtl) {
		this.name = name;
		this.active = active;
		this.isoCode = isoCode;
		this.languageCode = languageCode;
		this.dateFormatLite = dateFormatLite;
		this.dateFormatFull = dateFormatFull;
		this.isRtl = isRtl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_lang", unique = true, nullable = false)
	public Integer getIdLang() {
		return this.idLang;
	}

	public void setIdLang(Integer idLang) {
		this.idLang = idLang;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "active", nullable = false)
	public byte getActive() {
		return this.active;
	}

	public void setActive(byte active) {
		this.active = active;
	}

	@Column(name = "iso_code", nullable = false, length = 2)
	public String getIsoCode() {
		return this.isoCode;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	@Column(name = "language_code", nullable = false, length = 5)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "date_format_lite", nullable = false, length = 32)
	public String getDateFormatLite() {
		return this.dateFormatLite;
	}

	public void setDateFormatLite(String dateFormatLite) {
		this.dateFormatLite = dateFormatLite;
	}

	@Column(name = "date_format_full", nullable = false, length = 32)
	public String getDateFormatFull() {
		return this.dateFormatFull;
	}

	public void setDateFormatFull(String dateFormatFull) {
		this.dateFormatFull = dateFormatFull;
	}

	@Column(name = "is_rtl", nullable = false)
	public boolean isIsRtl() {
		return this.isRtl;
	}

	public void setIsRtl(boolean isRtl) {
		this.isRtl = isRtl;
	}

}
