package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvLayeredIndexableFeatureValueLangValueId generated by hbm2java
 */
@Embeddable
public class NvLayeredIndexableFeatureValueLangValueId implements java.io.Serializable {

	private int idFeatureValue;
	private int idLang;

	public NvLayeredIndexableFeatureValueLangValueId() {
	}

	public NvLayeredIndexableFeatureValueLangValueId(int idFeatureValue, int idLang) {
		this.idFeatureValue = idFeatureValue;
		this.idLang = idLang;
	}

	@Column(name = "id_feature_value", nullable = false)
	public int getIdFeatureValue() {
		return this.idFeatureValue;
	}

	public void setIdFeatureValue(int idFeatureValue) {
		this.idFeatureValue = idFeatureValue;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvLayeredIndexableFeatureValueLangValueId))
			return false;
		NvLayeredIndexableFeatureValueLangValueId castOther = (NvLayeredIndexableFeatureValueLangValueId) other;

		return (this.getIdFeatureValue() == castOther.getIdFeatureValue()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFeatureValue();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
