package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvLayeredProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "nv_layered_product_attribute", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = { "id_attribute_group",
		"id_attribute", "id_product", "id_shop" }))
public class NvLayeredProductAttribute implements java.io.Serializable {

	private NvLayeredProductAttributeId id;
	private int idAttributeGroup;

	public NvLayeredProductAttribute() {
	}

	public NvLayeredProductAttribute(NvLayeredProductAttributeId id, int idAttributeGroup) {
		this.id = id;
		this.idAttributeGroup = idAttributeGroup;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttribute", column = @Column(name = "id_attribute", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvLayeredProductAttributeId getId() {
		return this.id;
	}

	public void setId(NvLayeredProductAttributeId id) {
		this.id = id;
	}

	@Column(name = "id_attribute_group", nullable = false)
	public int getIdAttributeGroup() {
		return this.idAttributeGroup;
	}

	public void setIdAttributeGroup(int idAttributeGroup) {
		this.idAttributeGroup = idAttributeGroup;
	}

}
