package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvLangShop generated by hbm2java
 */
@Entity
@Table(name = "nv_lang_shop", catalog = "NVPrestashop")
public class NvLangShop implements java.io.Serializable {

	private NvLangShopId id;

	public NvLangShop() {
	}

	public NvLangShop(NvLangShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvLangShopId getId() {
		return this.id;
	}

	public void setId(NvLangShopId id) {
		this.id = id;
	}

}
