package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvLinksmenutopLang generated by hbm2java
 */
@Entity
@Table(name = "nv_linksmenutop_lang", catalog = "NVPrestashop")
public class NvLinksmenutopLang implements java.io.Serializable {

	private NvLinksmenutopLangId id;

	public NvLinksmenutopLang() {
	}

	public NvLinksmenutopLang(NvLinksmenutopLangId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idLinksmenutop", column = @Column(name = "id_linksmenutop", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "label", column = @Column(name = "label", nullable = false, length = 128)),
			@AttributeOverride(name = "link", column = @Column(name = "link", nullable = false, length = 128)) })
	public NvLinksmenutopLangId getId() {
		return this.id;
	}

	public void setId(NvLinksmenutopLangId id) {
		this.id = id;
	}

}
