package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvLoyalty generated by hbm2java
 */
@Entity
@Table(name = "nv_loyalty", catalog = "NVPrestashop")
public class NvLoyalty implements java.io.Serializable {

	private Integer idLoyalty;
	private int idLoyaltyState;
	private int idCustomer;
	private Integer idOrder;
	private Integer idCartRule;
	private int points;
	private Date dateAdd;
	private Date dateUpd;

	public NvLoyalty() {
	}

	public NvLoyalty(int idLoyaltyState, int idCustomer, int points, Date dateAdd, Date dateUpd) {
		this.idLoyaltyState = idLoyaltyState;
		this.idCustomer = idCustomer;
		this.points = points;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvLoyalty(int idLoyaltyState, int idCustomer, Integer idOrder, Integer idCartRule, int points, Date dateAdd, Date dateUpd) {
		this.idLoyaltyState = idLoyaltyState;
		this.idCustomer = idCustomer;
		this.idOrder = idOrder;
		this.idCartRule = idCartRule;
		this.points = points;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_loyalty", unique = true, nullable = false)
	public Integer getIdLoyalty() {
		return this.idLoyalty;
	}

	public void setIdLoyalty(Integer idLoyalty) {
		this.idLoyalty = idLoyalty;
	}

	@Column(name = "id_loyalty_state", nullable = false)
	public int getIdLoyaltyState() {
		return this.idLoyaltyState;
	}

	public void setIdLoyaltyState(int idLoyaltyState) {
		this.idLoyaltyState = idLoyaltyState;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_order")
	public Integer getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(Integer idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "id_cart_rule")
	public Integer getIdCartRule() {
		return this.idCartRule;
	}

	public void setIdCartRule(Integer idCartRule) {
		this.idCartRule = idCartRule;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
