package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvManufacturer generated by hbm2java
 */
@Entity
@Table(name = "nv_manufacturer", catalog = "NVPrestashop")
public class NvManufacturer implements java.io.Serializable {

	private Integer idManufacturer;
	private String name;
	private Date dateAdd;
	private Date dateUpd;
	private boolean active;

	public NvManufacturer() {
	}

	public NvManufacturer(String name, Date dateAdd, Date dateUpd, boolean active) {
		this.name = name;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_manufacturer", unique = true, nullable = false)
	public Integer getIdManufacturer() {
		return this.idManufacturer;
	}

	public void setIdManufacturer(Integer idManufacturer) {
		this.idManufacturer = idManufacturer;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
