package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvManufacturerLang generated by hbm2java
 */
@Entity
@Table(name = "nv_manufacturer_lang", catalog = "NVPrestashop")
public class NvManufacturerLang implements java.io.Serializable {

	private NvManufacturerLangId id;
	private String description;
	private String shortDescription;
	private String metaTitle;
	private String metaKeywords;
	private String metaDescription;

	public NvManufacturerLang() {
	}

	public NvManufacturerLang(NvManufacturerLangId id) {
		this.id = id;
	}

	public NvManufacturerLang(NvManufacturerLangId id, String description, String shortDescription, String metaTitle, String metaKeywords,
					String metaDescription) {
		this.id = id;
		this.description = description;
		this.shortDescription = shortDescription;
		this.metaTitle = metaTitle;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idManufacturer", column = @Column(name = "id_manufacturer", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvManufacturerLangId getId() {
		return this.id;
	}

	public void setId(NvManufacturerLangId id) {
		this.id = id;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "short_description", length = 65535)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "meta_title", length = 128)
	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	@Column(name = "meta_keywords")
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "meta_description")
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

}
