package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvMeta generated by hbm2java
 */
@Entity
@Table(name = "nv_meta", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "page"))
public class NvMeta implements java.io.Serializable {

	private Integer idMeta;
	private String page;
	private boolean configurable;

	public NvMeta() {
	}

	public NvMeta(String page, boolean configurable) {
		this.page = page;
		this.configurable = configurable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_meta", unique = true, nullable = false)
	public Integer getIdMeta() {
		return this.idMeta;
	}

	public void setIdMeta(Integer idMeta) {
		this.idMeta = idMeta;
	}

	@Column(name = "page", unique = true, nullable = false, length = 64)
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	@Column(name = "configurable", nullable = false)
	public boolean isConfigurable() {
		return this.configurable;
	}

	public void setConfigurable(boolean configurable) {
		this.configurable = configurable;
	}

}
