package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvMetaLang generated by hbm2java
 */
@Entity
@Table(name = "nv_meta_lang", catalog = "NVPrestashop")
public class NvMetaLang implements java.io.Serializable {

	private NvMetaLangId id;
	private String title;
	private String description;
	private String keywords;
	private String urlRewrite;

	public NvMetaLang() {
	}

	public NvMetaLang(NvMetaLangId id, String urlRewrite) {
		this.id = id;
		this.urlRewrite = urlRewrite;
	}

	public NvMetaLang(NvMetaLangId id, String title, String description, String keywords, String urlRewrite) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.keywords = keywords;
		this.urlRewrite = urlRewrite;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idMeta", column = @Column(name = "id_meta", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvMetaLangId getId() {
		return this.id;
	}

	public void setId(NvMetaLangId id) {
		this.id = id;
	}

	@Column(name = "title", length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "keywords")
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "url_rewrite", nullable = false, length = 254)
	public String getUrlRewrite() {
		return this.urlRewrite;
	}

	public void setUrlRewrite(String urlRewrite) {
		this.urlRewrite = urlRewrite;
	}

}
