package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvMessageReadedId generated by hbm2java
 */
@Embeddable
public class NvMessageReadedId implements java.io.Serializable {

	private int idMessage;
	private int idEmployee;

	public NvMessageReadedId() {
	}

	public NvMessageReadedId(int idMessage, int idEmployee) {
		this.idMessage = idMessage;
		this.idEmployee = idEmployee;
	}

	@Column(name = "id_message", nullable = false)
	public int getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(int idMessage) {
		this.idMessage = idMessage;
	}

	@Column(name = "id_employee", nullable = false)
	public int getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(int idEmployee) {
		this.idEmployee = idEmployee;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvMessageReadedId))
			return false;
		NvMessageReadedId castOther = (NvMessageReadedId) other;

		return (this.getIdMessage() == castOther.getIdMessage()) && (this.getIdEmployee() == castOther.getIdEmployee());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMessage();
		result = 37 * result + this.getIdEmployee();
		return result;
	}

}
