package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvModuleCurrency generated by hbm2java
 */
@Entity
@Table(name = "nv_module_currency", catalog = "NVPrestashop")
public class NvModuleCurrency implements java.io.Serializable {

	private NvModuleCurrencyId id;

	public NvModuleCurrency() {
	}

	public NvModuleCurrency(NvModuleCurrencyId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idCurrency", column = @Column(name = "id_currency", nullable = false)) })
	public NvModuleCurrencyId getId() {
		return this.id;
	}

	public void setId(NvModuleCurrencyId id) {
		this.id = id;
	}

}
