package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvModuleShop generated by hbm2java
 */
@Entity
@Table(name = "nv_module_shop", catalog = "NVPrestashop")
public class NvModuleShop implements java.io.Serializable {

	private NvModuleShopId id;
	private boolean enableDevice;

	public NvModuleShop() {
	}

	public NvModuleShop(NvModuleShopId id, boolean enableDevice) {
		this.id = id;
		this.enableDevice = enableDevice;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvModuleShopId getId() {
		return this.id;
	}

	public void setId(NvModuleShopId id) {
		this.id = id;
	}

	@Column(name = "enable_device", nullable = false)
	public boolean isEnableDevice() {
		return this.enableDevice;
	}

	public void setEnableDevice(boolean enableDevice) {
		this.enableDevice = enableDevice;
	}

}
