package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvModuleCountry generated by hbm2java
 */
@Entity
@Table(name = "nv_module_country", catalog = "NVPrestashop")
public class NvModuleCountry implements java.io.Serializable {

	private NvModuleCountryId id;

	public NvModuleCountry() {
	}

	public NvModuleCountry(NvModuleCountryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idCountry", column = @Column(name = "id_country", nullable = false)) })
	public NvModuleCountryId getId() {
		return this.id;
	}

	public void setId(NvModuleCountryId id) {
		this.id = id;
	}

}
