package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvModuleGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_module_group", catalog = "NVPrestashop")
public class NvModuleGroup implements java.io.Serializable {

	private NvModuleGroupId id;

	public NvModuleGroup() {
	}

	public NvModuleGroup(NvModuleGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)) })
	public NvModuleGroupId getId() {
		return this.id;
	}

	public void setId(NvModuleGroupId id) {
		this.id = id;
	}

}
