package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvModuleAccess generated by hbm2java
 */
@Entity
@Table(name = "nv_module_access", catalog = "NVPrestashop")
public class NvModuleAccess implements java.io.Serializable {

	private NvModuleAccessId id;
	private boolean view;
	private boolean configure;
	private boolean uninstall;

	public NvModuleAccess() {
	}

	public NvModuleAccess(NvModuleAccessId id, boolean view, boolean configure, boolean uninstall) {
		this.id = id;
		this.view = view;
		this.configure = configure;
		this.uninstall = uninstall;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProfile", column = @Column(name = "id_profile", nullable = false)),
			@AttributeOverride(name = "idModule", column = @Column(name = "id_module", nullable = false)) })
	public NvModuleAccessId getId() {
		return this.id;
	}

	public void setId(NvModuleAccessId id) {
		this.id = id;
	}

	@Column(name = "view", nullable = false)
	public boolean isView() {
		return this.view;
	}

	public void setView(boolean view) {
		this.view = view;
	}

	@Column(name = "configure", nullable = false)
	public boolean isConfigure() {
		return this.configure;
	}

	public void setConfigure(boolean configure) {
		this.configure = configure;
	}

	@Column(name = "uninstall", nullable = false)
	public boolean isUninstall() {
		return this.uninstall;
	}

	public void setUninstall(boolean uninstall) {
		this.uninstall = uninstall;
	}

}
