package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvModuleAccessId generated by hbm2java
 */
@Embeddable
public class NvModuleAccessId implements java.io.Serializable {

	private int idProfile;
	private int idModule;

	public NvModuleAccessId() {
	}

	public NvModuleAccessId(int idProfile, int idModule) {
		this.idProfile = idProfile;
		this.idModule = idModule;
	}

	@Column(name = "id_profile", nullable = false)
	public int getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(int idProfile) {
		this.idProfile = idProfile;
	}

	@Column(name = "id_module", nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvModuleAccessId))
			return false;
		NvModuleAccessId castOther = (NvModuleAccessId) other;

		return (this.getIdProfile() == castOther.getIdProfile()) && (this.getIdModule() == castOther.getIdModule());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProfile();
		result = 37 * result + this.getIdModule();
		return result;
	}

}
