package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvNewsletter generated by hbm2java
 */
@Entity
@Table(name = "nv_newsletter", catalog = "NVPrestashop")
public class NvNewsletter implements java.io.Serializable {

	private Integer id;
	private int idShop;
	private int idShopGroup;
	private String email;
	private Date newsletterDateAdd;
	private String ipRegistrationNewsletter;
	private String httpReferer;
	private boolean active;

	public NvNewsletter() {
	}

	public NvNewsletter(int idShop, int idShopGroup, String email, String ipRegistrationNewsletter, boolean active) {
		this.idShop = idShop;
		this.idShopGroup = idShopGroup;
		this.email = email;
		this.ipRegistrationNewsletter = ipRegistrationNewsletter;
		this.active = active;
	}

	public NvNewsletter(int idShop, int idShopGroup, String email, Date newsletterDateAdd, String ipRegistrationNewsletter, String httpReferer, boolean active) {
		this.idShop = idShop;
		this.idShopGroup = idShopGroup;
		this.email = email;
		this.newsletterDateAdd = newsletterDateAdd;
		this.ipRegistrationNewsletter = ipRegistrationNewsletter;
		this.httpReferer = httpReferer;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_shop_group", nullable = false)
	public int getIdShopGroup() {
		return this.idShopGroup;
	}

	public void setIdShopGroup(int idShopGroup) {
		this.idShopGroup = idShopGroup;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "newsletter_date_add", length = 0)
	public Date getNewsletterDateAdd() {
		return this.newsletterDateAdd;
	}

	public void setNewsletterDateAdd(Date newsletterDateAdd) {
		this.newsletterDateAdd = newsletterDateAdd;
	}

	@Column(name = "ip_registration_newsletter", nullable = false, length = 15)
	public String getIpRegistrationNewsletter() {
		return this.ipRegistrationNewsletter;
	}

	public void setIpRegistrationNewsletter(String ipRegistrationNewsletter) {
		this.ipRegistrationNewsletter = ipRegistrationNewsletter;
	}

	@Column(name = "http_referer")
	public String getHttpReferer() {
		return this.httpReferer;
	}

	public void setHttpReferer(String httpReferer) {
		this.httpReferer = httpReferer;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
