package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvPagenotfound generated by hbm2java
 */
@Entity
@Table(name = "nv_pagenotfound", catalog = "NVPrestashop")
public class NvPagenotfound implements java.io.Serializable {

	private Integer idPagenotfound;
	private int idShop;
	private int idShopGroup;
	private String requestUri;
	private String httpReferer;
	private Date dateAdd;

	public NvPagenotfound() {
	}

	public NvPagenotfound(int idShop, int idShopGroup, String requestUri, String httpReferer, Date dateAdd) {
		this.idShop = idShop;
		this.idShopGroup = idShopGroup;
		this.requestUri = requestUri;
		this.httpReferer = httpReferer;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_pagenotfound", unique = true, nullable = false)
	public Integer getIdPagenotfound() {
		return this.idPagenotfound;
	}

	public void setIdPagenotfound(Integer idPagenotfound) {
		this.idPagenotfound = idPagenotfound;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_shop_group", nullable = false)
	public int getIdShopGroup() {
		return this.idShopGroup;
	}

	public void setIdShopGroup(int idShopGroup) {
		this.idShopGroup = idShopGroup;
	}

	@Column(name = "request_uri", nullable = false, length = 256)
	public String getRequestUri() {
		return this.requestUri;
	}

	public void setRequestUri(String requestUri) {
		this.requestUri = requestUri;
	}

	@Column(name = "http_referer", nullable = false, length = 256)
	public String getHttpReferer() {
		return this.httpReferer;
	}

	public void setHttpReferer(String httpReferer) {
		this.httpReferer = httpReferer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
