package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvPayuOrder generated by hbm2java
 */
@Entity
@Table(name = "nv_payu_order", catalog = "NVPrestashop")
public class NvPayuOrder implements java.io.Serializable {

	private int idOrder;
	private String idTransaction;
	private int paymentMethod;
	private String paymentStatus;
	private Date orderDate;
	private String paymentRequest;
	private String paymentResponse;

	public NvPayuOrder() {
	}

	public NvPayuOrder(int idOrder, String idTransaction, int paymentMethod, String paymentStatus, Date orderDate) {
		this.idOrder = idOrder;
		this.idTransaction = idTransaction;
		this.paymentMethod = paymentMethod;
		this.paymentStatus = paymentStatus;
		this.orderDate = orderDate;
	}

	public NvPayuOrder(int idOrder, String idTransaction, int paymentMethod, String paymentStatus, Date orderDate, String paymentRequest, String paymentResponse) {
		this.idOrder = idOrder;
		this.idTransaction = idTransaction;
		this.paymentMethod = paymentMethod;
		this.paymentStatus = paymentStatus;
		this.orderDate = orderDate;
		this.paymentRequest = paymentRequest;
		this.paymentResponse = paymentResponse;
	}

	@Id
	@Column(name = "id_order", unique = true, nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "id_transaction", nullable = false)
	public String getIdTransaction() {
		return this.idTransaction;
	}

	public void setIdTransaction(String idTransaction) {
		this.idTransaction = idTransaction;
	}

	@Column(name = "payment_method", nullable = false)
	public int getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(int paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "payment_status", nullable = false)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 0)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "payment_request", length = 65535)
	public String getPaymentRequest() {
		return this.paymentRequest;
	}

	public void setPaymentRequest(String paymentRequest) {
		this.paymentRequest = paymentRequest;
	}

	@Column(name = "payment_response", length = 65535)
	public String getPaymentResponse() {
		return this.paymentResponse;
	}

	public void setPaymentResponse(String paymentResponse) {
		this.paymentResponse = paymentResponse;
	}

}
