package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductTag generated by hbm2java
 */
@Entity
@Table(name = "nv_product_tag", catalog = "NVPrestashop")
public class NvProductTag implements java.io.Serializable {

	private NvProductTagId id;
	private int idLang;

	public NvProductTag() {
	}

	public NvProductTag(NvProductTagId id, int idLang) {
		this.id = id;
		this.idLang = idLang;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idTag", column = @Column(name = "id_tag", nullable = false)) })
	public NvProductTagId getId() {
		return this.id;
	}

	public void setId(NvProductTagId id) {
		this.id = id;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

}
