package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductGroupReductionCache generated by hbm2java
 */
@Entity
@Table(name = "nv_product_group_reduction_cache", catalog = "NVPrestashop")
public class NvProductGroupReductionCache implements java.io.Serializable {

	private NvProductGroupReductionCacheId id;
	private BigDecimal reduction;

	public NvProductGroupReductionCache() {
	}

	public NvProductGroupReductionCache(NvProductGroupReductionCacheId id, BigDecimal reduction) {
		this.id = id;
		this.reduction = reduction;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)) })
	public NvProductGroupReductionCacheId getId() {
		return this.id;
	}

	public void setId(NvProductGroupReductionCacheId id) {
		this.id = id;
	}

	@Column(name = "reduction", nullable = false, precision = 4, scale = 3)
	public BigDecimal getReduction() {
		return this.reduction;
	}

	public void setReduction(BigDecimal reduction) {
		this.reduction = reduction;
	}

}
