package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * NvProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "nv_product_attribute", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = { "id_product", "default_on" }))
public class NvProductAttribute implements java.io.Serializable {

	private Integer idProductAttribute;
	private int idProduct;
	private String reference;
	private String supplierReference;
	private String location;
	private String ean13;
	private String upc;
	private BigDecimal wholesalePrice;
	private BigDecimal price;
	private BigDecimal ecotax;
	private int quantity;
	private BigDecimal weight;
	private BigDecimal unitPriceImpact;
	private Boolean defaultOn;
	private int minimalQuantity;
	private Date availableDate;

	public NvProductAttribute() {
	}

	public NvProductAttribute(int idProduct, BigDecimal wholesalePrice, BigDecimal price, BigDecimal ecotax, int quantity, BigDecimal weight,
					BigDecimal unitPriceImpact, int minimalQuantity, Date availableDate) {
		this.idProduct = idProduct;
		this.wholesalePrice = wholesalePrice;
		this.price = price;
		this.ecotax = ecotax;
		this.quantity = quantity;
		this.weight = weight;
		this.unitPriceImpact = unitPriceImpact;
		this.minimalQuantity = minimalQuantity;
		this.availableDate = availableDate;
	}

	public NvProductAttribute(int idProduct, String reference, String supplierReference, String location, String ean13, String upc, BigDecimal wholesalePrice,
					BigDecimal price, BigDecimal ecotax, int quantity, BigDecimal weight, BigDecimal unitPriceImpact, Boolean defaultOn, int minimalQuantity,
					Date availableDate) {
		this.idProduct = idProduct;
		this.reference = reference;
		this.supplierReference = supplierReference;
		this.location = location;
		this.ean13 = ean13;
		this.upc = upc;
		this.wholesalePrice = wholesalePrice;
		this.price = price;
		this.ecotax = ecotax;
		this.quantity = quantity;
		this.weight = weight;
		this.unitPriceImpact = unitPriceImpact;
		this.defaultOn = defaultOn;
		this.minimalQuantity = minimalQuantity;
		this.availableDate = availableDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_product_attribute", unique = true, nullable = false)
	public Integer getIdProductAttribute() {
		return this.idProductAttribute;
	}

	public void setIdProductAttribute(Integer idProductAttribute) {
		this.idProductAttribute = idProductAttribute;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "reference", length = 32)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "supplier_reference", length = 32)
	public String getSupplierReference() {
		return this.supplierReference;
	}

	public void setSupplierReference(String supplierReference) {
		this.supplierReference = supplierReference;
	}

	@Column(name = "location", length = 64)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "ean13", length = 13)
	public String getEan13() {
		return this.ean13;
	}

	public void setEan13(String ean13) {
		this.ean13 = ean13;
	}

	@Column(name = "upc", length = 12)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "wholesale_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getWholesalePrice() {
		return this.wholesalePrice;
	}

	public void setWholesalePrice(BigDecimal wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	@Column(name = "price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "ecotax", nullable = false, precision = 17, scale = 6)
	public BigDecimal getEcotax() {
		return this.ecotax;
	}

	public void setEcotax(BigDecimal ecotax) {
		this.ecotax = ecotax;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "weight", nullable = false, precision = 20, scale = 6)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "unit_price_impact", nullable = false, precision = 20, scale = 6)
	public BigDecimal getUnitPriceImpact() {
		return this.unitPriceImpact;
	}

	public void setUnitPriceImpact(BigDecimal unitPriceImpact) {
		this.unitPriceImpact = unitPriceImpact;
	}

	@Column(name = "default_on")
	public Boolean getDefaultOn() {
		return this.defaultOn;
	}

	public void setDefaultOn(Boolean defaultOn) {
		this.defaultOn = defaultOn;
	}

	@Column(name = "minimal_quantity", nullable = false)
	public int getMinimalQuantity() {
		return this.minimalQuantity;
	}

	public void setMinimalQuantity(int minimalQuantity) {
		this.minimalQuantity = minimalQuantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "available_date", nullable = false, length = 0)
	public Date getAvailableDate() {
		return this.availableDate;
	}

	public void setAvailableDate(Date availableDate) {
		this.availableDate = availableDate;
	}

}
