package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductCommentGradeId generated by hbm2java
 */
@Embeddable
public class NvProductCommentGradeId implements java.io.Serializable {

	private int idProductComment;
	private int idProductCommentCriterion;

	public NvProductCommentGradeId() {
	}

	public NvProductCommentGradeId(int idProductComment, int idProductCommentCriterion) {
		this.idProductComment = idProductComment;
		this.idProductCommentCriterion = idProductCommentCriterion;
	}

	@Column(name = "id_product_comment", nullable = false)
	public int getIdProductComment() {
		return this.idProductComment;
	}

	public void setIdProductComment(int idProductComment) {
		this.idProductComment = idProductComment;
	}

	@Column(name = "id_product_comment_criterion", nullable = false)
	public int getIdProductCommentCriterion() {
		return this.idProductCommentCriterion;
	}

	public void setIdProductCommentCriterion(int idProductCommentCriterion) {
		this.idProductCommentCriterion = idProductCommentCriterion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductCommentGradeId))
			return false;
		NvProductCommentGradeId castOther = (NvProductCommentGradeId) other;

		return (this.getIdProductComment() == castOther.getIdProductComment())
						&& (this.getIdProductCommentCriterion() == castOther.getIdProductCommentCriterion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductComment();
		result = 37 * result + this.getIdProductCommentCriterion();
		return result;
	}

}
