package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductLang generated by hbm2java
 */
@Entity
@Table(name = "nv_product_lang", catalog = "NVPrestashop")
public class NvProductLang implements java.io.Serializable {

	private NvProductLangId id;
	private String description;
	private String descriptionShort;
	private String linkRewrite;
	private String metaDescription;
	private String metaKeywords;
	private String metaTitle;
	private String name;
	private String availableNow;
	private String availableLater;

	public NvProductLang() {
	}

	public NvProductLang(NvProductLangId id, String linkRewrite, String name) {
		this.id = id;
		this.linkRewrite = linkRewrite;
		this.name = name;
	}

	public NvProductLang(NvProductLangId id, String description, String descriptionShort, String linkRewrite, String metaDescription, String metaKeywords,
					String metaTitle, String name, String availableNow, String availableLater) {
		this.id = id;
		this.description = description;
		this.descriptionShort = descriptionShort;
		this.linkRewrite = linkRewrite;
		this.metaDescription = metaDescription;
		this.metaKeywords = metaKeywords;
		this.metaTitle = metaTitle;
		this.name = name;
		this.availableNow = availableNow;
		this.availableLater = availableLater;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvProductLangId getId() {
		return this.id;
	}

	public void setId(NvProductLangId id) {
		this.id = id;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "description_short", length = 65535)
	public String getDescriptionShort() {
		return this.descriptionShort;
	}

	public void setDescriptionShort(String descriptionShort) {
		this.descriptionShort = descriptionShort;
	}

	@Column(name = "link_rewrite", nullable = false, length = 128)
	public String getLinkRewrite() {
		return this.linkRewrite;
	}

	public void setLinkRewrite(String linkRewrite) {
		this.linkRewrite = linkRewrite;
	}

	@Column(name = "meta_description")
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	@Column(name = "meta_keywords")
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "meta_title", length = 128)
	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "available_now")
	public String getAvailableNow() {
		return this.availableNow;
	}

	public void setAvailableNow(String availableNow) {
		this.availableNow = availableNow;
	}

	@Column(name = "available_later")
	public String getAvailableLater() {
		return this.availableLater;
	}

	public void setAvailableLater(String availableLater) {
		this.availableLater = availableLater;
	}

}
