package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvProduct generated by hbm2java
 */
@Entity
@Table(name = "nv_product", catalog = "NVPrestashop")
public class NvProduct implements java.io.Serializable {

	private Integer idProduct;
	private Integer idSupplier;
	private Integer idManufacturer;
	private Integer idCategoryDefault;
	private int idShopDefault;
	private int idTaxRulesGroup;
	private boolean onSale;
	private boolean onlineOnly;
	private String ean13;
	private String upc;
	private BigDecimal ecotax;
	private int quantity;
	private int minimalQuantity;
	private BigDecimal price;
	private BigDecimal wholesalePrice;
	private String unity;
	private BigDecimal unitPriceRatio;
	private BigDecimal additionalShippingCost;
	private String reference;
	private String supplierReference;
	private String location;
	private BigDecimal width;
	private BigDecimal height;
	private BigDecimal depth;
	private BigDecimal weight;
	private int outOfStock;
	private Boolean quantityDiscount;
	private byte customizable;
	private byte uploadableFiles;
	private byte textFields;
	private boolean active;
	private String redirectType;
	private int idProductRedirected;
	private boolean availableForOrder;
	private Date availableDate;
	private String condition;
	private boolean showPrice;
	private boolean indexed;
	private String visibility;
	private boolean cacheIsPack;
	private boolean cacheHasAttachments;
	private boolean isVirtual;
	private Integer cacheDefaultAttribute;
	private Date dateAdd;
	private Date dateUpd;
	private boolean advancedStockManagement;
	private int packStockType;

	public NvProduct() {
	}

	public NvProduct(int idShopDefault, int idTaxRulesGroup, boolean onSale, boolean onlineOnly, BigDecimal ecotax, int quantity, int minimalQuantity,
					BigDecimal price, BigDecimal wholesalePrice, BigDecimal unitPriceRatio, BigDecimal additionalShippingCost, BigDecimal width,
					BigDecimal height, BigDecimal depth, BigDecimal weight, int outOfStock, byte customizable, byte uploadableFiles, byte textFields,
					boolean active, String redirectType, int idProductRedirected, boolean availableForOrder, Date availableDate, String condition,
					boolean showPrice, boolean indexed, String visibility, boolean cacheIsPack, boolean cacheHasAttachments, boolean isVirtual, Date dateAdd,
					Date dateUpd, boolean advancedStockManagement, int packStockType) {
		this.idShopDefault = idShopDefault;
		this.idTaxRulesGroup = idTaxRulesGroup;
		this.onSale = onSale;
		this.onlineOnly = onlineOnly;
		this.ecotax = ecotax;
		this.quantity = quantity;
		this.minimalQuantity = minimalQuantity;
		this.price = price;
		this.wholesalePrice = wholesalePrice;
		this.unitPriceRatio = unitPriceRatio;
		this.additionalShippingCost = additionalShippingCost;
		this.width = width;
		this.height = height;
		this.depth = depth;
		this.weight = weight;
		this.outOfStock = outOfStock;
		this.customizable = customizable;
		this.uploadableFiles = uploadableFiles;
		this.textFields = textFields;
		this.active = active;
		this.redirectType = redirectType;
		this.idProductRedirected = idProductRedirected;
		this.availableForOrder = availableForOrder;
		this.availableDate = availableDate;
		this.condition = condition;
		this.showPrice = showPrice;
		this.indexed = indexed;
		this.visibility = visibility;
		this.cacheIsPack = cacheIsPack;
		this.cacheHasAttachments = cacheHasAttachments;
		this.isVirtual = isVirtual;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.advancedStockManagement = advancedStockManagement;
		this.packStockType = packStockType;
	}

	public NvProduct(Integer idSupplier, Integer idManufacturer, Integer idCategoryDefault, int idShopDefault, int idTaxRulesGroup, boolean onSale,
					boolean onlineOnly, String ean13, String upc, BigDecimal ecotax, int quantity, int minimalQuantity, BigDecimal price,
					BigDecimal wholesalePrice, String unity, BigDecimal unitPriceRatio, BigDecimal additionalShippingCost, String reference,
					String supplierReference, String location, BigDecimal width, BigDecimal height, BigDecimal depth, BigDecimal weight, int outOfStock,
					Boolean quantityDiscount, byte customizable, byte uploadableFiles, byte textFields, boolean active, String redirectType,
					int idProductRedirected, boolean availableForOrder, Date availableDate, String condition, boolean showPrice, boolean indexed,
					String visibility, boolean cacheIsPack, boolean cacheHasAttachments, boolean isVirtual, Integer cacheDefaultAttribute, Date dateAdd,
					Date dateUpd, boolean advancedStockManagement, int packStockType) {
		this.idSupplier = idSupplier;
		this.idManufacturer = idManufacturer;
		this.idCategoryDefault = idCategoryDefault;
		this.idShopDefault = idShopDefault;
		this.idTaxRulesGroup = idTaxRulesGroup;
		this.onSale = onSale;
		this.onlineOnly = onlineOnly;
		this.ean13 = ean13;
		this.upc = upc;
		this.ecotax = ecotax;
		this.quantity = quantity;
		this.minimalQuantity = minimalQuantity;
		this.price = price;
		this.wholesalePrice = wholesalePrice;
		this.unity = unity;
		this.unitPriceRatio = unitPriceRatio;
		this.additionalShippingCost = additionalShippingCost;
		this.reference = reference;
		this.supplierReference = supplierReference;
		this.location = location;
		this.width = width;
		this.height = height;
		this.depth = depth;
		this.weight = weight;
		this.outOfStock = outOfStock;
		this.quantityDiscount = quantityDiscount;
		this.customizable = customizable;
		this.uploadableFiles = uploadableFiles;
		this.textFields = textFields;
		this.active = active;
		this.redirectType = redirectType;
		this.idProductRedirected = idProductRedirected;
		this.availableForOrder = availableForOrder;
		this.availableDate = availableDate;
		this.condition = condition;
		this.showPrice = showPrice;
		this.indexed = indexed;
		this.visibility = visibility;
		this.cacheIsPack = cacheIsPack;
		this.cacheHasAttachments = cacheHasAttachments;
		this.isVirtual = isVirtual;
		this.cacheDefaultAttribute = cacheDefaultAttribute;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.advancedStockManagement = advancedStockManagement;
		this.packStockType = packStockType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_product", unique = true, nullable = false)
	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_supplier")
	public Integer getIdSupplier() {
		return this.idSupplier;
	}

	public void setIdSupplier(Integer idSupplier) {
		this.idSupplier = idSupplier;
	}

	@Column(name = "id_manufacturer")
	public Integer getIdManufacturer() {
		return this.idManufacturer;
	}

	public void setIdManufacturer(Integer idManufacturer) {
		this.idManufacturer = idManufacturer;
	}

	@Column(name = "id_category_default")
	public Integer getIdCategoryDefault() {
		return this.idCategoryDefault;
	}

	public void setIdCategoryDefault(Integer idCategoryDefault) {
		this.idCategoryDefault = idCategoryDefault;
	}

	@Column(name = "id_shop_default", nullable = false)
	public int getIdShopDefault() {
		return this.idShopDefault;
	}

	public void setIdShopDefault(int idShopDefault) {
		this.idShopDefault = idShopDefault;
	}

	@Column(name = "id_tax_rules_group", nullable = false)
	public int getIdTaxRulesGroup() {
		return this.idTaxRulesGroup;
	}

	public void setIdTaxRulesGroup(int idTaxRulesGroup) {
		this.idTaxRulesGroup = idTaxRulesGroup;
	}

	@Column(name = "on_sale", nullable = false)
	public boolean isOnSale() {
		return this.onSale;
	}

	public void setOnSale(boolean onSale) {
		this.onSale = onSale;
	}

	@Column(name = "online_only", nullable = false)
	public boolean isOnlineOnly() {
		return this.onlineOnly;
	}

	public void setOnlineOnly(boolean onlineOnly) {
		this.onlineOnly = onlineOnly;
	}

	@Column(name = "ean13", length = 13)
	public String getEan13() {
		return this.ean13;
	}

	public void setEan13(String ean13) {
		this.ean13 = ean13;
	}

	@Column(name = "upc", length = 12)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "ecotax", nullable = false, precision = 17, scale = 6)
	public BigDecimal getEcotax() {
		return this.ecotax;
	}

	public void setEcotax(BigDecimal ecotax) {
		this.ecotax = ecotax;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "minimal_quantity", nullable = false)
	public int getMinimalQuantity() {
		return this.minimalQuantity;
	}

	public void setMinimalQuantity(int minimalQuantity) {
		this.minimalQuantity = minimalQuantity;
	}

	@Column(name = "price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "wholesale_price", nullable = false, precision = 20, scale = 6)
	public BigDecimal getWholesalePrice() {
		return this.wholesalePrice;
	}

	public void setWholesalePrice(BigDecimal wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	@Column(name = "unity")
	public String getUnity() {
		return this.unity;
	}

	public void setUnity(String unity) {
		this.unity = unity;
	}

	@Column(name = "unit_price_ratio", nullable = false, precision = 20, scale = 6)
	public BigDecimal getUnitPriceRatio() {
		return this.unitPriceRatio;
	}

	public void setUnitPriceRatio(BigDecimal unitPriceRatio) {
		this.unitPriceRatio = unitPriceRatio;
	}

	@Column(name = "additional_shipping_cost", nullable = false, precision = 20)
	public BigDecimal getAdditionalShippingCost() {
		return this.additionalShippingCost;
	}

	public void setAdditionalShippingCost(BigDecimal additionalShippingCost) {
		this.additionalShippingCost = additionalShippingCost;
	}

	@Column(name = "reference", length = 32)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "supplier_reference", length = 32)
	public String getSupplierReference() {
		return this.supplierReference;
	}

	public void setSupplierReference(String supplierReference) {
		this.supplierReference = supplierReference;
	}

	@Column(name = "location", length = 64)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "width", nullable = false, precision = 20, scale = 6)
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false, precision = 20, scale = 6)
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	@Column(name = "depth", nullable = false, precision = 20, scale = 6)
	public BigDecimal getDepth() {
		return this.depth;
	}

	public void setDepth(BigDecimal depth) {
		this.depth = depth;
	}

	@Column(name = "weight", nullable = false, precision = 20, scale = 6)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "out_of_stock", nullable = false)
	public int getOutOfStock() {
		return this.outOfStock;
	}

	public void setOutOfStock(int outOfStock) {
		this.outOfStock = outOfStock;
	}

	@Column(name = "quantity_discount")
	public Boolean getQuantityDiscount() {
		return this.quantityDiscount;
	}

	public void setQuantityDiscount(Boolean quantityDiscount) {
		this.quantityDiscount = quantityDiscount;
	}

	@Column(name = "customizable", nullable = false)
	public byte getCustomizable() {
		return this.customizable;
	}

	public void setCustomizable(byte customizable) {
		this.customizable = customizable;
	}

	@Column(name = "uploadable_files", nullable = false)
	public byte getUploadableFiles() {
		return this.uploadableFiles;
	}

	public void setUploadableFiles(byte uploadableFiles) {
		this.uploadableFiles = uploadableFiles;
	}

	@Column(name = "text_fields", nullable = false)
	public byte getTextFields() {
		return this.textFields;
	}

	public void setTextFields(byte textFields) {
		this.textFields = textFields;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "redirect_type", nullable = false, length = 3)
	public String getRedirectType() {
		return this.redirectType;
	}

	public void setRedirectType(String redirectType) {
		this.redirectType = redirectType;
	}

	@Column(name = "id_product_redirected", nullable = false)
	public int getIdProductRedirected() {
		return this.idProductRedirected;
	}

	public void setIdProductRedirected(int idProductRedirected) {
		this.idProductRedirected = idProductRedirected;
	}

	@Column(name = "available_for_order", nullable = false)
	public boolean isAvailableForOrder() {
		return this.availableForOrder;
	}

	public void setAvailableForOrder(boolean availableForOrder) {
		this.availableForOrder = availableForOrder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "available_date", nullable = false, length = 0)
	public Date getAvailableDate() {
		return this.availableDate;
	}

	public void setAvailableDate(Date availableDate) {
		this.availableDate = availableDate;
	}

	@Column(name = "condition", nullable = false, length = 11)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Column(name = "show_price", nullable = false)
	public boolean isShowPrice() {
		return this.showPrice;
	}

	public void setShowPrice(boolean showPrice) {
		this.showPrice = showPrice;
	}

	@Column(name = "indexed", nullable = false)
	public boolean isIndexed() {
		return this.indexed;
	}

	public void setIndexed(boolean indexed) {
		this.indexed = indexed;
	}

	@Column(name = "visibility", nullable = false, length = 7)
	public String getVisibility() {
		return this.visibility;
	}

	public void setVisibility(String visibility) {
		this.visibility = visibility;
	}

	@Column(name = "cache_is_pack", nullable = false)
	public boolean isCacheIsPack() {
		return this.cacheIsPack;
	}

	public void setCacheIsPack(boolean cacheIsPack) {
		this.cacheIsPack = cacheIsPack;
	}

	@Column(name = "cache_has_attachments", nullable = false)
	public boolean isCacheHasAttachments() {
		return this.cacheHasAttachments;
	}

	public void setCacheHasAttachments(boolean cacheHasAttachments) {
		this.cacheHasAttachments = cacheHasAttachments;
	}

	@Column(name = "is_virtual", nullable = false)
	public boolean isIsVirtual() {
		return this.isVirtual;
	}

	public void setIsVirtual(boolean isVirtual) {
		this.isVirtual = isVirtual;
	}

	@Column(name = "cache_default_attribute")
	public Integer getCacheDefaultAttribute() {
		return this.cacheDefaultAttribute;
	}

	public void setCacheDefaultAttribute(Integer cacheDefaultAttribute) {
		this.cacheDefaultAttribute = cacheDefaultAttribute;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Column(name = "advanced_stock_management", nullable = false)
	public boolean isAdvancedStockManagement() {
		return this.advancedStockManagement;
	}

	public void setAdvancedStockManagement(boolean advancedStockManagement) {
		this.advancedStockManagement = advancedStockManagement;
	}

	@Column(name = "pack_stock_type", nullable = false)
	public int getPackStockType() {
		return this.packStockType;
	}

	public void setPackStockType(int packStockType) {
		this.packStockType = packStockType;
	}

}
