package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductCommentCriterionCategoryId generated by hbm2java
 */
@Embeddable
public class NvProductCommentCriterionCategoryId implements java.io.Serializable {

	private int idProductCommentCriterion;
	private int idCategory;

	public NvProductCommentCriterionCategoryId() {
	}

	public NvProductCommentCriterionCategoryId(int idProductCommentCriterion, int idCategory) {
		this.idProductCommentCriterion = idProductCommentCriterion;
		this.idCategory = idCategory;
	}

	@Column(name = "id_product_comment_criterion", nullable = false)
	public int getIdProductCommentCriterion() {
		return this.idProductCommentCriterion;
	}

	public void setIdProductCommentCriterion(int idProductCommentCriterion) {
		this.idProductCommentCriterion = idProductCommentCriterion;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductCommentCriterionCategoryId))
			return false;
		NvProductCommentCriterionCategoryId castOther = (NvProductCommentCriterionCategoryId) other;

		return (this.getIdProductCommentCriterion() == castOther.getIdProductCommentCriterion()) && (this.getIdCategory() == castOther.getIdCategory());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductCommentCriterion();
		result = 37 * result + this.getIdCategory();
		return result;
	}

}
