package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvProductSupplier generated by hbm2java
 */
@Entity
@Table(name = "nv_product_supplier", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = { "id_product", "id_product_attribute",
		"id_supplier" }))
public class NvProductSupplier implements java.io.Serializable {

	private Integer idProductSupplier;
	private int idProduct;
	private int idProductAttribute;
	private int idSupplier;
	private String productSupplierReference;
	private BigDecimal productSupplierPriceTe;
	private int idCurrency;

	public NvProductSupplier() {
	}

	public NvProductSupplier(int idProduct, int idProductAttribute, int idSupplier, BigDecimal productSupplierPriceTe, int idCurrency) {
		this.idProduct = idProduct;
		this.idProductAttribute = idProductAttribute;
		this.idSupplier = idSupplier;
		this.productSupplierPriceTe = productSupplierPriceTe;
		this.idCurrency = idCurrency;
	}

	public NvProductSupplier(int idProduct, int idProductAttribute, int idSupplier, String productSupplierReference, BigDecimal productSupplierPriceTe,
					int idCurrency) {
		this.idProduct = idProduct;
		this.idProductAttribute = idProductAttribute;
		this.idSupplier = idSupplier;
		this.productSupplierReference = productSupplierReference;
		this.productSupplierPriceTe = productSupplierPriceTe;
		this.idCurrency = idCurrency;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_product_supplier", unique = true, nullable = false)
	public Integer getIdProductSupplier() {
		return this.idProductSupplier;
	}

	public void setIdProductSupplier(Integer idProductSupplier) {
		this.idProductSupplier = idProductSupplier;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_product_attribute", nullable = false)
	public int getIdProductAttribute() {
		return this.idProductAttribute;
	}

	public void setIdProductAttribute(int idProductAttribute) {
		this.idProductAttribute = idProductAttribute;
	}

	@Column(name = "id_supplier", nullable = false)
	public int getIdSupplier() {
		return this.idSupplier;
	}

	public void setIdSupplier(int idSupplier) {
		this.idSupplier = idSupplier;
	}

	@Column(name = "product_supplier_reference", length = 32)
	public String getProductSupplierReference() {
		return this.productSupplierReference;
	}

	public void setProductSupplierReference(String productSupplierReference) {
		this.productSupplierReference = productSupplierReference;
	}

	@Column(name = "product_supplier_price_te", nullable = false, precision = 20, scale = 6)
	public BigDecimal getProductSupplierPriceTe() {
		return this.productSupplierPriceTe;
	}

	public void setProductSupplierPriceTe(BigDecimal productSupplierPriceTe) {
		this.productSupplierPriceTe = productSupplierPriceTe;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

}
