package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCommentUsefulness generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment_usefulness", catalog = "NVPrestashop")
public class NvProductCommentUsefulness implements java.io.Serializable {

	private NvProductCommentUsefulnessId id;
	private boolean usefulness;

	public NvProductCommentUsefulness() {
	}

	public NvProductCommentUsefulness(NvProductCommentUsefulnessId id, boolean usefulness) {
		this.id = id;
		this.usefulness = usefulness;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProductComment", column = @Column(name = "id_product_comment", nullable = false)),
			@AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)) })
	public NvProductCommentUsefulnessId getId() {
		return this.id;
	}

	public void setId(NvProductCommentUsefulnessId id) {
		this.id = id;
	}

	@Column(name = "usefulness", nullable = false)
	public boolean isUsefulness() {
		return this.usefulness;
	}

	public void setUsefulness(boolean usefulness) {
		this.usefulness = usefulness;
	}

}
