package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductAttributeShopId generated by hbm2java
 */
@Embeddable
public class NvProductAttributeShopId implements java.io.Serializable {

	private int idProductAttribute;
	private int idShop;

	public NvProductAttributeShopId() {
	}

	public NvProductAttributeShopId(int idProductAttribute, int idShop) {
		this.idProductAttribute = idProductAttribute;
		this.idShop = idShop;
	}

	@Column(name = "id_product_attribute", nullable = false)
	public int getIdProductAttribute() {
		return this.idProductAttribute;
	}

	public void setIdProductAttribute(int idProductAttribute) {
		this.idProductAttribute = idProductAttribute;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductAttributeShopId))
			return false;
		NvProductAttributeShopId castOther = (NvProductAttributeShopId) other;

		return (this.getIdProductAttribute() == castOther.getIdProductAttribute()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductAttribute();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
