package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvProductSale generated by hbm2java
 */
@Entity
@Table(name = "nv_product_sale", catalog = "NVPrestashop")
public class NvProductSale implements java.io.Serializable {

	private int idProduct;
	private int quantity;
	private int saleNbr;
	private Date dateUpd;

	public NvProductSale() {
	}

	public NvProductSale(int idProduct, int quantity, int saleNbr, Date dateUpd) {
		this.idProduct = idProduct;
		this.quantity = quantity;
		this.saleNbr = saleNbr;
		this.dateUpd = dateUpd;
	}

	@Id
	@Column(name = "id_product", unique = true, nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "sale_nbr", nullable = false)
	public int getSaleNbr() {
		return this.saleNbr;
	}

	public void setSaleNbr(int saleNbr) {
		this.saleNbr = saleNbr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
