package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProfileLang generated by hbm2java
 */
@Entity
@Table(name = "nv_profile_lang", catalog = "NVPrestashop")
public class NvProfileLang implements java.io.Serializable {

	private NvProfileLangId id;
	private String name;

	public NvProfileLang() {
	}

	public NvProfileLang(NvProfileLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProfile", column = @Column(name = "id_profile", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvProfileLangId getId() {
		return this.id;
	}

	public void setId(NvProfileLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
