package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvProductComment generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment", catalog = "NVPrestashop")
public class NvProductComment implements java.io.Serializable {

	private Integer idProductComment;
	private int idProduct;
	private int idCustomer;
	private Integer idGuest;
	private String title;
	private String content;
	private String customerName;
	private float grade;
	private boolean validate;
	private boolean deleted;
	private Date dateAdd;

	public NvProductComment() {
	}

	public NvProductComment(int idProduct, int idCustomer, String content, float grade, boolean validate, boolean deleted, Date dateAdd) {
		this.idProduct = idProduct;
		this.idCustomer = idCustomer;
		this.content = content;
		this.grade = grade;
		this.validate = validate;
		this.deleted = deleted;
		this.dateAdd = dateAdd;
	}

	public NvProductComment(int idProduct, int idCustomer, Integer idGuest, String title, String content, String customerName, float grade, boolean validate,
					boolean deleted, Date dateAdd) {
		this.idProduct = idProduct;
		this.idCustomer = idCustomer;
		this.idGuest = idGuest;
		this.title = title;
		this.content = content;
		this.customerName = customerName;
		this.grade = grade;
		this.validate = validate;
		this.deleted = deleted;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_product_comment", unique = true, nullable = false)
	public Integer getIdProductComment() {
		return this.idProductComment;
	}

	public void setIdProductComment(Integer idProductComment) {
		this.idProductComment = idProductComment;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_guest")
	public Integer getIdGuest() {
		return this.idGuest;
	}

	public void setIdGuest(Integer idGuest) {
		this.idGuest = idGuest;
	}

	@Column(name = "title", length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "customer_name", length = 64)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "grade", nullable = false, precision = 12, scale = 0)
	public float getGrade() {
		return this.grade;
	}

	public void setGrade(float grade) {
		this.grade = grade;
	}

	@Column(name = "validate", nullable = false)
	public boolean isValidate() {
		return this.validate;
	}

	public void setValidate(boolean validate) {
		this.validate = validate;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
