package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductAttributeCombination generated by hbm2java
 */
@Entity
@Table(name = "nv_product_attribute_combination", catalog = "NVPrestashop")
public class NvProductAttributeCombination implements java.io.Serializable {

	private NvProductAttributeCombinationId id;

	public NvProductAttributeCombination() {
	}

	public NvProductAttributeCombination(NvProductAttributeCombinationId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttribute", column = @Column(name = "id_attribute", nullable = false)),
			@AttributeOverride(name = "idProductAttribute", column = @Column(name = "id_product_attribute", nullable = false)) })
	public NvProductAttributeCombinationId getId() {
		return this.id;
	}

	public void setId(NvProductAttributeCombinationId id) {
		this.id = id;
	}

}
