package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductLangId generated by hbm2java
 */
@Embeddable
public class NvProductLangId implements java.io.Serializable {

	private int idProduct;
	private int idShop;
	private int idLang;

	public NvProductLangId() {
	}

	public NvProductLangId(int idProduct, int idShop, int idLang) {
		this.idProduct = idProduct;
		this.idShop = idShop;
		this.idLang = idLang;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductLangId))
			return false;
		NvProductLangId castOther = (NvProductLangId) other;

		return (this.getIdProduct() == castOther.getIdProduct()) && (this.getIdShop() == castOther.getIdShop()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdShop();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
