package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductAttachmentId generated by hbm2java
 */
@Embeddable
public class NvProductAttachmentId implements java.io.Serializable {

	private int idProduct;
	private int idAttachment;

	public NvProductAttachmentId() {
	}

	public NvProductAttachmentId(int idProduct, int idAttachment) {
		this.idProduct = idProduct;
		this.idAttachment = idAttachment;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_attachment", nullable = false)
	public int getIdAttachment() {
		return this.idAttachment;
	}

	public void setIdAttachment(int idAttachment) {
		this.idAttachment = idAttachment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductAttachmentId))
			return false;
		NvProductAttachmentId castOther = (NvProductAttachmentId) other;

		return (this.getIdProduct() == castOther.getIdProduct()) && (this.getIdAttachment() == castOther.getIdAttachment());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdAttachment();
		return result;
	}

}
