package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCommentCriterionLang generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment_criterion_lang", catalog = "NVPrestashop")
public class NvProductCommentCriterionLang implements java.io.Serializable {

	private NvProductCommentCriterionLangId id;
	private String name;

	public NvProductCommentCriterionLang() {
	}

	public NvProductCommentCriterionLang(NvProductCommentCriterionLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProductCommentCriterion", column = @Column(name = "id_product_comment_criterion", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvProductCommentCriterionLangId getId() {
		return this.id;
	}

	public void setId(NvProductCommentCriterionLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
