package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCommentCriterionCategory generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment_criterion_category", catalog = "NVPrestashop")
public class NvProductCommentCriterionCategory implements java.io.Serializable {

	private NvProductCommentCriterionCategoryId id;

	public NvProductCommentCriterionCategory() {
	}

	public NvProductCommentCriterionCategory(NvProductCommentCriterionCategoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProductCommentCriterion", column = @Column(name = "id_product_comment_criterion", nullable = false)),
			@AttributeOverride(name = "idCategory", column = @Column(name = "id_category", nullable = false)) })
	public NvProductCommentCriterionCategoryId getId() {
		return this.id;
	}

	public void setId(NvProductCommentCriterionCategoryId id) {
		this.id = id;
	}

}
