package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCountryTax generated by hbm2java
 */
@Entity
@Table(name = "nv_product_country_tax", catalog = "NVPrestashop")
public class NvProductCountryTax implements java.io.Serializable {

	private NvProductCountryTaxId id;
	private int idTax;

	public NvProductCountryTax() {
	}

	public NvProductCountryTax(NvProductCountryTaxId id, int idTax) {
		this.id = id;
		this.idTax = idTax;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idCountry", column = @Column(name = "id_country", nullable = false)) })
	public NvProductCountryTaxId getId() {
		return this.id;
	}

	public void setId(NvProductCountryTaxId id) {
		this.id = id;
	}

	@Column(name = "id_tax", nullable = false)
	public int getIdTax() {
		return this.idTax;
	}

	public void setIdTax(int idTax) {
		this.idTax = idTax;
	}

}
