package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCommentCriterionProduct generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment_criterion_product", catalog = "NVPrestashop")
public class NvProductCommentCriterionProduct implements java.io.Serializable {

	private NvProductCommentCriterionProductId id;

	public NvProductCommentCriterionProduct() {
	}

	public NvProductCommentCriterionProduct(NvProductCommentCriterionProductId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idProductCommentCriterion", column = @Column(name = "id_product_comment_criterion", nullable = false)) })
	public NvProductCommentCriterionProductId getId() {
		return this.id;
	}

	public void setId(NvProductCommentCriterionProductId id) {
		this.id = id;
	}

}
