package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvProductCommentReport generated by hbm2java
 */
@Entity
@Table(name = "nv_product_comment_report", catalog = "NVPrestashop")
public class NvProductCommentReport implements java.io.Serializable {

	private NvProductCommentReportId id;

	public NvProductCommentReport() {
	}

	public NvProductCommentReport(NvProductCommentReportId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idProductComment", column = @Column(name = "id_product_comment", nullable = false)),
			@AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)) })
	public NvProductCommentReportId getId() {
		return this.id;
	}

	public void setId(NvProductCommentReportId id) {
		this.id = id;
	}

}
