package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvProductCommentUsefulnessId generated by hbm2java
 */
@Embeddable
public class NvProductCommentUsefulnessId implements java.io.Serializable {

	private int idProductComment;
	private int idCustomer;

	public NvProductCommentUsefulnessId() {
	}

	public NvProductCommentUsefulnessId(int idProductComment, int idCustomer) {
		this.idProductComment = idProductComment;
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_product_comment", nullable = false)
	public int getIdProductComment() {
		return this.idProductComment;
	}

	public void setIdProductComment(int idProductComment) {
		this.idProductComment = idProductComment;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvProductCommentUsefulnessId))
			return false;
		NvProductCommentUsefulnessId castOther = (NvProductCommentUsefulnessId) other;

		return (this.getIdProductComment() == castOther.getIdProductComment()) && (this.getIdCustomer() == castOther.getIdCustomer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductComment();
		result = 37 * result + this.getIdCustomer();
		return result;
	}

}
