package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvQuickAccessLangId generated by hbm2java
 */
@Embeddable
public class NvQuickAccessLangId implements java.io.Serializable {

	private int idQuickAccess;
	private int idLang;

	public NvQuickAccessLangId() {
	}

	public NvQuickAccessLangId(int idQuickAccess, int idLang) {
		this.idQuickAccess = idQuickAccess;
		this.idLang = idLang;
	}

	@Column(name = "id_quick_access", nullable = false)
	public int getIdQuickAccess() {
		return this.idQuickAccess;
	}

	public void setIdQuickAccess(int idQuickAccess) {
		this.idQuickAccess = idQuickAccess;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvQuickAccessLangId))
			return false;
		NvQuickAccessLangId castOther = (NvQuickAccessLangId) other;

		return (this.getIdQuickAccess() == castOther.getIdQuickAccess()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdQuickAccess();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
