package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvReferrer generated by hbm2java
 */
@Entity
@Table(name = "nv_referrer", catalog = "NVPrestashop")
public class NvReferrer implements java.io.Serializable {

	private Integer idReferrer;
	private String name;
	private String passwd;
	private String httpRefererRegexp;
	private String httpRefererLike;
	private String requestUriRegexp;
	private String requestUriLike;
	private String httpRefererRegexpNot;
	private String httpRefererLikeNot;
	private String requestUriRegexpNot;
	private String requestUriLikeNot;
	private BigDecimal baseFee;
	private BigDecimal percentFee;
	private BigDecimal clickFee;
	private Date dateAdd;

	public NvReferrer() {
	}

	public NvReferrer(String name, BigDecimal baseFee, BigDecimal percentFee, BigDecimal clickFee, Date dateAdd) {
		this.name = name;
		this.baseFee = baseFee;
		this.percentFee = percentFee;
		this.clickFee = clickFee;
		this.dateAdd = dateAdd;
	}

	public NvReferrer(String name, String passwd, String httpRefererRegexp, String httpRefererLike, String requestUriRegexp, String requestUriLike,
					String httpRefererRegexpNot, String httpRefererLikeNot, String requestUriRegexpNot, String requestUriLikeNot, BigDecimal baseFee,
					BigDecimal percentFee, BigDecimal clickFee, Date dateAdd) {
		this.name = name;
		this.passwd = passwd;
		this.httpRefererRegexp = httpRefererRegexp;
		this.httpRefererLike = httpRefererLike;
		this.requestUriRegexp = requestUriRegexp;
		this.requestUriLike = requestUriLike;
		this.httpRefererRegexpNot = httpRefererRegexpNot;
		this.httpRefererLikeNot = httpRefererLikeNot;
		this.requestUriRegexpNot = requestUriRegexpNot;
		this.requestUriLikeNot = requestUriLikeNot;
		this.baseFee = baseFee;
		this.percentFee = percentFee;
		this.clickFee = clickFee;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_referrer", unique = true, nullable = false)
	public Integer getIdReferrer() {
		return this.idReferrer;
	}

	public void setIdReferrer(Integer idReferrer) {
		this.idReferrer = idReferrer;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "passwd", length = 32)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "http_referer_regexp", length = 64)
	public String getHttpRefererRegexp() {
		return this.httpRefererRegexp;
	}

	public void setHttpRefererRegexp(String httpRefererRegexp) {
		this.httpRefererRegexp = httpRefererRegexp;
	}

	@Column(name = "http_referer_like", length = 64)
	public String getHttpRefererLike() {
		return this.httpRefererLike;
	}

	public void setHttpRefererLike(String httpRefererLike) {
		this.httpRefererLike = httpRefererLike;
	}

	@Column(name = "request_uri_regexp", length = 64)
	public String getRequestUriRegexp() {
		return this.requestUriRegexp;
	}

	public void setRequestUriRegexp(String requestUriRegexp) {
		this.requestUriRegexp = requestUriRegexp;
	}

	@Column(name = "request_uri_like", length = 64)
	public String getRequestUriLike() {
		return this.requestUriLike;
	}

	public void setRequestUriLike(String requestUriLike) {
		this.requestUriLike = requestUriLike;
	}

	@Column(name = "http_referer_regexp_not", length = 64)
	public String getHttpRefererRegexpNot() {
		return this.httpRefererRegexpNot;
	}

	public void setHttpRefererRegexpNot(String httpRefererRegexpNot) {
		this.httpRefererRegexpNot = httpRefererRegexpNot;
	}

	@Column(name = "http_referer_like_not", length = 64)
	public String getHttpRefererLikeNot() {
		return this.httpRefererLikeNot;
	}

	public void setHttpRefererLikeNot(String httpRefererLikeNot) {
		this.httpRefererLikeNot = httpRefererLikeNot;
	}

	@Column(name = "request_uri_regexp_not", length = 64)
	public String getRequestUriRegexpNot() {
		return this.requestUriRegexpNot;
	}

	public void setRequestUriRegexpNot(String requestUriRegexpNot) {
		this.requestUriRegexpNot = requestUriRegexpNot;
	}

	@Column(name = "request_uri_like_not", length = 64)
	public String getRequestUriLikeNot() {
		return this.requestUriLikeNot;
	}

	public void setRequestUriLikeNot(String requestUriLikeNot) {
		this.requestUriLikeNot = requestUriLikeNot;
	}

	@Column(name = "base_fee", nullable = false, precision = 5)
	public BigDecimal getBaseFee() {
		return this.baseFee;
	}

	public void setBaseFee(BigDecimal baseFee) {
		this.baseFee = baseFee;
	}

	@Column(name = "percent_fee", nullable = false, precision = 5)
	public BigDecimal getPercentFee() {
		return this.percentFee;
	}

	public void setPercentFee(BigDecimal percentFee) {
		this.percentFee = percentFee;
	}

	@Column(name = "click_fee", nullable = false, precision = 5)
	public BigDecimal getClickFee() {
		return this.clickFee;
	}

	public void setClickFee(BigDecimal clickFee) {
		this.clickFee = clickFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
