package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvReferrerShop generated by hbm2java
 */
@Entity
@Table(name = "nv_referrer_shop", catalog = "NVPrestashop")
public class NvReferrerShop implements java.io.Serializable {

	private NvReferrerShopId id;
	private Integer cacheVisitors;
	private Integer cacheVisits;
	private Integer cachePages;
	private Integer cacheRegistrations;
	private Integer cacheOrders;
	private BigDecimal cacheSales;
	private BigDecimal cacheRegRate;
	private BigDecimal cacheOrderRate;

	public NvReferrerShop() {
	}

	public NvReferrerShop(NvReferrerShopId id) {
		this.id = id;
	}

	public NvReferrerShop(NvReferrerShopId id, Integer cacheVisitors, Integer cacheVisits, Integer cachePages, Integer cacheRegistrations, Integer cacheOrders,
					BigDecimal cacheSales, BigDecimal cacheRegRate, BigDecimal cacheOrderRate) {
		this.id = id;
		this.cacheVisitors = cacheVisitors;
		this.cacheVisits = cacheVisits;
		this.cachePages = cachePages;
		this.cacheRegistrations = cacheRegistrations;
		this.cacheOrders = cacheOrders;
		this.cacheSales = cacheSales;
		this.cacheRegRate = cacheRegRate;
		this.cacheOrderRate = cacheOrderRate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idReferrer", column = @Column(name = "id_referrer", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvReferrerShopId getId() {
		return this.id;
	}

	public void setId(NvReferrerShopId id) {
		this.id = id;
	}

	@Column(name = "cache_visitors")
	public Integer getCacheVisitors() {
		return this.cacheVisitors;
	}

	public void setCacheVisitors(Integer cacheVisitors) {
		this.cacheVisitors = cacheVisitors;
	}

	@Column(name = "cache_visits")
	public Integer getCacheVisits() {
		return this.cacheVisits;
	}

	public void setCacheVisits(Integer cacheVisits) {
		this.cacheVisits = cacheVisits;
	}

	@Column(name = "cache_pages")
	public Integer getCachePages() {
		return this.cachePages;
	}

	public void setCachePages(Integer cachePages) {
		this.cachePages = cachePages;
	}

	@Column(name = "cache_registrations")
	public Integer getCacheRegistrations() {
		return this.cacheRegistrations;
	}

	public void setCacheRegistrations(Integer cacheRegistrations) {
		this.cacheRegistrations = cacheRegistrations;
	}

	@Column(name = "cache_orders")
	public Integer getCacheOrders() {
		return this.cacheOrders;
	}

	public void setCacheOrders(Integer cacheOrders) {
		this.cacheOrders = cacheOrders;
	}

	@Column(name = "cache_sales", precision = 17)
	public BigDecimal getCacheSales() {
		return this.cacheSales;
	}

	public void setCacheSales(BigDecimal cacheSales) {
		this.cacheSales = cacheSales;
	}

	@Column(name = "cache_reg_rate", precision = 5, scale = 4)
	public BigDecimal getCacheRegRate() {
		return this.cacheRegRate;
	}

	public void setCacheRegRate(BigDecimal cacheRegRate) {
		this.cacheRegRate = cacheRegRate;
	}

	@Column(name = "cache_order_rate", precision = 5, scale = 4)
	public BigDecimal getCacheOrderRate() {
		return this.cacheOrderRate;
	}

	public void setCacheOrderRate(BigDecimal cacheOrderRate) {
		this.cacheOrderRate = cacheOrderRate;
	}

}
