package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvReferrerCache generated by hbm2java
 */
@Entity
@Table(name = "nv_referrer_cache", catalog = "NVPrestashop")
public class NvReferrerCache implements java.io.Serializable {

	private NvReferrerCacheId id;

	public NvReferrerCache() {
	}

	public NvReferrerCache(NvReferrerCacheId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idConnectionsSource", column = @Column(name = "id_connections_source", nullable = false)),
			@AttributeOverride(name = "idReferrer", column = @Column(name = "id_referrer", nullable = false)) })
	public NvReferrerCacheId getId() {
		return this.id;
	}

	public void setId(NvReferrerCacheId id) {
		this.id = id;
	}

}
