package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvRequestSql generated by hbm2java
 */
@Entity
@Table(name = "nv_request_sql", catalog = "NVPrestashop")
public class NvRequestSql implements java.io.Serializable {

	private Integer idRequestSql;
	private String name;
	private String sql;

	public NvRequestSql() {
	}

	public NvRequestSql(String name, String sql) {
		this.name = name;
		this.sql = sql;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_request_sql", unique = true, nullable = false)
	public Integer getIdRequestSql() {
		return this.idRequestSql;
	}

	public void setIdRequestSql(Integer idRequestSql) {
		this.idRequestSql = idRequestSql;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sql", nullable = false, length = 65535)
	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

}
