package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * NvReferralprogram generated by hbm2java
 */
@Entity
@Table(name = "nv_referralprogram", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class NvReferralprogram implements java.io.Serializable {

	private Integer idReferralprogram;
	private int idSponsor;
	private String email;
	private String lastname;
	private String firstname;
	private Integer idCustomer;
	private Integer idCartRule;
	private Integer idCartRuleSponsor;
	private Date dateAdd;
	private Date dateUpd;

	public NvReferralprogram() {
	}

	public NvReferralprogram(int idSponsor, String email, String lastname, String firstname, Date dateAdd, Date dateUpd) {
		this.idSponsor = idSponsor;
		this.email = email;
		this.lastname = lastname;
		this.firstname = firstname;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvReferralprogram(int idSponsor, String email, String lastname, String firstname, Integer idCustomer, Integer idCartRule, Integer idCartRuleSponsor,
					Date dateAdd, Date dateUpd) {
		this.idSponsor = idSponsor;
		this.email = email;
		this.lastname = lastname;
		this.firstname = firstname;
		this.idCustomer = idCustomer;
		this.idCartRule = idCartRule;
		this.idCartRuleSponsor = idCartRuleSponsor;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_referralprogram", unique = true, nullable = false)
	public Integer getIdReferralprogram() {
		return this.idReferralprogram;
	}

	public void setIdReferralprogram(Integer idReferralprogram) {
		this.idReferralprogram = idReferralprogram;
	}

	@Column(name = "id_sponsor", nullable = false)
	public int getIdSponsor() {
		return this.idSponsor;
	}

	public void setIdSponsor(int idSponsor) {
		this.idSponsor = idSponsor;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "lastname", nullable = false, length = 128)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "firstname", nullable = false, length = 128)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "id_customer")
	public Integer getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Integer idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_cart_rule")
	public Integer getIdCartRule() {
		return this.idCartRule;
	}

	public void setIdCartRule(Integer idCartRule) {
		this.idCartRule = idCartRule;
	}

	@Column(name = "id_cart_rule_sponsor")
	public Integer getIdCartRuleSponsor() {
		return this.idCartRuleSponsor;
	}

	public void setIdCartRuleSponsor(Integer idCartRuleSponsor) {
		this.idCartRuleSponsor = idCartRuleSponsor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

}
