package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvRiskLangId generated by hbm2java
 */
@Embeddable
public class NvRiskLangId implements java.io.Serializable {

	private int idRisk;
	private int idLang;

	public NvRiskLangId() {
	}

	public NvRiskLangId(int idRisk, int idLang) {
		this.idRisk = idRisk;
		this.idLang = idLang;
	}

	@Column(name = "id_risk", nullable = false)
	public int getIdRisk() {
		return this.idRisk;
	}

	public void setIdRisk(int idRisk) {
		this.idRisk = idRisk;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvRiskLangId))
			return false;
		NvRiskLangId castOther = (NvRiskLangId) other;

		return (this.getIdRisk() == castOther.getIdRisk()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRisk();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
