package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvSceneShop generated by hbm2java
 */
@Entity
@Table(name = "nv_scene_shop", catalog = "NVPrestashop")
public class NvSceneShop implements java.io.Serializable {

	private NvSceneShopId id;

	public NvSceneShop() {
	}

	public NvSceneShop(NvSceneShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idScene", column = @Column(name = "id_scene", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvSceneShopId getId() {
		return this.id;
	}

	public void setId(NvSceneShopId id) {
		this.id = id;
	}

}
