package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvSceneLang generated by hbm2java
 */
@Entity
@Table(name = "nv_scene_lang", catalog = "NVPrestashop")
public class NvSceneLang implements java.io.Serializable {

	private NvSceneLangId id;
	private String name;

	public NvSceneLang() {
	}

	public NvSceneLang(NvSceneLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idScene", column = @Column(name = "id_scene", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvSceneLangId getId() {
		return this.id;
	}

	public void setId(NvSceneLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
