package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvSearchIndexId generated by hbm2java
 */
@Embeddable
public class NvSearchIndexId implements java.io.Serializable {

	private int idWord;
	private int idProduct;

	public NvSearchIndexId() {
	}

	public NvSearchIndexId(int idWord, int idProduct) {
		this.idWord = idWord;
		this.idProduct = idProduct;
	}

	@Column(name = "id_word", nullable = false)
	public int getIdWord() {
		return this.idWord;
	}

	public void setIdWord(int idWord) {
		this.idWord = idWord;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvSearchIndexId))
			return false;
		NvSearchIndexId castOther = (NvSearchIndexId) other;

		return (this.getIdWord() == castOther.getIdWord()) && (this.getIdProduct() == castOther.getIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdWord();
		result = 37 * result + this.getIdProduct();
		return result;
	}

}
