package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvSearchIndex generated by hbm2java
 */
@Entity
@Table(name = "nv_search_index", catalog = "NVPrestashop")
public class NvSearchIndex implements java.io.Serializable {

	private NvSearchIndexId id;
	private short weight;

	public NvSearchIndex() {
	}

	public NvSearchIndex(NvSearchIndexId id, short weight) {
		this.id = id;
		this.weight = weight;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idWord", column = @Column(name = "id_word", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)) })
	public NvSearchIndexId getId() {
		return this.id;
	}

	public void setId(NvSearchIndexId id) {
		this.id = id;
	}

	@Column(name = "weight", nullable = false)
	public short getWeight() {
		return this.weight;
	}

	public void setWeight(short weight) {
		this.weight = weight;
	}

}
