package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvSekeyword generated by hbm2java
 */
@Entity
@Table(name = "nv_sekeyword", catalog = "NVPrestashop")
public class NvSekeyword implements java.io.Serializable {

	private Integer idSekeyword;
	private int idShop;
	private int idShopGroup;
	private String keyword;
	private Date dateAdd;

	public NvSekeyword() {
	}

	public NvSekeyword(int idShop, int idShopGroup, String keyword, Date dateAdd) {
		this.idShop = idShop;
		this.idShopGroup = idShopGroup;
		this.keyword = keyword;
		this.dateAdd = dateAdd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sekeyword", unique = true, nullable = false)
	public Integer getIdSekeyword() {
		return this.idSekeyword;
	}

	public void setIdSekeyword(Integer idSekeyword) {
		this.idSekeyword = idSekeyword;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_shop_group", nullable = false)
	public int getIdShopGroup() {
		return this.idShopGroup;
	}

	public void setIdShopGroup(int idShopGroup) {
		this.idShopGroup = idShopGroup;
	}

	@Column(name = "keyword", nullable = false, length = 256)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

}
