package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvShopUrl generated by hbm2java
 */
@Entity
@Table(name = "nv_shop_url", catalog = "NVPrestashop", uniqueConstraints = { @UniqueConstraint(columnNames = { "domain_ssl", "physical_uri", "virtual_uri" }),
		@UniqueConstraint(columnNames = { "domain", "physical_uri", "virtual_uri" }) })
public class NvShopUrl implements java.io.Serializable {

	private Integer idShopUrl;
	private int idShop;
	private String domain;
	private String domainSsl;
	private String physicalUri;
	private String virtualUri;
	private boolean main;
	private boolean active;

	public NvShopUrl() {
	}

	public NvShopUrl(int idShop, String domain, String domainSsl, String physicalUri, String virtualUri, boolean main, boolean active) {
		this.idShop = idShop;
		this.domain = domain;
		this.domainSsl = domainSsl;
		this.physicalUri = physicalUri;
		this.virtualUri = virtualUri;
		this.main = main;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_shop_url", unique = true, nullable = false)
	public Integer getIdShopUrl() {
		return this.idShopUrl;
	}

	public void setIdShopUrl(Integer idShopUrl) {
		this.idShopUrl = idShopUrl;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "domain", nullable = false, length = 150)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "domain_ssl", nullable = false, length = 150)
	public String getDomainSsl() {
		return this.domainSsl;
	}

	public void setDomainSsl(String domainSsl) {
		this.domainSsl = domainSsl;
	}

	@Column(name = "physical_uri", nullable = false, length = 64)
	public String getPhysicalUri() {
		return this.physicalUri;
	}

	public void setPhysicalUri(String physicalUri) {
		this.physicalUri = physicalUri;
	}

	@Column(name = "virtual_uri", nullable = false, length = 64)
	public String getVirtualUri() {
		return this.virtualUri;
	}

	public void setVirtualUri(String virtualUri) {
		this.virtualUri = virtualUri;
	}

	@Column(name = "main", nullable = false)
	public boolean isMain() {
		return this.main;
	}

	public void setMain(boolean main) {
		this.main = main;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
