package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvSmartyLastFlush generated by hbm2java
 */
@Entity
@Table(name = "nv_smarty_last_flush", catalog = "NVPrestashop")
public class NvSmartyLastFlush implements java.io.Serializable {

	private String type;
	private Date lastFlush;

	public NvSmartyLastFlush() {
	}

	public NvSmartyLastFlush(String type, Date lastFlush) {
		this.type = type;
		this.lastFlush = lastFlush;
	}

	@Id
	@Column(name = "type", unique = true, nullable = false, length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_flush", nullable = false, length = 0)
	public Date getLastFlush() {
		return this.lastFlush;
	}

	public void setLastFlush(Date lastFlush) {
		this.lastFlush = lastFlush;
	}

}
