package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvSmartyLazyCache generated by hbm2java
 */
@Entity
@Table(name = "nv_smarty_lazy_cache", catalog = "NVPrestashop")
public class NvSmartyLazyCache implements java.io.Serializable {

	private NvSmartyLazyCacheId id;
	private String filepath;
	private Date lastUpdate;

	public NvSmartyLazyCache() {
	}

	public NvSmartyLazyCache(NvSmartyLazyCacheId id, String filepath, Date lastUpdate) {
		this.id = id;
		this.filepath = filepath;
		this.lastUpdate = lastUpdate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "templateHash", column = @Column(name = "template_hash", nullable = false, length = 32)),
			@AttributeOverride(name = "cacheId", column = @Column(name = "cache_id", nullable = false)),
			@AttributeOverride(name = "compileId", column = @Column(name = "compile_id", nullable = false, length = 32)) })
	public NvSmartyLazyCacheId getId() {
		return this.id;
	}

	public void setId(NvSmartyLazyCacheId id) {
		this.id = id;
	}

	@Column(name = "filepath", nullable = false)
	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 0)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
