package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvSpecificPricePriorityId generated by hbm2java
 */
@Embeddable
public class NvSpecificPricePriorityId implements java.io.Serializable {

	private int idSpecificPricePriority;
	private int idProduct;

	public NvSpecificPricePriorityId() {
	}

	public NvSpecificPricePriorityId(int idSpecificPricePriority, int idProduct) {
		this.idSpecificPricePriority = idSpecificPricePriority;
		this.idProduct = idProduct;
	}

	@Column(name = "id_specific_price_priority", nullable = false)
	public int getIdSpecificPricePriority() {
		return this.idSpecificPricePriority;
	}

	public void setIdSpecificPricePriority(int idSpecificPricePriority) {
		this.idSpecificPricePriority = idSpecificPricePriority;
	}

	@Column(name = "id_product", unique = true, nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvSpecificPricePriorityId))
			return false;
		NvSpecificPricePriorityId castOther = (NvSpecificPricePriorityId) other;

		return (this.getIdSpecificPricePriority() == castOther.getIdSpecificPricePriority()) && (this.getIdProduct() == castOther.getIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSpecificPricePriority();
		result = 37 * result + this.getIdProduct();
		return result;
	}

}
