package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvSpecificPriceRuleConditionGroup generated by hbm2java
 */
@Entity
@Table(name = "nv_specific_price_rule_condition_group", catalog = "NVPrestashop")
public class NvSpecificPriceRuleConditionGroup implements java.io.Serializable {

	private NvSpecificPriceRuleConditionGroupId id;

	public NvSpecificPriceRuleConditionGroup() {
	}

	public NvSpecificPriceRuleConditionGroup(NvSpecificPriceRuleConditionGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpecificPriceRuleConditionGroup", column = @Column(name = "id_specific_price_rule_condition_group", nullable = false)),
			@AttributeOverride(name = "idSpecificPriceRule", column = @Column(name = "id_specific_price_rule", nullable = false)) })
	public NvSpecificPriceRuleConditionGroupId getId() {
		return this.id;
	}

	public void setId(NvSpecificPriceRuleConditionGroupId id) {
		this.id = id;
	}

}
