package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvSpecificPriceRuleConditionGroupId generated by hbm2java
 */
@Embeddable
public class NvSpecificPriceRuleConditionGroupId implements java.io.Serializable {

	private int idSpecificPriceRuleConditionGroup;
	private int idSpecificPriceRule;

	public NvSpecificPriceRuleConditionGroupId() {
	}

	public NvSpecificPriceRuleConditionGroupId(int idSpecificPriceRuleConditionGroup, int idSpecificPriceRule) {
		this.idSpecificPriceRuleConditionGroup = idSpecificPriceRuleConditionGroup;
		this.idSpecificPriceRule = idSpecificPriceRule;
	}

	@Column(name = "id_specific_price_rule_condition_group", nullable = false)
	public int getIdSpecificPriceRuleConditionGroup() {
		return this.idSpecificPriceRuleConditionGroup;
	}

	public void setIdSpecificPriceRuleConditionGroup(int idSpecificPriceRuleConditionGroup) {
		this.idSpecificPriceRuleConditionGroup = idSpecificPriceRuleConditionGroup;
	}

	@Column(name = "id_specific_price_rule", nullable = false)
	public int getIdSpecificPriceRule() {
		return this.idSpecificPriceRule;
	}

	public void setIdSpecificPriceRule(int idSpecificPriceRule) {
		this.idSpecificPriceRule = idSpecificPriceRule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvSpecificPriceRuleConditionGroupId))
			return false;
		NvSpecificPriceRuleConditionGroupId castOther = (NvSpecificPriceRuleConditionGroupId) other;

		return (this.getIdSpecificPriceRuleConditionGroup() == castOther.getIdSpecificPriceRuleConditionGroup())
						&& (this.getIdSpecificPriceRule() == castOther.getIdSpecificPriceRule());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSpecificPriceRuleConditionGroup();
		result = 37 * result + this.getIdSpecificPriceRule();
		return result;
	}

}
