package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvSpecificPricePriority generated by hbm2java
 */
@Entity
@Table(name = "nv_specific_price_priority", catalog = "NVPrestashop", uniqueConstraints = @UniqueConstraint(columnNames = "id_product"))
public class NvSpecificPricePriority implements java.io.Serializable {

	private NvSpecificPricePriorityId id;
	private String priority;

	public NvSpecificPricePriority() {
	}

	public NvSpecificPricePriority(NvSpecificPricePriorityId id, String priority) {
		this.id = id;
		this.priority = priority;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idSpecificPricePriority", column = @Column(name = "id_specific_price_priority", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", unique = true, nullable = false)) })
	public NvSpecificPricePriorityId getId() {
		return this.id;
	}

	public void setId(NvSpecificPricePriorityId id) {
		this.id = id;
	}

	@Column(name = "priority", nullable = false, length = 80)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

}
