package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvStoreShop generated by hbm2java
 */
@Entity
@Table(name = "nv_store_shop", catalog = "NVPrestashop")
public class NvStoreShop implements java.io.Serializable {

	private NvStoreShopId id;

	public NvStoreShop() {
	}

	public NvStoreShop(NvStoreShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idStore", column = @Column(name = "id_store", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvStoreShopId getId() {
		return this.id;
	}

	public void setId(NvStoreShopId id) {
		this.id = id;
	}

}
