package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvStoreShopId generated by hbm2java
 */
@Embeddable
public class NvStoreShopId implements java.io.Serializable {

	private int idStore;
	private int idShop;

	public NvStoreShopId() {
	}

	public NvStoreShopId(int idStore, int idShop) {
		this.idStore = idStore;
		this.idShop = idShop;
	}

	@Column(name = "id_store", nullable = false)
	public int getIdStore() {
		return this.idStore;
	}

	public void setIdStore(int idStore) {
		this.idStore = idStore;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvStoreShopId))
			return false;
		NvStoreShopId castOther = (NvStoreShopId) other;

		return (this.getIdStore() == castOther.getIdStore()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStore();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
