package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvSupplyOrderState generated by hbm2java
 */
@Entity
@Table(name = "nv_supply_order_state", catalog = "NVPrestashop")
public class NvSupplyOrderState implements java.io.Serializable {

	private Integer idSupplyOrderState;
	private boolean deliveryNote;
	private boolean editable;
	private boolean receiptState;
	private boolean pendingReceipt;
	private boolean enclosed;
	private String color;

	public NvSupplyOrderState() {
	}

	public NvSupplyOrderState(boolean deliveryNote, boolean editable, boolean receiptState, boolean pendingReceipt, boolean enclosed) {
		this.deliveryNote = deliveryNote;
		this.editable = editable;
		this.receiptState = receiptState;
		this.pendingReceipt = pendingReceipt;
		this.enclosed = enclosed;
	}

	public NvSupplyOrderState(boolean deliveryNote, boolean editable, boolean receiptState, boolean pendingReceipt, boolean enclosed, String color) {
		this.deliveryNote = deliveryNote;
		this.editable = editable;
		this.receiptState = receiptState;
		this.pendingReceipt = pendingReceipt;
		this.enclosed = enclosed;
		this.color = color;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_supply_order_state", unique = true, nullable = false)
	public Integer getIdSupplyOrderState() {
		return this.idSupplyOrderState;
	}

	public void setIdSupplyOrderState(Integer idSupplyOrderState) {
		this.idSupplyOrderState = idSupplyOrderState;
	}

	@Column(name = "delivery_note", nullable = false)
	public boolean isDeliveryNote() {
		return this.deliveryNote;
	}

	public void setDeliveryNote(boolean deliveryNote) {
		this.deliveryNote = deliveryNote;
	}

	@Column(name = "editable", nullable = false)
	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	@Column(name = "receipt_state", nullable = false)
	public boolean isReceiptState() {
		return this.receiptState;
	}

	public void setReceiptState(boolean receiptState) {
		this.receiptState = receiptState;
	}

	@Column(name = "pending_receipt", nullable = false)
	public boolean isPendingReceipt() {
		return this.pendingReceipt;
	}

	public void setPendingReceipt(boolean pendingReceipt) {
		this.pendingReceipt = pendingReceipt;
	}

	@Column(name = "enclosed", nullable = false)
	public boolean isEnclosed() {
		return this.enclosed;
	}

	public void setEnclosed(boolean enclosed) {
		this.enclosed = enclosed;
	}

	@Column(name = "color", length = 32)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
