package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvSupplyOrder generated by hbm2java
 */
@Entity
@Table(name = "nv_supply_order", catalog = "NVPrestashop")
public class NvSupplyOrder implements java.io.Serializable {

	private Integer idSupplyOrder;
	private int idSupplier;
	private String supplierName;
	private int idLang;
	private int idWarehouse;
	private int idSupplyOrderState;
	private int idCurrency;
	private int idRefCurrency;
	private String reference;
	private Date dateAdd;
	private Date dateUpd;
	private Date dateDeliveryExpected;
	private BigDecimal totalTe;
	private BigDecimal totalWithDiscountTe;
	private BigDecimal totalTax;
	private BigDecimal totalTi;
	private BigDecimal discountRate;
	private BigDecimal discountValueTe;
	private Boolean isTemplate;

	public NvSupplyOrder() {
	}

	public NvSupplyOrder(int idSupplier, String supplierName, int idLang, int idWarehouse, int idSupplyOrderState, int idCurrency, int idRefCurrency,
					String reference, Date dateAdd, Date dateUpd) {
		this.idSupplier = idSupplier;
		this.supplierName = supplierName;
		this.idLang = idLang;
		this.idWarehouse = idWarehouse;
		this.idSupplyOrderState = idSupplyOrderState;
		this.idCurrency = idCurrency;
		this.idRefCurrency = idRefCurrency;
		this.reference = reference;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvSupplyOrder(int idSupplier, String supplierName, int idLang, int idWarehouse, int idSupplyOrderState, int idCurrency, int idRefCurrency,
					String reference, Date dateAdd, Date dateUpd, Date dateDeliveryExpected, BigDecimal totalTe, BigDecimal totalWithDiscountTe,
					BigDecimal totalTax, BigDecimal totalTi, BigDecimal discountRate, BigDecimal discountValueTe, Boolean isTemplate) {
		this.idSupplier = idSupplier;
		this.supplierName = supplierName;
		this.idLang = idLang;
		this.idWarehouse = idWarehouse;
		this.idSupplyOrderState = idSupplyOrderState;
		this.idCurrency = idCurrency;
		this.idRefCurrency = idRefCurrency;
		this.reference = reference;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.dateDeliveryExpected = dateDeliveryExpected;
		this.totalTe = totalTe;
		this.totalWithDiscountTe = totalWithDiscountTe;
		this.totalTax = totalTax;
		this.totalTi = totalTi;
		this.discountRate = discountRate;
		this.discountValueTe = discountValueTe;
		this.isTemplate = isTemplate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_supply_order", unique = true, nullable = false)
	public Integer getIdSupplyOrder() {
		return this.idSupplyOrder;
	}

	public void setIdSupplyOrder(Integer idSupplyOrder) {
		this.idSupplyOrder = idSupplyOrder;
	}

	@Column(name = "id_supplier", nullable = false)
	public int getIdSupplier() {
		return this.idSupplier;
	}

	public void setIdSupplier(int idSupplier) {
		this.idSupplier = idSupplier;
	}

	@Column(name = "supplier_name", nullable = false, length = 64)
	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	@Column(name = "id_warehouse", nullable = false)
	public int getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(int idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "id_supply_order_state", nullable = false)
	public int getIdSupplyOrderState() {
		return this.idSupplyOrderState;
	}

	public void setIdSupplyOrderState(int idSupplyOrderState) {
		this.idSupplyOrderState = idSupplyOrderState;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "id_ref_currency", nullable = false)
	public int getIdRefCurrency() {
		return this.idRefCurrency;
	}

	public void setIdRefCurrency(int idRefCurrency) {
		this.idRefCurrency = idRefCurrency;
	}

	@Column(name = "reference", nullable = false, length = 64)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_delivery_expected", length = 0)
	public Date getDateDeliveryExpected() {
		return this.dateDeliveryExpected;
	}

	public void setDateDeliveryExpected(Date dateDeliveryExpected) {
		this.dateDeliveryExpected = dateDeliveryExpected;
	}

	@Column(name = "total_te", precision = 20, scale = 6)
	public BigDecimal getTotalTe() {
		return this.totalTe;
	}

	public void setTotalTe(BigDecimal totalTe) {
		this.totalTe = totalTe;
	}

	@Column(name = "total_with_discount_te", precision = 20, scale = 6)
	public BigDecimal getTotalWithDiscountTe() {
		return this.totalWithDiscountTe;
	}

	public void setTotalWithDiscountTe(BigDecimal totalWithDiscountTe) {
		this.totalWithDiscountTe = totalWithDiscountTe;
	}

	@Column(name = "total_tax", precision = 20, scale = 6)
	public BigDecimal getTotalTax() {
		return this.totalTax;
	}

	public void setTotalTax(BigDecimal totalTax) {
		this.totalTax = totalTax;
	}

	@Column(name = "total_ti", precision = 20, scale = 6)
	public BigDecimal getTotalTi() {
		return this.totalTi;
	}

	public void setTotalTi(BigDecimal totalTi) {
		this.totalTi = totalTi;
	}

	@Column(name = "discount_rate", precision = 20, scale = 6)
	public BigDecimal getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(BigDecimal discountRate) {
		this.discountRate = discountRate;
	}

	@Column(name = "discount_value_te", precision = 20, scale = 6)
	public BigDecimal getDiscountValueTe() {
		return this.discountValueTe;
	}

	public void setDiscountValueTe(BigDecimal discountValueTe) {
		this.discountValueTe = discountValueTe;
	}

	@Column(name = "is_template")
	public Boolean getIsTemplate() {
		return this.isTemplate;
	}

	public void setIsTemplate(Boolean isTemplate) {
		this.isTemplate = isTemplate;
	}

}
