package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvSupplyOrderStateLangId generated by hbm2java
 */
@Embeddable
public class NvSupplyOrderStateLangId implements java.io.Serializable {

	private int idSupplyOrderState;
	private int idLang;

	public NvSupplyOrderStateLangId() {
	}

	public NvSupplyOrderStateLangId(int idSupplyOrderState, int idLang) {
		this.idSupplyOrderState = idSupplyOrderState;
		this.idLang = idLang;
	}

	@Column(name = "id_supply_order_state", nullable = false)
	public int getIdSupplyOrderState() {
		return this.idSupplyOrderState;
	}

	public void setIdSupplyOrderState(int idSupplyOrderState) {
		this.idSupplyOrderState = idSupplyOrderState;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvSupplyOrderStateLangId))
			return false;
		NvSupplyOrderStateLangId castOther = (NvSupplyOrderStateLangId) other;

		return (this.getIdSupplyOrderState() == castOther.getIdSupplyOrderState()) && (this.getIdLang() == castOther.getIdLang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSupplyOrderState();
		result = 37 * result + this.getIdLang();
		return result;
	}

}
