package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvSupplierShopId generated by hbm2java
 */
@Embeddable
public class NvSupplierShopId implements java.io.Serializable {

	private int idSupplier;
	private int idShop;

	public NvSupplierShopId() {
	}

	public NvSupplierShopId(int idSupplier, int idShop) {
		this.idSupplier = idSupplier;
		this.idShop = idShop;
	}

	@Column(name = "id_supplier", nullable = false)
	public int getIdSupplier() {
		return this.idSupplier;
	}

	public void setIdSupplier(int idSupplier) {
		this.idSupplier = idSupplier;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvSupplierShopId))
			return false;
		NvSupplierShopId castOther = (NvSupplierShopId) other;

		return (this.getIdSupplier() == castOther.getIdSupplier()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSupplier();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
