package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvSupplyOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "nv_supply_order_detail", catalog = "NVPrestashop")
public class NvSupplyOrderDetail implements java.io.Serializable {

	private Integer idSupplyOrderDetail;
	private int idSupplyOrder;
	private int idCurrency;
	private int idProduct;
	private int idProductAttribute;
	private String reference;
	private String supplierReference;
	private String name;
	private String ean13;
	private String upc;
	private BigDecimal exchangeRate;
	private BigDecimal unitPriceTe;
	private int quantityExpected;
	private int quantityReceived;
	private BigDecimal priceTe;
	private BigDecimal discountRate;
	private BigDecimal discountValueTe;
	private BigDecimal priceWithDiscountTe;
	private BigDecimal taxRate;
	private BigDecimal taxValue;
	private BigDecimal priceTi;
	private BigDecimal taxValueWithOrderDiscount;
	private BigDecimal priceWithOrderDiscountTe;

	public NvSupplyOrderDetail() {
	}

	public NvSupplyOrderDetail(int idSupplyOrder, int idCurrency, int idProduct, int idProductAttribute, String reference, String supplierReference,
					String name, int quantityExpected, int quantityReceived) {
		this.idSupplyOrder = idSupplyOrder;
		this.idCurrency = idCurrency;
		this.idProduct = idProduct;
		this.idProductAttribute = idProductAttribute;
		this.reference = reference;
		this.supplierReference = supplierReference;
		this.name = name;
		this.quantityExpected = quantityExpected;
		this.quantityReceived = quantityReceived;
	}

	public NvSupplyOrderDetail(int idSupplyOrder, int idCurrency, int idProduct, int idProductAttribute, String reference, String supplierReference,
					String name, String ean13, String upc, BigDecimal exchangeRate, BigDecimal unitPriceTe, int quantityExpected, int quantityReceived,
					BigDecimal priceTe, BigDecimal discountRate, BigDecimal discountValueTe, BigDecimal priceWithDiscountTe, BigDecimal taxRate,
					BigDecimal taxValue, BigDecimal priceTi, BigDecimal taxValueWithOrderDiscount, BigDecimal priceWithOrderDiscountTe) {
		this.idSupplyOrder = idSupplyOrder;
		this.idCurrency = idCurrency;
		this.idProduct = idProduct;
		this.idProductAttribute = idProductAttribute;
		this.reference = reference;
		this.supplierReference = supplierReference;
		this.name = name;
		this.ean13 = ean13;
		this.upc = upc;
		this.exchangeRate = exchangeRate;
		this.unitPriceTe = unitPriceTe;
		this.quantityExpected = quantityExpected;
		this.quantityReceived = quantityReceived;
		this.priceTe = priceTe;
		this.discountRate = discountRate;
		this.discountValueTe = discountValueTe;
		this.priceWithDiscountTe = priceWithDiscountTe;
		this.taxRate = taxRate;
		this.taxValue = taxValue;
		this.priceTi = priceTi;
		this.taxValueWithOrderDiscount = taxValueWithOrderDiscount;
		this.priceWithOrderDiscountTe = priceWithOrderDiscountTe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_supply_order_detail", unique = true, nullable = false)
	public Integer getIdSupplyOrderDetail() {
		return this.idSupplyOrderDetail;
	}

	public void setIdSupplyOrderDetail(Integer idSupplyOrderDetail) {
		this.idSupplyOrderDetail = idSupplyOrderDetail;
	}

	@Column(name = "id_supply_order", nullable = false)
	public int getIdSupplyOrder() {
		return this.idSupplyOrder;
	}

	public void setIdSupplyOrder(int idSupplyOrder) {
		this.idSupplyOrder = idSupplyOrder;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_product_attribute", nullable = false)
	public int getIdProductAttribute() {
		return this.idProductAttribute;
	}

	public void setIdProductAttribute(int idProductAttribute) {
		this.idProductAttribute = idProductAttribute;
	}

	@Column(name = "reference", nullable = false, length = 32)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "supplier_reference", nullable = false, length = 32)
	public String getSupplierReference() {
		return this.supplierReference;
	}

	public void setSupplierReference(String supplierReference) {
		this.supplierReference = supplierReference;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ean13", length = 13)
	public String getEan13() {
		return this.ean13;
	}

	public void setEan13(String ean13) {
		this.ean13 = ean13;
	}

	@Column(name = "upc", length = 12)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "exchange_rate", precision = 20, scale = 6)
	public BigDecimal getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "unit_price_te", precision = 20, scale = 6)
	public BigDecimal getUnitPriceTe() {
		return this.unitPriceTe;
	}

	public void setUnitPriceTe(BigDecimal unitPriceTe) {
		this.unitPriceTe = unitPriceTe;
	}

	@Column(name = "quantity_expected", nullable = false)
	public int getQuantityExpected() {
		return this.quantityExpected;
	}

	public void setQuantityExpected(int quantityExpected) {
		this.quantityExpected = quantityExpected;
	}

	@Column(name = "quantity_received", nullable = false)
	public int getQuantityReceived() {
		return this.quantityReceived;
	}

	public void setQuantityReceived(int quantityReceived) {
		this.quantityReceived = quantityReceived;
	}

	@Column(name = "price_te", precision = 20, scale = 6)
	public BigDecimal getPriceTe() {
		return this.priceTe;
	}

	public void setPriceTe(BigDecimal priceTe) {
		this.priceTe = priceTe;
	}

	@Column(name = "discount_rate", precision = 20, scale = 6)
	public BigDecimal getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(BigDecimal discountRate) {
		this.discountRate = discountRate;
	}

	@Column(name = "discount_value_te", precision = 20, scale = 6)
	public BigDecimal getDiscountValueTe() {
		return this.discountValueTe;
	}

	public void setDiscountValueTe(BigDecimal discountValueTe) {
		this.discountValueTe = discountValueTe;
	}

	@Column(name = "price_with_discount_te", precision = 20, scale = 6)
	public BigDecimal getPriceWithDiscountTe() {
		return this.priceWithDiscountTe;
	}

	public void setPriceWithDiscountTe(BigDecimal priceWithDiscountTe) {
		this.priceWithDiscountTe = priceWithDiscountTe;
	}

	@Column(name = "tax_rate", precision = 20, scale = 6)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "tax_value", precision = 20, scale = 6)
	public BigDecimal getTaxValue() {
		return this.taxValue;
	}

	public void setTaxValue(BigDecimal taxValue) {
		this.taxValue = taxValue;
	}

	@Column(name = "price_ti", precision = 20, scale = 6)
	public BigDecimal getPriceTi() {
		return this.priceTi;
	}

	public void setPriceTi(BigDecimal priceTi) {
		this.priceTi = priceTi;
	}

	@Column(name = "tax_value_with_order_discount", precision = 20, scale = 6)
	public BigDecimal getTaxValueWithOrderDiscount() {
		return this.taxValueWithOrderDiscount;
	}

	public void setTaxValueWithOrderDiscount(BigDecimal taxValueWithOrderDiscount) {
		this.taxValueWithOrderDiscount = taxValueWithOrderDiscount;
	}

	@Column(name = "price_with_order_discount_te", precision = 20, scale = 6)
	public BigDecimal getPriceWithOrderDiscountTe() {
		return this.priceWithOrderDiscountTe;
	}

	public void setPriceWithOrderDiscountTe(BigDecimal priceWithOrderDiscountTe) {
		this.priceWithOrderDiscountTe = priceWithOrderDiscountTe;
	}

}
