package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvSupplyOrderStateLang generated by hbm2java
 */
@Entity
@Table(name = "nv_supply_order_state_lang", catalog = "NVPrestashop")
public class NvSupplyOrderStateLang implements java.io.Serializable {

	private NvSupplyOrderStateLangId id;
	private String name;

	public NvSupplyOrderStateLang() {
	}

	public NvSupplyOrderStateLang(NvSupplyOrderStateLangId id) {
		this.id = id;
	}

	public NvSupplyOrderStateLang(NvSupplyOrderStateLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idSupplyOrderState", column = @Column(name = "id_supply_order_state", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvSupplyOrderStateLangId getId() {
		return this.id;
	}

	public void setId(NvSupplyOrderStateLangId id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
