package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvTax generated by hbm2java
 */
@Entity
@Table(name = "nv_tax", catalog = "NVPrestashop")
public class NvTax implements java.io.Serializable {

	private Integer idTax;
	private BigDecimal rate;
	private boolean active;
	private boolean deleted;

	public NvTax() {
	}

	public NvTax(BigDecimal rate, boolean active, boolean deleted) {
		this.rate = rate;
		this.active = active;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tax", unique = true, nullable = false)
	public Integer getIdTax() {
		return this.idTax;
	}

	public void setIdTax(Integer idTax) {
		this.idTax = idTax;
	}

	@Column(name = "rate", nullable = false, precision = 10, scale = 3)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
