package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvTagCount generated by hbm2java
 */
@Entity
@Table(name = "nv_tag_count", catalog = "NVPrestashop")
public class NvTagCount implements java.io.Serializable {

	private NvTagCountId id;
	private int idLang;
	private int idShop;
	private int counter;

	public NvTagCount() {
	}

	public NvTagCount(NvTagCountId id, int idLang, int idShop, int counter) {
		this.id = id;
		this.idLang = idLang;
		this.idShop = idShop;
		this.counter = counter;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGroup", column = @Column(name = "id_group", nullable = false)),
			@AttributeOverride(name = "idTag", column = @Column(name = "id_tag", nullable = false)) })
	public NvTagCountId getId() {
		return this.id;
	}

	public void setId(NvTagCountId id) {
		this.id = id;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "counter", nullable = false)
	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

}
