package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvTabLang generated by hbm2java
 */
@Entity
@Table(name = "nv_tab_lang", catalog = "NVPrestashop")
public class NvTabLang implements java.io.Serializable {

	private NvTabLangId id;
	private String name;

	public NvTabLang() {
	}

	public NvTabLang(NvTabLangId id) {
		this.id = id;
	}

	public NvTabLang(NvTabLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idTab", column = @Column(name = "id_tab", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvTabLangId getId() {
		return this.id;
	}

	public void setId(NvTabLangId id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
