package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvTabAdviceId generated by hbm2java
 */
@Embeddable
public class NvTabAdviceId implements java.io.Serializable {

	private int idTab;
	private int idAdvice;

	public NvTabAdviceId() {
	}

	public NvTabAdviceId(int idTab, int idAdvice) {
		this.idTab = idTab;
		this.idAdvice = idAdvice;
	}

	@Column(name = "id_tab", nullable = false)
	public int getIdTab() {
		return this.idTab;
	}

	public void setIdTab(int idTab) {
		this.idTab = idTab;
	}

	@Column(name = "id_advice", nullable = false)
	public int getIdAdvice() {
		return this.idAdvice;
	}

	public void setIdAdvice(int idAdvice) {
		this.idAdvice = idAdvice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvTabAdviceId))
			return false;
		NvTabAdviceId castOther = (NvTabAdviceId) other;

		return (this.getIdTab() == castOther.getIdTab()) && (this.getIdAdvice() == castOther.getIdAdvice());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTab();
		result = 37 * result + this.getIdAdvice();
		return result;
	}

}
