package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvTabAdvice generated by hbm2java
 */
@Entity
@Table(name = "nv_tab_advice", catalog = "NVPrestashop")
public class NvTabAdvice implements java.io.Serializable {

	private NvTabAdviceId id;

	public NvTabAdvice() {
	}

	public NvTabAdvice(NvTabAdviceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idTab", column = @Column(name = "id_tab", nullable = false)),
			@AttributeOverride(name = "idAdvice", column = @Column(name = "id_advice", nullable = false)) })
	public NvTabAdviceId getId() {
		return this.id;
	}

	public void setId(NvTabAdviceId id) {
		this.id = id;
	}

}
