package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvTaxLang generated by hbm2java
 */
@Entity
@Table(name = "nv_tax_lang", catalog = "NVPrestashop")
public class NvTaxLang implements java.io.Serializable {

	private NvTaxLangId id;
	private String name;

	public NvTaxLang() {
	}

	public NvTaxLang(NvTaxLangId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idTax", column = @Column(name = "id_tax", nullable = false)),
			@AttributeOverride(name = "idLang", column = @Column(name = "id_lang", nullable = false)) })
	public NvTaxLangId getId() {
		return this.id;
	}

	public void setId(NvTaxLangId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
