package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvTaxRulesGroupShop generated by hbm2java
 */
@Entity
@Table(name = "nv_tax_rules_group_shop", catalog = "NVPrestashop")
public class NvTaxRulesGroupShop implements java.io.Serializable {

	private NvTaxRulesGroupShopId id;

	public NvTaxRulesGroupShop() {
	}

	public NvTaxRulesGroupShop(NvTaxRulesGroupShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idTaxRulesGroup", column = @Column(name = "id_tax_rules_group", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvTaxRulesGroupShopId getId() {
		return this.id;
	}

	public void setId(NvTaxRulesGroupShopId id) {
		this.id = id;
	}

}
