package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvThemeconfigurator generated by hbm2java
 */
@Entity
@Table(name = "nv_themeconfigurator", catalog = "NVPrestashop")
public class NvThemeconfigurator implements java.io.Serializable {

	private Integer idItem;
	private int idShop;
	private int idLang;
	private int itemOrder;
	private String title;
	private boolean titleUse;
	private String hook;
	private String url;
	private boolean target;
	private String image;
	private String imageW;
	private String imageH;
	private String html;
	private boolean active;

	public NvThemeconfigurator() {
	}

	public NvThemeconfigurator(int idShop, int idLang, int itemOrder, boolean titleUse, boolean target, boolean active) {
		this.idShop = idShop;
		this.idLang = idLang;
		this.itemOrder = itemOrder;
		this.titleUse = titleUse;
		this.target = target;
		this.active = active;
	}

	public NvThemeconfigurator(int idShop, int idLang, int itemOrder, String title, boolean titleUse, String hook, String url, boolean target, String image,
					String imageW, String imageH, String html, boolean active) {
		this.idShop = idShop;
		this.idLang = idLang;
		this.itemOrder = itemOrder;
		this.title = title;
		this.titleUse = titleUse;
		this.hook = hook;
		this.url = url;
		this.target = target;
		this.image = image;
		this.imageW = imageW;
		this.imageH = imageH;
		this.html = html;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_item", unique = true, nullable = false)
	public Integer getIdItem() {
		return this.idItem;
	}

	public void setIdItem(Integer idItem) {
		this.idItem = idItem;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_lang", nullable = false)
	public int getIdLang() {
		return this.idLang;
	}

	public void setIdLang(int idLang) {
		this.idLang = idLang;
	}

	@Column(name = "item_order", nullable = false)
	public int getItemOrder() {
		return this.itemOrder;
	}

	public void setItemOrder(int itemOrder) {
		this.itemOrder = itemOrder;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "title_use", nullable = false)
	public boolean isTitleUse() {
		return this.titleUse;
	}

	public void setTitleUse(boolean titleUse) {
		this.titleUse = titleUse;
	}

	@Column(name = "hook", length = 100)
	public String getHook() {
		return this.hook;
	}

	public void setHook(String hook) {
		this.hook = hook;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "target", nullable = false)
	public boolean isTarget() {
		return this.target;
	}

	public void setTarget(boolean target) {
		this.target = target;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "image_w", length = 10)
	public String getImageW() {
		return this.imageW;
	}

	public void setImageW(String imageW) {
		this.imageW = imageW;
	}

	@Column(name = "image_h", length = 10)
	public String getImageH() {
		return this.imageH;
	}

	public void setImageH(String imageH) {
		this.imageH = imageH;
	}

	@Column(name = "html", length = 65535)
	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
