package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvThemeSpecific generated by hbm2java
 */
@Entity
@Table(name = "nv_theme_specific", catalog = "NVPrestashop")
public class NvThemeSpecific implements java.io.Serializable {

	private NvThemeSpecificId id;

	public NvThemeSpecific() {
	}

	public NvThemeSpecific(NvThemeSpecificId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idTheme", column = @Column(name = "id_theme", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)),
			@AttributeOverride(name = "entity", column = @Column(name = "entity", nullable = false)),
			@AttributeOverride(name = "idObject", column = @Column(name = "id_object", nullable = false)) })
	public NvThemeSpecificId getId() {
		return this.id;
	}

	public void setId(NvThemeSpecificId id) {
		this.id = id;
	}

}
