package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvThemeSpecificId generated by hbm2java
 */
@Embeddable
public class NvThemeSpecificId implements java.io.Serializable {

	private int idTheme;
	private int idShop;
	private int entity;
	private int idObject;

	public NvThemeSpecificId() {
	}

	public NvThemeSpecificId(int idTheme, int idShop, int entity, int idObject) {
		this.idTheme = idTheme;
		this.idShop = idShop;
		this.entity = entity;
		this.idObject = idObject;
	}

	@Column(name = "id_theme", nullable = false)
	public int getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(int idTheme) {
		this.idTheme = idTheme;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "entity", nullable = false)
	public int getEntity() {
		return this.entity;
	}

	public void setEntity(int entity) {
		this.entity = entity;
	}

	@Column(name = "id_object", nullable = false)
	public int getIdObject() {
		return this.idObject;
	}

	public void setIdObject(int idObject) {
		this.idObject = idObject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvThemeSpecificId))
			return false;
		NvThemeSpecificId castOther = (NvThemeSpecificId) other;

		return (this.getIdTheme() == castOther.getIdTheme()) && (this.getIdShop() == castOther.getIdShop()) && (this.getEntity() == castOther.getEntity())
						&& (this.getIdObject() == castOther.getIdObject());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTheme();
		result = 37 * result + this.getIdShop();
		result = 37 * result + this.getEntity();
		result = 37 * result + this.getIdObject();
		return result;
	}

}
