package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvWarehouseShop generated by hbm2java
 */
@Entity
@Table(name = "nv_warehouse_shop", catalog = "NVPrestashop")
public class NvWarehouseShop implements java.io.Serializable {

	private NvWarehouseShopId id;

	public NvWarehouseShop() {
	}

	public NvWarehouseShop(NvWarehouseShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idWarehouse", column = @Column(name = "id_warehouse", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvWarehouseShopId getId() {
		return this.id;
	}

	public void setId(NvWarehouseShopId id) {
		this.id = id;
	}

}
