package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvWarehouse generated by hbm2java
 */
@Entity
@Table(name = "nv_warehouse", catalog = "NVPrestashop")
public class NvWarehouse implements java.io.Serializable {

	private Integer idWarehouse;
	private int idCurrency;
	private int idAddress;
	private int idEmployee;
	private String reference;
	private String name;
	private String managementType;
	private boolean deleted;

	public NvWarehouse() {
	}

	public NvWarehouse(int idCurrency, int idAddress, int idEmployee, String name, String managementType, boolean deleted) {
		this.idCurrency = idCurrency;
		this.idAddress = idAddress;
		this.idEmployee = idEmployee;
		this.name = name;
		this.managementType = managementType;
		this.deleted = deleted;
	}

	public NvWarehouse(int idCurrency, int idAddress, int idEmployee, String reference, String name, String managementType, boolean deleted) {
		this.idCurrency = idCurrency;
		this.idAddress = idAddress;
		this.idEmployee = idEmployee;
		this.reference = reference;
		this.name = name;
		this.managementType = managementType;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_warehouse", unique = true, nullable = false)
	public Integer getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(Integer idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "id_currency", nullable = false)
	public int getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(int idCurrency) {
		this.idCurrency = idCurrency;
	}

	@Column(name = "id_address", nullable = false)
	public int getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(int idAddress) {
		this.idAddress = idAddress;
	}

	@Column(name = "id_employee", nullable = false)
	public int getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(int idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "reference", length = 32)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "management_type", nullable = false, length = 4)
	public String getManagementType() {
		return this.managementType;
	}

	public void setManagementType(String managementType) {
		this.managementType = managementType;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
