package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvWarehouseShopId generated by hbm2java
 */
@Embeddable
public class NvWarehouseShopId implements java.io.Serializable {

	private int idWarehouse;
	private int idShop;

	public NvWarehouseShopId() {
	}

	public NvWarehouseShopId(int idWarehouse, int idShop) {
		this.idWarehouse = idWarehouse;
		this.idShop = idShop;
	}

	@Column(name = "id_warehouse", nullable = false)
	public int getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(int idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvWarehouseShopId))
			return false;
		NvWarehouseShopId castOther = (NvWarehouseShopId) other;

		return (this.getIdWarehouse() == castOther.getIdWarehouse()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdWarehouse();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
