package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvWebserviceAccount generated by hbm2java
 */
@Entity
@Table(name = "nv_webservice_account", catalog = "NVPrestashop")
public class NvWebserviceAccount implements java.io.Serializable {

	private Integer idWebserviceAccount;
	private String key;
	private String description;
	private String className;
	private byte isModule;
	private String moduleName;
	private byte active;

	public NvWebserviceAccount() {
	}

	public NvWebserviceAccount(String key, String className, byte isModule, byte active) {
		this.key = key;
		this.className = className;
		this.isModule = isModule;
		this.active = active;
	}

	public NvWebserviceAccount(String key, String description, String className, byte isModule, String moduleName, byte active) {
		this.key = key;
		this.description = description;
		this.className = className;
		this.isModule = isModule;
		this.moduleName = moduleName;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_webservice_account", unique = true, nullable = false)
	public Integer getIdWebserviceAccount() {
		return this.idWebserviceAccount;
	}

	public void setIdWebserviceAccount(Integer idWebserviceAccount) {
		this.idWebserviceAccount = idWebserviceAccount;
	}

	@Column(name = "key", nullable = false, length = 32)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "class_name", nullable = false, length = 50)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "is_module", nullable = false)
	public byte getIsModule() {
		return this.isModule;
	}

	public void setIsModule(byte isModule) {
		this.isModule = isModule;
	}

	@Column(name = "module_name", length = 50)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "active", nullable = false)
	public byte getActive() {
		return this.active;
	}

	public void setActive(byte active) {
		this.active = active;
	}

}
