package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvWebBrowser generated by hbm2java
 */
@Entity
@Table(name = "nv_web_browser", catalog = "NVPrestashop")
public class NvWebBrowser implements java.io.Serializable {

	private Integer idWebBrowser;
	private String name;

	public NvWebBrowser() {
	}

	public NvWebBrowser(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_web_browser", unique = true, nullable = false)
	public Integer getIdWebBrowser() {
		return this.idWebBrowser;
	}

	public void setIdWebBrowser(Integer idWebBrowser) {
		this.idWebBrowser = idWebBrowser;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
