package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvWishlistProductCart generated by hbm2java
 */
@Entity
@Table(name = "nv_wishlist_product_cart", catalog = "NVPrestashop")
public class NvWishlistProductCart implements java.io.Serializable {

	private NvWishlistProductCartId id;

	public NvWishlistProductCart() {
	}

	public NvWishlistProductCart(NvWishlistProductCartId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idWishlistProduct", column = @Column(name = "id_wishlist_product", nullable = false)),
			@AttributeOverride(name = "idCart", column = @Column(name = "id_cart", nullable = false)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false)),
			@AttributeOverride(name = "dateAdd", column = @Column(name = "date_add", nullable = false, length = 0)) })
	public NvWishlistProductCartId getId() {
		return this.id;
	}

	public void setId(NvWishlistProductCartId id) {
		this.id = id;
	}

}
