package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NvWishlist generated by hbm2java
 */
@Entity
@Table(name = "nv_wishlist", catalog = "NVPrestashop")
public class NvWishlist implements java.io.Serializable {

	private Integer idWishlist;
	private int idCustomer;
	private String token;
	private String name;
	private Integer counter;
	private Integer idShop;
	private Integer idShopGroup;
	private Date dateAdd;
	private Date dateUpd;
	private Integer default_;

	public NvWishlist() {
	}

	public NvWishlist(int idCustomer, String token, String name, Date dateAdd, Date dateUpd) {
		this.idCustomer = idCustomer;
		this.token = token;
		this.name = name;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
	}

	public NvWishlist(int idCustomer, String token, String name, Integer counter, Integer idShop, Integer idShopGroup, Date dateAdd, Date dateUpd,
					Integer default_) {
		this.idCustomer = idCustomer;
		this.token = token;
		this.name = name;
		this.counter = counter;
		this.idShop = idShop;
		this.idShopGroup = idShopGroup;
		this.dateAdd = dateAdd;
		this.dateUpd = dateUpd;
		this.default_ = default_;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_wishlist", unique = true, nullable = false)
	public Integer getIdWishlist() {
		return this.idWishlist;
	}

	public void setIdWishlist(Integer idWishlist) {
		this.idWishlist = idWishlist;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "token", nullable = false, length = 64)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "counter")
	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	@Column(name = "id_shop")
	public Integer getIdShop() {
		return this.idShop;
	}

	public void setIdShop(Integer idShop) {
		this.idShop = idShop;
	}

	@Column(name = "id_shop_group")
	public Integer getIdShopGroup() {
		return this.idShopGroup;
	}

	public void setIdShopGroup(Integer idShopGroup) {
		this.idShopGroup = idShopGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_upd", nullable = false, length = 0)
	public Date getDateUpd() {
		return this.dateUpd;
	}

	public void setDateUpd(Date dateUpd) {
		this.dateUpd = dateUpd;
	}

	@Column(name = "default")
	public Integer getDefault_() {
		return this.default_;
	}

	public void setDefault_(Integer default_) {
		this.default_ = default_;
	}

}
