package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvWishlistEmailId generated by hbm2java
 */
@Embeddable
public class NvWishlistEmailId implements java.io.Serializable {

	private int idWishlist;
	private String email;
	private Date dateAdd;

	public NvWishlistEmailId() {
	}

	public NvWishlistEmailId(int idWishlist, String email, Date dateAdd) {
		this.idWishlist = idWishlist;
		this.email = email;
		this.dateAdd = dateAdd;
	}

	@Column(name = "id_wishlist", nullable = false)
	public int getIdWishlist() {
		return this.idWishlist;
	}

	public void setIdWishlist(int idWishlist) {
		this.idWishlist = idWishlist;
	}

	@Column(name = "email", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "date_add", nullable = false, length = 0)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvWishlistEmailId))
			return false;
		NvWishlistEmailId castOther = (NvWishlistEmailId) other;

		return (this.getIdWishlist() == castOther.getIdWishlist())
						&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null && castOther.getEmail() != null && this.getEmail().equals(
										castOther.getEmail())))
						&& ((this.getDateAdd() == castOther.getDateAdd()) || (this.getDateAdd() != null && castOther.getDateAdd() != null && this.getDateAdd()
										.equals(castOther.getDateAdd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdWishlist();
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getDateAdd() == null ? 0 : this.getDateAdd().hashCode());
		return result;
	}

}
