package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NvZoneShop generated by hbm2java
 */
@Entity
@Table(name = "nv_zone_shop", catalog = "NVPrestashop")
public class NvZoneShop implements java.io.Serializable {

	private NvZoneShopId id;

	public NvZoneShop() {
	}

	public NvZoneShop(NvZoneShopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idZone", column = @Column(name = "id_zone", nullable = false)),
			@AttributeOverride(name = "idShop", column = @Column(name = "id_shop", nullable = false)) })
	public NvZoneShopId getId() {
		return this.id;
	}

	public void setId(NvZoneShopId id) {
		this.id = id;
	}

}
