package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NvZone generated by hbm2java
 */
@Entity
@Table(name = "nv_zone", catalog = "NVPrestashop")
public class NvZone implements java.io.Serializable {

	private Integer idZone;
	private String name;
	private boolean active;

	public NvZone() {
	}

	public NvZone(String name, boolean active) {
		this.name = name;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_zone", unique = true, nullable = false)
	public Integer getIdZone() {
		return this.idZone;
	}

	public void setIdZone(Integer idZone) {
		this.idZone = idZone;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
