package com.nonveggies.entity;

// Generated Jan 2, 2016 7:30:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NvZoneShopId generated by hbm2java
 */
@Embeddable
public class NvZoneShopId implements java.io.Serializable {

	private int idZone;
	private int idShop;

	public NvZoneShopId() {
	}

	public NvZoneShopId(int idZone, int idShop) {
		this.idZone = idZone;
		this.idShop = idShop;
	}

	@Column(name = "id_zone", nullable = false)
	public int getIdZone() {
		return this.idZone;
	}

	public void setIdZone(int idZone) {
		this.idZone = idZone;
	}

	@Column(name = "id_shop", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NvZoneShopId))
			return false;
		NvZoneShopId castOther = (NvZoneShopId) other;

		return (this.getIdZone() == castOther.getIdZone()) && (this.getIdShop() == castOther.getIdShop());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdZone();
		result = 37 * result + this.getIdShop();
		return result;
	}

}
